/**
 * comeback 世界线内容（复出线）。
 * 入口为既有 comeback-injury → comeback-rust；本文件内容 gated 在 done(comeback-rust) 之后。
 */
import {
  attr, stat, flag, rmFlag, wl, transfer, role, trophy, cstat,
  done, hasFlag, age, statCond, attrCond, ANY, ALL, NONE, gm,
  MORALE, ENERGY, BALANCE, STRESS, RATING2,
  AIM, GAME_SENSE, LEADERSHIP, CLUTCH, CONSISTENCY, TEAM_CONFLICT,
} from './helpers.js';

const GATE = done('comeback-rust');

export default [
  // ============ 主线：康复与回归 ============
  {
    id: 'comeback-rehab-plan', title: '康复计划', period: 'NORMAL', conds: [GATE],
    desc: '医生给了你一份半年的康复计划：理疗、力量、还有最难的——等待。',
    options: [
      { id: 'follow-plan', label: '严格按计划执行', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), flag('REHAB_TRACK', '康复进行中', 'CAREER')], msg: ['你每天按计划打卡。', '康复师说你的进度比预期快。'], next: 'comeback-physio-battle' },
        f: { fx: [stat(STRESS, 8)], msg: ['计划坚持了两周就开始偷工减料。', '康复师看你的眼神多了些无奈。'], next: 'comeback-physio-battle' } },
      { id: 'rush-rehab', label: '想加快进度', chance: 0.45,
        s: { fx: [stat(MORALE, 6), stat(ENERGY, -4)], msg: ['你私自加大了训练量。', '康复师说：你这样会前功尽弃。'], next: 'comeback-physio-battle' },
        f: { fx: [stat(ENERGY, -10), stat(STRESS, 8)], msg: ['加练让伤处重新肿胀。', '你被迫退回到康复初期。'], next: 'comeback-physio-battle' } },
    ],
  },
  {
    id: 'comeback-physio-battle', title: '复健挣扎', period: 'NORMAL', conds: [done('comeback-rehab-plan')],
    desc: '复健的每一天都在和疼痛打交道。你问康复师：什么时候才是个头。',
    options: [
      { id: 'endure-pain', label: '咬牙坚持', chance: 0.6,
        s: { fx: [stat(ENERGY, 8), stat(MORALE, 6)], msg: ['疼归疼，但你一天都没断。', '两个月后，你的力量回到了八成。'], next: 'comeback-mental-shadow' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['疼痛让你开始逃避复健。', '进度落下了两周。'], next: 'comeback-mental-shadow' } },
      { id: 'adjust-pace', label: '按身体反应调整', chance: 0.65,
        s: { fx: [stat(STRESS, -6), stat(ENERGY, 8)], msg: ['你学会了听身体的话。', '康复师说你「终于开窍了」。'], next: 'comeback-mental-shadow' },
        f: { fx: [stat(ENERGY, -4)], msg: ['太听身体的话，你休息得过头了。', '康复进度慢了下来。'], next: 'comeback-mental-shadow' } },
    ],
  },
  {
    id: 'comeback-mental-shadow', title: '心理阴影', period: 'NORMAL', conds: [done('comeback-physio-battle')],
    desc: '身体恢复了大半，但心理还没跟上。每次发力，你都本能地护住伤处。',
    options: [
      { id: 'shadow-boxing', label: '直面恐惧', chance: 0.55,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 6)], msg: ['你开始做受伤动作的模拟练习。', '第一次做的时候手在抖，第十次就稳了。'], next: 'comeback-first-scrim' },
        f: { fx: [stat(STRESS, 12)], msg: ['你越想克服越害怕。', '心理医生建议你慢慢来。'], next: 'comeback-first-scrim' } },
      { id: 'avoid-trigger', label: '暂时避开', chance: 0.65,
        s: { fx: [stat(STRESS, -6)], msg: ['你暂时避开高强度对抗。', '心理负担小了些，但你心里清楚躲不过。'], next: 'comeback-first-scrim' },
        f: { fx: [stat(MORALE, -4)], msg: ['避开变成习惯，你越来越不敢发力。', '这比伤病本身更可怕。'], next: 'comeback-first-scrim' } },
    ],
  },
  {
    id: 'comeback-first-scrim', title: '首场训练赛', period: 'NORMAL', conds: [done('comeback-mental-shadow')],
    desc: '医生批准你参加非对抗训练赛。坐上熟悉的位置，你的手有点抖。',
    options: [
      { id: 'gentle-return', label: '先找节奏', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 8)], msg: ['你打得很保守，但节奏还在。', '教练说：你的脑子没锈。'], next: 'comeback-bench-return' },
        f: { fx: [stat(STRESS, 10)], msg: ['你的反应速度比自己想象得慢。', '「我真的还能打吗」在脑子里冒了出来。'], next: 'comeback-bench-return' } },
      { id: 'prove-now2', label: '证明自己没退步', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 8)], msg: ['你打出了几个漂亮枪。', '但之后手腕开始发酸，你不敢继续用力。'], next: 'comeback-bench-return' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['想证明反而暴露了生疏。', '训练赛你成了队里的短板。'], next: 'comeback-bench-return' } },
    ],
  },
  {
    id: 'comeback-bench-return', title: '替补回归', period: 'NORMAL', conds: [done('comeback-first-scrim')],
    desc: '你回到了正式名单，但只是替补。那个顶替你首发的人打得很不错。',
    options: [
      { id: 'bench-patient', label: '耐心等待机会', chance: 0.65,
        s: { fx: [stat(MORALE, 6), stat(STRESS, -4)], msg: ['你坐回替补席，认真看比赛。', '你发现新人确实有值得学的地方。'], next: 'comeback-crowd-fear' },
        f: { fx: [stat(MORALE, -6)], msg: ['替补席让你焦躁。', '「这是我的位置」的念头一直冒出来。'], next: 'comeback-crowd-fear' } },
      { id: 'push-coach', label: '向教练要上场时间', chance: 0.5,
        s: { fx: [stat(MORALE, 8), stat(TEAM_CONFLICT, 1)], msg: ['教练给了你半场机会。', '你打出了点东西，但还不足以夺回首发。'], next: 'comeback-crowd-fear' },
        f: { fx: [stat(TEAM_CONFLICT, 3), stat(STRESS, 8)], msg: ['要时间让教练觉得你「急了」。', '你的机会被压得更后了。'], next: 'comeback-crowd-fear' } },
    ],
  },
  {
    id: 'comeback-crowd-fear', title: '观众恐惧', period: 'NORMAL', conds: [done('comeback-bench-return')],
    desc: '你重新站上线下舞台。全场喊的不是你的 ID，而是那个顶替你的新人。',
    options: [
      { id: 'own-the-noise', label: '把声音当背景', chance: 0.55,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你屏蔽了杂音，专注比赛。', '打进两个关键局后，有人开始喊你的名字。'], next: 'comeback-first-map' },
        f: { fx: [stat(STRESS, 12)], msg: ['别人的欢呼像针一样扎着你。', '这场比赛你打得魂不守舍。'], next: 'comeback-first-map' } },
      { id: 'win-them-back', label: '用表现赢回欢呼', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.008 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 10)], msg: ['你在关键时刻接管了比赛。', '最后全场都在喊你的 ID。'], next: 'comeback-first-map' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['越想赢回欢呼，打得越急。', '你输掉了这场证明战。'], next: 'comeback-first-map' } },
    ],
  },
  {
    id: 'comeback-first-map', title: '复出首图', period: 'NORMAL', conds: [done('comeback-crowd-fear')],
    desc: '教练让你打首发的第一张图。对面刚好是当年让你受伤的那支队。',
    options: [
      { id: 'face-old-rival', label: '正面刚', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('TOTAL_KILLS', 35), stat(MORALE, 12)], msg: ['你面对那支队打出了 35 击杀。', '赛后他们的选手向你点头致意。'], next: 'comeback-owner-support' },
        f: { fx: [stat(STRESS, 12)], msg: ['面对他们，你的心理阴影又冒出来了。', '那张图你打得一塌糊涂。'], next: 'comeback-owner-support' } },
      { id: 'steady-return2', label: '稳定发挥', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 8)], msg: ['你没有刻意针对谁，打得四平八稳。', '「他回来了」的评价开始出现。'], next: 'comeback-owner-support' },
        f: { fx: [stat(MORALE, -4)], msg: ['稳定发挥变成了平庸发挥。', '「他还能回巅峰吗」的声音又来了。'], next: 'comeback-owner-support' } },
    ],
  },
  {
    id: 'comeback-owner-support', title: '俱乐部支持', period: 'NORMAL', conds: [done('comeback-first-map')],
    desc: '老板约你吃饭，说俱乐部相信你的复出，愿意给你一份新合同。',
    options: [
      { id: 'accept-deal', label: '接受新合同', chance: 0.7,
        s: { fx: [cstat('CAREER_EARNINGS', 5000), stat(MORALE, 10)], msg: ['新合同谈得很顺利。', '老板说：我们等了你一年。'], next: 'comeback-teammate-welcome' },
        f: { fx: [stat(STRESS, 6)], msg: ['合同细节让你犹豫了一下。', '但老板的诚意是实的。'], next: 'comeback-teammate-welcome' } },
      { id: 'ask-wait', label: '先打出身价再谈', chance: 0.55,
        s: { fx: [stat(MORALE, 8)], msg: ['你想用表现说话。', '老板说：行，那我们等你的好消息。'], next: 'comeback-teammate-welcome' },
        f: { fx: [stat(STRESS, 8)], msg: ['拖着不谈让管理层觉得你「心不定」。', '续约谈判的窗口悄悄关小了一点。'], next: 'comeback-teammate-welcome' } },
    ],
  },
  {
    id: 'comeback-teammate-welcome', title: '队友接纳', period: 'NORMAL', conds: [done('comeback-owner-support')],
    desc: '队里换了不少新面孔。他们看你像看「传说」，客气里带着距离。',
    options: [
      { id: 'break-ice', label: '主动破冰', chance: 0.65,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 8), flag('TEAM_ACCEPTED', '被队友接纳', 'CAREER')], msg: ['你请全队吃了顿火锅。', '饭桌上，新人开始喊你「老哥」。'], next: 'comeback-form-60' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['你试着融入，但老觉得隔着一层。', '「传说」的称号反而成了墙。'], next: 'comeback-form-60' } },
      { id: 'prove-first', label: '先证明自己', chance: 0.6,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你选择用训练赛表现说话。', '几周后，新人们对你的态度自然多了。'], next: 'comeback-form-60' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['证明自己的过程很慢。', '你和新人们的磨合磕磕绊绊。'], next: 'comeback-form-60' } },
    ],
  },
  {
    id: 'comeback-form-60', title: '六成状态', period: 'NORMAL', conds: [done('comeback-teammate-welcome')],
    desc: '复出一个月的你，大概恢复到了巅峰的六成。医生说的「完全恢复」还很远。',
    options: [
      { id: 'accept-60', label: '接受现状慢慢来', chance: 0.65,
        s: { fx: [stat(STRESS, -6), attr(CONSISTENCY, 2)], msg: ['你接受六成状态，不和过去比。', '复健节奏反而快了起来。'], next: 'comeback-rival-doubt' },
        f: { fx: [stat(STRESS, 8)], msg: ['「只有六成」让你焦虑。', '你开始和自己较劲。'], next: 'comeback-rival-doubt' } },
      { id: 'push-80', label: '想尽快到八成', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 6), stat(ENERGY, -6)], msg: ['你加了强度，状态勉强到了七成。', '但你知道这不是恢复，是透支。'], next: 'comeback-rival-doubt' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 8)], msg: ['急于求成让你差点二次受伤。', '康复师严厉地批评了你。'], next: 'comeback-rival-doubt' } },
    ],
  },
  {
    id: 'comeback-rival-doubt', title: '对手质疑', period: 'NORMAL', conds: [done('comeback-form-60')],
    desc: '有对手在采访里说：「他早就不行了，复出只是情怀。」',
    options: [
      { id: 'silent-response', label: '不回应', chance: 0.65,
        s: { fx: [stat(STRESS, -4), stat(MORALE, 6)], msg: ['你什么都没说。', '你打算在比赛里回答。'], next: 'comeback-ignite' },
        f: { fx: [stat(STRESS, 8)], msg: ['你的沉默被当成默认。', '质疑声更大了一些。'], next: 'comeback-ignite' } },
      { id: 'verbal-counter', label: '采访里回应', chance: 0.55,
        s: { fx: [stat(MORALE, 8)], msg: ['你说：球场见。', '这句话被反复剪辑播放。'], next: 'comeback-ignite' },
        f: { fx: [stat(STRESS, 10)], msg: ['你的回应被断章取义，成了「嘴硬」。', '你只能靠比赛翻盘。'], next: 'comeback-ignite' } },
    ],
  },
  {
    id: 'comeback-ignite', title: '状态点燃', period: 'NORMAL', conds: [done('comeback-rival-doubt')],
    desc: '和那支队正式相遇。你打出了复出以来最好的一场比赛，点燃了全场。',
    options: [
      { id: 'vindicate', label: '用胜利回应质疑', chance: 0.6, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 14), cstat('TOTAL_KILLS', 40)], msg: ['你们赢了，你打出了关键表现。', '赛后采访，你只说了一句：我说过球场见。'], next: 'comeback-reinjury-scare' },
        f: { fx: [stat(STRESS, 10)], msg: ['你很想赢，但状态没跟上。', '质疑声变成了事实的注脚。'], next: 'comeback-reinjury-scare' } },
      { id: 'team-win', label: '靠团队取胜', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 8)], msg: ['你没当英雄，但每个关键点都有你。', '教练说：这就是老将的价值。'], next: 'comeback-reinjury-scare' },
        f: { fx: [stat(MORALE, -4)], msg: ['团队没赢下来。', '但你的状态确实在回升。'], next: 'comeback-reinjury-scare' } },
    ],
  },
  {
    id: 'comeback-reinjury-scare', title: '旧伤警报', period: 'NORMAL', conds: [done('comeback-ignite')],
    desc: '一场加时赛后，你的手腕突然疼得握不住鼠标。你僵在椅子上。',
    options: [
      { id: 'immediate-check', label: '立刻去检查', chance: 0.65,
        s: { fx: [stat(STRESS, -6), flag('REINJURY_CLEAR', '旧伤未复发', 'CAREER')], msg: ['检查结果：只是疲劳，没有复发。', '你长舒了一口气。'], next: 'comeback-protect-ratio' },
        f: { fx: [stat(STRESS, 10)], msg: ['等待结果的两小时，你坐立难安。', '「又要倒下了吗」在脑子里循环。'], next: 'comeback-protect-ratio' } },
      { id: 'hide-it', label: '先瞒着打完赛季', chance: 0.45,
        s: { fx: [stat(MORALE, 6), stat(STRESS, 10)], msg: ['你选择撑完这个赛季。', '表现没下滑，但你知道自己在赌。'], next: 'comeback-protect-ratio' },
        f: { fx: [stat(STRESS, 14), stat(ENERGY, -8)], msg: ['瞒着伤打完赛季，你的状态彻底崩了。', '队医发现时，已经晚了。'], next: 'comeback-protect-ratio' } },
    ],
  },
  {
    id: 'comeback-protect-ratio', title: '保护比例', period: 'NORMAL', conds: [done('comeback-reinjury-scare')],
    desc: '队医要求你限制训练时长：每天最多 5 小时。你担心这会拖累恢复速度。',
    options: [
      { id: 'respect-limit', label: '遵守时长限制', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), attr(CONSISTENCY, 2)], msg: ['你开始科学安排训练。', '5 小时的效率比 10 小时还高。'], next: 'comeback-media-hype2' },
        f: { fx: [stat(STRESS, 6)], msg: ['你总觉得练不够，偷偷加时。', '被队医抓包后，限制更严了。'], next: 'comeback-media-hype2' } },
      { id: 'bargain-hours', label: '争取更多时间', chance: 0.55,
        s: { fx: [stat(MORALE, 6)], msg: ['你和管理层谈判，争取到 7 小时。', '代价是每周多一次理疗。'], next: 'comeback-media-hype2' },
        f: { fx: [stat(STRESS, 8)], msg: ['谈判没谈成，你还有点不服。', '但队医的坚持后来证明是对的。'], next: 'comeback-media-hype2' } },
    ],
  },
  {
    id: 'comeback-media-hype2', title: '复出热度', period: 'NORMAL', conds: [done('comeback-protect-ratio')],
    desc: '媒体开始写你的复出故事：「从伤病到回归，他用了 400 天。」采访邀约涌来。',
    options: [
      { id: 'share-story', label: '分享完整故事', chance: 0.65,
        s: { fx: [stat(MORALE, 8), cstat('CAREER_EARNINGS', 1000)], msg: ['你讲了 400 天的细节，包括最难的那段。', '报道发出去后，评论区都在鼓励你。'], next: 'comeback-doc-checks' },
        f: { fx: [stat(STRESS, 8)], msg: ['故事讲得太沉重，媒体剪得面目全非。', '你决定以后少说两句。'], next: 'comeback-doc-checks' } },
      { id: 'low-key', label: '低调处理', chance: 0.7,
        s: { fx: [stat(STRESS, -6)], msg: ['你只接受了一次简单采访。', '热度过去后，你继续安静训练。'], next: 'comeback-doc-checks' },
        f: { fx: [stat(MORALE, -4)], msg: ['低调让你错过了一次曝光机会。', '经纪人替你可惜。'], next: 'comeback-doc-checks' } },
    ],
  },
  {
    id: 'comeback-doc-checks', title: '体检报告', period: 'NORMAL', conds: [done('comeback-media-hype2')],
    desc: '半年后的体检报告出来了。医生说你的身体机能「超出预期」。',
    options: [
      { id: 'celebrate-cautious', label: '高兴但保持警惕', chance: 0.65,
        s: { fx: [stat(MORALE, 10), stat(STRESS, -4)], msg: ['你确实恢复了，但还差最后的临门一脚。', '你把这当动力，而不是终点。'], next: 'comeback-contract-extension' },
        f: { fx: [stat(STRESS, 6)], msg: ['报告让你飘了几天。', '恢复≠完全，你提醒自己。'], next: 'comeback-contract-extension' } },
      { id: 'push-limit2', label: '认为可以全力了', chance: 0.55,
        s: { fx: [attr(AIM, 3), stat(MORALE, 8), stat(ENERGY, -6)], msg: ['你解除了自我限制，全力训练。', '状态确实上来了，但风险也在累积。'], next: 'comeback-contract-extension' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 8)], msg: ['全力训练让旧伤处开始抗议。', '你被迫退回到保护模式。'], next: 'comeback-contract-extension' } },
    ],
  },
  {
    id: 'comeback-contract-extension', title: '续约谈判', period: 'TRANSFER_WINDOW', conds: [done('comeback-doc-checks')],
    desc: '俱乐部想和你续约三年，但薪水只有巅峰期的一半。',
    options: [
      { id: 'accept-extension', label: '接受续约', chance: 0.65,
        s: { fx: [cstat('CAREER_EARNINGS', 4000), stat(MORALE, 8)], msg: ['你签了三年。', '签完字，老板说：欢迎回家。'], next: 'comeback-role-change3' },
        f: { fx: [stat(STRESS, 8)], msg: ['三年合同让你犹豫了很久。', '「万一恢复不了呢」的想法挥之不去。'], next: 'comeback-role-change3' } },
      { id: 'test-market', label: '试试自由市场', chance: 0.55,
        s: { fx: [transfer('g2'), stat(MORALE, 10)], msg: ['市场给出了更好的报价。', '你转会了，带着 400 天的故事。'], next: 'comeback-role-change3' },
        f: { fx: [stat(STRESS, 12)], msg: ['市场反应冷淡，你只能回来续约。', '谈判桌上你的底气弱了几分。'], next: 'comeback-role-change3' } },
    ],
  },
  {
    id: 'comeback-role-change3', title: '位置调整', period: 'NORMAL', conds: [done('comeback-contract-extension')],
    desc: '教练建议你换个位置：「你的反应不如以前，但你的经验能打辅助位。」',
    options: [
      { id: 'try-support', label: '转型辅助', chance: 0.6,
        s: { fx: [role('SUPPORT'), attr(GAME_SENSE, 3), stat(MORALE, 8)], msg: ['你开始打辅助位，用经验补反应。', '这个位置意外地适合复出后的你。'], next: 'comeback-captain-offer3' },
        f: { fx: [stat(MORALE, -6), stat(STRESS, 8)], msg: ['辅助位让你觉得「被降级」。', '转型初期你打得很别扭。'], next: 'comeback-captain-offer3' } },
      { id: 'keep-role2', label: '坚持原位置', chance: 0.55,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你留在原位置，靠调整打法弥补反应。', '打得不算差，但确实吃力。'], next: 'comeback-captain-offer3' },
        f: { fx: [stat(STRESS, 10)], msg: ['原位置对反应的要求越来越高。', '你开始怀疑自己能不能撑住。'], next: 'comeback-captain-offer3' } },
    ],
  },
  {
    id: 'comeback-captain-offer3', title: '队长邀请', period: 'NORMAL', conds: [done('comeback-role-change3')],
    desc: '教练提议让你当队长：「你的价值不在枪，在稳住这支队伍。」',
    options: [
      { id: 'take-lead', label: '接任队长', chance: 0.6, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), role('IGL'), stat(MORALE, 10)], msg: ['你接过了队长袖标。', '老将当队长，队伍确实稳了很多。'], next: 'comeback-new-rookie' },
        f: { fx: [stat(STRESS, 12)], msg: ['队长责任让你压力倍增。', '你怕自己的状态拖累全队。'], next: 'comeback-new-rookie' } },
      { id: 'decline-lead2', label: '让给年轻人', chance: 0.65,
        s: { fx: [stat(MORALE, 6), stat(TEAM_CONFLICT, -2)], msg: ['你推荐了队里的年轻指挥。', '你在旁边辅助他成长。'], next: 'comeback-new-rookie' },
        f: { fx: [stat(MORALE, -4)], msg: ['让贤让教练觉得你「没有野心」。', '你解释不清。'], next: 'comeback-new-rookie' } },
    ],
  },
  {
    id: 'comeback-new-rookie', title: '新秀冲击', period: 'NORMAL', conds: [done('comeback-captain-offer3')],
    desc: '俱乐部签了一个 17 岁的新人，和你同位置。训练赛里，他的枪法让你想起了年轻的自己。',
    options: [
      { id: 'mentor-rival', label: '认真带他', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8), flag('MENTOR_NEWGEN', '提携新人', 'CAREER')], msg: ['你把经验倾囊相授。', '他进步很快，喊你一声「师父」。'], next: 'comeback-mentor-new' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['你教得有所保留。', '「教会徒弟饿死师父」的念头闪过。'], next: 'comeback-mentor-new' } },
      { id: 'compete-hard', label: '全力竞争', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 8)], msg: ['你把竞争变成动力，状态回升。', '教练说：良性竞争是好事。'], next: 'comeback-mentor-new' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['竞争让你焦虑，状态下滑。', '新人的光芒更刺眼了。'], next: 'comeback-mentor-new' } },
    ],
  },
  {
    id: 'comeback-mentor-new', title: '师徒情谊', period: 'NORMAL', conds: [done('comeback-new-rookie')],
    desc: '新人私下约你吃饭，说自己把你当偶像。你想了想，决定告诉他真相。',
    options: [
      { id: 'honest-story', label: '讲真实的职业生涯', chance: 0.7,
        s: { fx: [stat(MORALE, 10), stat(TEAM_CONFLICT, -3)], msg: ['你讲了伤病、低谷、复出。', '他说：那我更要加油了。'], next: 'comeback-vet-battle' },
        f: { fx: [stat(STRESS, 6)], msg: ['你只讲了高光时刻。', '新人满怀憧憬，你心里却不是滋味。'], next: 'comeback-vet-battle' } },
      { id: 'hard-truth', label: '告诉他职业的残酷', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 6)], msg: ['你说：这个圈子会吃掉不努力的人。', '他沉默了一会儿，点了点头。'], next: 'comeback-vet-battle' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['话说太重，新人有点被吓到。', '你后来补了一次轻松的谈话。'], next: 'comeback-vet-battle' } },
    ],
  },
  {
    id: 'comeback-vet-battle', title: '老将对决', period: 'NORMAL', conds: [done('comeback-mentor-new')],
    desc: '你们遇上另一支队伍的老将，同样是伤后复出。媒体称之为「老兵不死」之战。',
    options: [
      { id: 'experience-duel', label: '用经验对决', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 10)], msg: ['你们打了一场充满算计的比赛。', '最后你赢了，他笑着和你拥抱。'], next: 'comeback-slump2' },
        f: { fx: [stat(STRESS, 8)], msg: ['你输给了他。', '「老兵不死，只是凋零」的标题让他占了。'], next: 'comeback-slump2' } },
      { id: 'respect-fight', label: '尊重对决', chance: 0.65,
        s: { fx: [stat(MORALE, 8)], msg: ['你们打得都很干净。', '赛后的握手比任何采访都有力。'], next: 'comeback-slump2' },
        f: { fx: [stat(MORALE, -4)], msg: ['比赛本身没什么亮点。', '媒体有点失望，但你们彼此认可。'], next: 'comeback-slump2' } },
    ],
  },
  {
    id: 'comeback-slump2', title: '状态反复', period: 'NORMAL', conds: [done('comeback-vet-battle')],
    desc: '复出后最怕的事发生了：你的状态又开始反复，好的时候像巅峰，差的时候像路人。',
    options: [
      { id: 'ride-dips', label: '接受起伏', chance: 0.6,
        s: { fx: [stat(STRESS, -6), attr(CONSISTENCY, 2)], msg: ['你接受这是恢复的一部分。', '起伏之间，整体趋势是向上的。'], next: 'comeback-comeback2' },
        f: { fx: [stat(MORALE, -6)], msg: ['你无法接受反复，心态开始崩。', '低谷期被你拉得更长。'], next: 'comeback-comeback2' } },
      { id: 'taper-load', label: '调整训练负荷', chance: 0.65,
        s: { fx: [stat(ENERGY, 8), stat(MORALE, 6)], msg: ['你和教练讨论后减了训练量。', '状态逐渐稳定下来。'], next: 'comeback-comeback2' },
        f: { fx: [stat(STRESS, 8)], msg: ['减量让你担心退步。', '你在「减」和「加」之间反复横跳。'], next: 'comeback-comeback2' } },
    ],
  },
  {
    id: 'comeback-comeback2', title: '再次回归', period: 'NORMAL', conds: [done('comeback-slump2')],
    desc: '你打出了复出以来最完整的一周：没有大爆发，但没有一场拖后腿。',
    options: [
      { id: 'steady-new-era', label: '接受新版本自己', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你意识到复出后的自己不可能和过去一样。', '但「不一样」也可以是「更好」。'], next: 'comeback-big-tournament' },
        f: { fx: [stat(STRESS, 6)], msg: ['你嘴上接受了，心里还在和过去较劲。', '那几天的梦都是巅峰期的自己。'], next: 'comeback-big-tournament' } },
      { id: 'push-peak', label: '想再摸一次巅峰', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 8), stat(ENERGY, -6)], msg: ['你朝着巅峰的方向训练。', '有些晚上，你真的摸到了那个状态。'], next: 'comeback-big-tournament' },
        f: { fx: [stat(ENERGY, -10), stat(STRESS, 8)], msg: ['追巅峰追得太用力，状态又滑了。', '你只能再次接受现实。'], next: 'comeback-big-tournament' } },
    ],
  },
  {
    id: 'comeback-big-tournament', title: '大赛回归', period: 'FINAL_DECISIVE_MOMENT', conds: [done('comeback-comeback2')],
    desc: '你以主力身份参加复出后的第一个大赛。开赛前，你发了条动态：我回来了。',
    options: [
      { id: 'calm-stage', label: '稳住节奏打', chance: 0.6, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你没有追求高光，但每一场都很扎实。', '「他回来了」成了媒体这周的关键词。'], next: 'comeback-semi-final' },
        f: { fx: [stat(STRESS, 10)], msg: ['大赛的强度让复出后的身体吃不消。', '小组赛你打得挣扎。'], next: 'comeback-semi-final' } },
      { id: 'statement-return', label: '打一场宣言战', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 14)], msg: ['你在淘汰赛首轮打出了复出代表作。', '「老兵不死」四个字重回标题。'], next: 'comeback-semi-final' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['宣言战打成了车祸现场。', '你被换下，坐回了熟悉的替补席。'], next: 'comeback-semi-final' } },
    ],
  },
  {
    id: 'comeback-semi-final', title: '半决赛', period: 'FINAL_DECISIVE_MOMENT', conds: [done('comeback-big-tournament')],
    desc: '你们杀进半决赛，对手是夺冠热门。赛前赔率不看好你们。',
    options: [
      { id: 'veteran-mind', label: '发挥老将经验', chance: 0.55, mods: [{ attribute: GAME_SENSE, perPoint: 0.009 }],
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 10)], msg: ['你用经验破解了他们的节奏。', '你们爆冷晋级决赛。'], next: 'comeback-final-return' },
        f: { fx: [stat(STRESS, 10)], msg: ['经验在绝对实力面前不够用。', '你们被碾压出局。'], next: 'comeback-final-return' } },
      { id: 'emotional-fuel', label: '用情绪当燃料', chance: 0.5,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 12)], msg: ['你的情绪感染了全队。', '你们带着火气赢下了半决赛。'], next: 'comeback-final-return' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['情绪让你上头，关键局失误。', '半决赛止步。'], next: 'comeback-final-return' } },
    ],
  },
  {
    id: 'comeback-final-return', title: '决赛回归', period: 'FINAL_DECISIVE_MOMENT', conds: [done('comeback-semi-final')],
    desc: '复出后的第一个决赛。站在熟悉的舞台上，你想起了 400 天前躺在病床上的自己。',
    options: [
      { id: 'crown-comeback', label: '拿下冠军', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [trophy('S_TIER', 1), trophy('MVP', 1), stat(MORALE, 15), flag('COMEBACK_CROWN', '复出加冕', 'ACHIEVEMENT')], msg: ['你拿下冠军，还有 MVP。', '颁奖时，全场高喊你的 ID。'], next: 'comeback-champion-return' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你拼了，但决赛还是输了。', '不过这一次，你站着输的。'], next: 'comeback-champion-return' } },
      { id: 'team-victory', label: '团队至上', chance: 0.6,
        s: { fx: [trophy('S_TIER', 1), stat(MORALE, 12)], msg: ['你没拿 MVP，但队伍赢了。', '赛后你把奖杯递给新人：下一个是你的。'], next: 'comeback-champion-return' },
        f: { fx: [stat(STRESS, 8)], msg: ['团队至上没能换来胜利。', '但你的表现没有拖后腿。'], next: 'comeback-champion-return' } },
    ],
  },
  {
    id: 'comeback-champion-return', title: '冠军回归', period: 'NORMAL', conds: [done('comeback-final-return')],
    desc: '复出后的第一个冠军到手。媒体把你写成了「体育精神」的代名词。',
    options: [
      { id: 'enjoy-light', label: '享受聚光灯', chance: 0.65,
        s: { fx: [stat(MORALE, 12)], msg: ['你接受了所有采访，讲了 400 天的故事。', '故事讲多了，你开始分不清真实和叙事。'], next: 'comeback-record' },
        f: { fx: [stat(STRESS, 8)], msg: ['聚光灯让你有点晕。', '「英雄叙事」的重压让你疲惫。'], next: 'comeback-record' } },
      { id: 'grounded-celebrate', label: '庆祝但保持清醒', chance: 0.7,
        s: { fx: [stat(MORALE, 10), stat(STRESS, -6)], msg: ['你和队友吃了个饭，没有大肆庆祝。', '你知道，赛季还没结束。'], next: 'comeback-record' },
        f: { fx: [stat(MORALE, -4)], msg: ['太清醒让队友觉得你「扫兴」。', '但你清楚自己在做什么。'], next: 'comeback-record' } },
    ],
  },
  {
    id: 'comeback-record', title: '纪录之夜', period: 'NORMAL', conds: [done('comeback-champion-return')],
    desc: '你在接下来的比赛里打破了「复出选手最长连胜纪录」。官方发来祝贺。',
    options: [
      { id: 'record-honor', label: '接受这份荣誉', chance: 0.65,
        s: { fx: [trophy('EVP', 1), stat(MORALE, 10)], msg: ['你的名字被写进纪录页。', '「复出传奇」开始成为你的标签。'], next: 'comeback-injury-crisis' },
        f: { fx: [stat(STRESS, 6)], msg: ['纪录成了包袱，你开始害怕输。', '连胜的压力比你想象得大。'], next: 'comeback-injury-crisis' } },
      { id: 'shrug-record', label: '不当回事', chance: 0.7,
        s: { fx: [stat(STRESS, -4), stat(MORALE, 6)], msg: ['你说纪录只是数字。', '这份松弛让你的状态更加稳定。'], next: 'comeback-injury-crisis' },
        f: { fx: [stat(MORALE, -4)], msg: ['不当回事被媒体写成「傲慢」。', '你懒得解释。'], next: 'comeback-injury-crisis' } },
    ],
  },
  // ============ 极端事件 ============
  {
    id: 'comeback-injury-crisis', title: '伤病危机', period: 'NORMAL', conds: [done('comeback-record')],
    desc: '训练中你的旧伤再次发作，这次疼得你站不起来。你被直接送进了医院。',
    options: [
      { id: 'full-stop', label: '立即停赛', chance: 0.55,
        s: { fx: [stat(ENERGY, 8), stat(STRESS, -6)], msg: ['你停赛一个月，彻底休息。', '复出后你开始更珍惜身体。'], next: 'comeback-retire-push' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -6)], msg: ['停赛的决定让你痛苦。', '「才刚回来又要走」的念头挥之不去。'], next: 'comeback-retire-push' } },
      { id: 'play-through2', label: '带伤打完赛季', chance: 0.4,
        s: { fx: [stat(MORALE, 8), stat(ENERGY, -10)], msg: ['你带伤撑完了赛季。', '成绩不错，但身体付出了代价。'], next: 'comeback-retire-push' },
        f: { fx: [stat(ENERGY, -14), stat(STRESS, 12)], msg: ['带伤作战让伤情恶化。', '你被迫缺席了更长时间。'], next: 'comeback-retire-push' } },
    ],
  },
  {
    id: 'comeback-retire-push', title: '退役压力', period: 'NORMAL', conds: [done('comeback-injury-crisis')],
    desc: '媒体开始讨论「他是不是该退役了」。连你的家人也委婉地问：要不要考虑退役。',
    options: [
      { id: 'keep-fighting', label: '坚持不退役', chance: 0.55,
        s: { fx: [stat(MORALE, 8), stat(STRESS, 8)], msg: ['你和家人深谈了一次。', '最终，他们支持你继续打。'], next: 'comeback-management-push' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -6)], msg: ['你嘴上说不退，心里开始动摇。', '「打不动了」的念头越来越频繁。'], next: 'comeback-management-push' } },
      { id: 'consider-exit', label: '认真考虑退路', chance: 0.65,
        s: { fx: [stat(STRESS, -6), flag('EXIT_PLAN', '退役预案', 'CAREER')], msg: ['你开始为退役做规划，但决定打完今年。', '有退路之后，反而打得更轻松。'], next: 'comeback-management-push' },
        f: { fx: [stat(STRESS, 8)], msg: ['退路想得太多，状态开始分心。', '你在「打」和「退」之间摇摆。'], next: 'comeback-management-push' } },
    ],
  },
  {
    id: 'comeback-management-push', title: '管理层劝退', period: 'NORMAL', conds: [done('comeback-retire-push')],
    desc: '管理层约你谈话，暗示「你的合同可以协商提前终止」。翻译过来就是：我们想让你走。',
    options: [
      { id: 'prove-value', label: '证明自己还有价值', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 10)], msg: ['你在接下来的比赛里打出了关键表现。', '管理层改口：合同照旧。'], next: 'comeback-media-cruelty' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -8)], msg: ['越想证明越发挥失常。', '管理层看你的眼神更加坚定。'], next: 'comeback-media-cruelty' } },
      { id: 'negotiate-exit', label: '谈个好聚好散', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 3000), stat(MORALE, 6)], msg: ['你谈妥了体面的解约。', '离开那天，老板送你到门口。'], next: 'comeback-media-cruelty' },
        f: { fx: [stat(STRESS, 10)], msg: ['解约谈判不顺利，双方都很难看。', '你带着怨气离开了。'], next: 'comeback-media-cruelty' } },
    ],
  },
  {
    id: 'comeback-media-cruelty', title: '舆论残酷', period: 'NORMAL', conds: [done('comeback-management-push')],
    desc: '一篇长文分析「复出选手的经济账」，结论是：大部分复出不值得。',
    options: [
      { id: 'ignore-analysis', label: '不看这些分析', chance: 0.65,
        s: { fx: [stat(STRESS, -8)], msg: ['你决定不再看这类文章。', '「值不值得」只有你自己能回答。'], next: 'comeback-fan-support' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['你读完了全文，还读了评论区。', '那晚你又失眠了。'], next: 'comeback-fan-support' } },
      { id: 'answer-back', label: '用表现回答', chance: 0.55,
        s: { fx: [attr(AIM, 2), stat(MORALE, 8)], msg: ['你在下一场比赛打出了高分表现。', '那篇文章的评论区开始反转。'], next: 'comeback-fan-support' },
        f: { fx: [stat(STRESS, 12)], msg: ['你想用表现回答，结果发挥更差。', '「果然不值得」的评论成了热评。'], next: 'comeback-fan-support' } },
    ],
  },
  {
    id: 'comeback-fan-support', title: '粉丝支持', period: 'NORMAL', conds: [done('comeback-media-cruelty')],
    desc: '你的粉丝组织了一场线上应援：把你复出以来的每一场比赛做成合集。',
    options: [
      { id: 'feel-warm', label: '收下这份支持', chance: 0.7,
        s: { fx: [stat(MORALE, 12)], msg: ['你看了那个合集，看到一半眼眶热了。', '你回复了一句：谢谢，我会继续。'], next: 'comeback-surgery-choice' },
        f: { fx: [stat(STRESS, 6)], msg: ['感动之外，你也感到了压力。', '「不能让粉丝失望」变成了新的负担。'], next: 'comeback-surgery-choice' } },
      { id: 'meet-fans', label: '办线下见面会', chance: 0.6,
        s: { fx: [stat(MORALE, 10), cstat('CAREER_EARNINGS', 500)], msg: ['见面会来了几百人。', '有个粉丝举的牌子写着：谢谢你没放弃。'], next: 'comeback-surgery-choice' },
        f: { fx: [stat(ENERGY, -6)], msg: ['见面会排场太大，你有点累。', '但被需要的幸福感很真实。'], next: 'comeback-surgery-choice' } },
    ],
  },
  {
    id: 'comeback-surgery-choice', title: '手术抉择', period: 'NORMAL', conds: [done('comeback-fan-support')],
    desc: '医生给出了两个选项：手术根治，但可能再歇半年；保守治疗，但风险会一直跟着。',
    options: [
      { id: 'surgery-root', label: '选择手术', chance: 0.55,
        s: { fx: [stat(ENERGY, -8), flag('SURGERY_CHOSEN', '手术根治', 'CAREER')], msg: ['你进了手术室。', '醒来时，你对自己说：再等一次。'], next: 'comeback-long-rehab' },
        f: { fx: [stat(STRESS, 12)], msg: ['手术前夜你怕了。', '但最终你还是躺上了手术台。'], next: 'comeback-long-rehab' } },
      { id: 'conservative', label: '保守治疗', chance: 0.65,
        s: { fx: [stat(ENERGY, 6)], msg: ['你选择保守治疗，继续打。', '风险在，但生活没有中断。'], next: 'comeback-long-rehab' },
        f: { fx: [stat(STRESS, 10)], msg: ['保守治疗的效果一般。', '你开始后悔没有早做决定。'], next: 'comeback-long-rehab' } },
    ],
  },
  {
    id: 'comeback-long-rehab', title: '漫长复健', period: 'NORMAL', conds: [done('comeback-surgery-choice')],
    desc: '这一次的复健比第一次更长、更枯燥。每天都是理疗、拉伸、等待。',
    options: [
      { id: 'patient-grind', label: '耐心坚持', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), attr(CONSISTENCY, 2)], msg: ['你不再数日子，而是过好每一天。', '复健师说你的心态比上次好多了。'], next: 'comeback-recovery-miracle' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -6)], msg: ['枯燥的复健让你情绪低落。', '你开始怀疑这一切的意义。'], next: 'comeback-recovery-miracle' } },
      { id: 'mental-training', label: '同步练心态', chance: 0.6,
        s: { fx: [stat(STRESS, -8), stat(MORALE, 8)], msg: ['复健期间你看了很多书，练了冥想。', '身体在恢复，心态也在恢复。'], next: 'comeback-recovery-miracle' },
        f: { fx: [stat(ENERGY, -4)], msg: ['心态训练做得断断续续。', '但至少让你没那么焦虑了。'], next: 'comeback-recovery-miracle' } },
    ],
  },
  {
    id: 'comeback-recovery-miracle', title: '奇迹恢复', period: 'NORMAL', conds: [done('comeback-long-rehab')],
    desc: '复查结果让医生都意外：你的恢复速度远超同类手术的常规水平。',
    options: [
      { id: 'believe-miracle', label: '接受这份幸运', chance: 0.65,
        s: { fx: [stat(MORALE, 12), stat(STRESS, -8)], msg: ['你把这份幸运当成了馈赠。', '这一次，你会更小心地使用自己的身体。'], next: 'comeback-scrim-top' },
        f: { fx: [stat(STRESS, 6)], msg: ['奇迹让你不敢高兴，怕乐极生悲。', '你小心翼翼地恢复着。'], next: 'comeback-scrim-top' } },
      { id: 'test-limit3', label: '测试自己的极限', chance: 0.55,
        s: { fx: [attr(AIM, 2), stat(MORALE, 8)], msg: ['你开始试探性训练，状态比预期好。', '「奇迹」开始有了实感。'], next: 'comeback-scrim-top' },
        f: { fx: [stat(ENERGY, -8)], msg: ['试探过头，伤处又开始酸胀。', '你退回来，按部就班。'], next: 'comeback-scrim-top' } },
    ],
  },
  {
    id: 'comeback-scrim-top', title: '顶级训练赛', period: 'NORMAL', conds: [done('comeback-recovery-miracle')],
    desc: '康复后的第一场高强度训练赛，对手是世界排名前列的队伍。',
    options: [
      { id: 'hold-own', label: '稳住不拖后腿', chance: 0.6, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你稳住了，没有成为突破口。', '教练说：可以回来打正式赛了。'], next: 'comeback-coach-faith' },
        f: { fx: [stat(STRESS, 10)], msg: ['顶级强度让你有些跟不上。', '但你知道，这只是时间问题。'], next: 'comeback-coach-faith' } },
      { id: 'flash-old', label: '打出过去的高光', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 12)], msg: ['你打出了几个过去才有的操作。', '训练室里有人喊：他回来了！'], next: 'comeback-coach-faith' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -4)], msg: ['想打高光反而失误连连。', '你提醒自己：别急。'], next: 'comeback-coach-faith' } },
    ],
  },
  {
    id: 'comeback-coach-faith', title: '教练信任', period: 'NORMAL', conds: [done('comeback-scrim-top')],
    desc: '教练把你排进季后赛首发名单。他把这个决定发在了媒体会上。',
    options: [
      { id: 'repay-trust', label: '回报这份信任', chance: 0.6,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 12)], msg: ['你用季后赛的表现回报了他。', '教练说：我的眼光从来没看错过。'], next: 'comeback-comeback-crown' },
        f: { fx: [stat(STRESS, 12)], msg: ['信任变成了压力，你发挥失常。', '有评论开始质疑教练的决定。'], next: 'comeback-comeback-crown' } },
      { id: 'share-faith', label: '把信任转给新人', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['你在训练中帮助新人成长。', '教练说：你让这支队伍更像一支队伍了。'], next: 'comeback-comeback-crown' },
        f: { fx: [stat(MORALE, -4)], msg: ['你的让贤没被理解。', '「老将是不是不行了」的猜测又来了。'], next: 'comeback-comeback-crown' } },
    ],
  },
  {
    id: 'comeback-comeback-crown', title: '复出巅峰', period: 'FINAL_DECISIVE_MOMENT', conds: [done('comeback-coach-faith')],
    desc: '季后赛，你打出了复出以来的巅峰状态。解说开始用「不可思议」来形容你。',
    options: [
      { id: 'peak-forever', label: '打出生涯最佳', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('S_TIER', 1), cstat('TOTAL_KILLS', 45), stat(MORALE, 15)], msg: ['你打出了生涯最佳系列赛。', '这次不是奇迹，是实力。'], next: 'comeback-legacy-match' },
        f: { fx: [stat(STRESS, 10)], msg: ['巅峰状态没能延续到最关键一场。', '但你已经证明了自己还能打。'], next: 'comeback-legacy-match' } },
      { id: 'guide-team', label: '带着队伍赢', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 3), trophy('S_TIER', 1), stat(MORALE, 12)], msg: ['你没有数据上的高光，但每个关键决策都有你。', '教练说：这就是复出的意义。'], next: 'comeback-legacy-match' },
        f: { fx: [stat(STRESS, 8)], msg: ['你的决策没能换来胜利。', '但队伍还是走了很远。'], next: 'comeback-legacy-match' } },
    ],
  },
  {
    id: 'comeback-legacy-match', title: '生涯之战', period: 'NORMAL', conds: [done('comeback-comeback-crown')],
    desc: '这场比赛的录像，未来一定会被反复播放。你职业生涯的所有篇章都在这里交汇。',
    options: [
      { id: 'complete-story', label: '为故事画上句点', chance: 0.6, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('MAJOR', 1), stat(MORALE, 15), flag('LEGACY_COMPLETE', '生涯圆满', 'ACHIEVEMENT')], msg: ['你赢了，故事圆满。', '从伤病到冠军，你走完了最远的路。'], next: 'comeback-final-goodbye' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你输了，但打得很精彩。', '「虽败犹荣」这四个字，这次是真的。'], next: 'comeback-final-goodbye' } },
      { id: 'pass-torch', label: '把火炬传给新人', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 3), stat(MORALE, 12)], msg: ['你在关键局把资源让给了新人。', '他打出了生涯代表作。'], next: 'comeback-final-goodbye' },
        f: { fx: [stat(STRESS, 8)], msg: ['让资源给新人，他没能接住。', '但你仍然为自己骄傲。'], next: 'comeback-final-goodbye' } },
    ],
  },
  // ============ 世界线转换 ============
  {
    id: 'comeback-grinder-fall', title: '复出失败', period: 'NORMAL', conds: [done('comeback-legacy-match')],
    desc: '复查结果不理想：医生建议你考虑彻底放弃高强度比赛。你第一次认真面对这个选项。',
    options: [
      { id: 'accept-fall', label: '接受现实去低级别', chance: 0.6,
        s: { fx: [wl('grinder'), stat(MORALE, 8), flag('CROSSED_TO_GRINDER', '转入磨砺线', 'CUSTOM')], msg: ['你去了低级别联赛，以另一种方式继续。', '故事没有结束，只是换了舞台。'], next: null },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你无法接受复出失败。', '「真的到此为止了吗」反复折磨你。'], next: 'comeback-prodigy-phoenix' } },
      { id: 'keep-top', label: '继续留在顶级', chance: 0.55,
        s: { fx: [stat(MORALE, 6)], msg: ['你选择留在顶级联赛，即使只能当替补。', '只要还在这个舞台上，就有机会。'], next: 'comeback-prodigy-phoenix' },
        f: { fx: [stat(STRESS, 10)], msg: ['留在顶级却上不了场，更煎熬。', '你开始怀疑自己的坚持。'], next: 'comeback-prodigy-phoenix' } },
    ],
  },
  {
    id: 'comeback-prodigy-phoenix', title: '涅槃重生', period: 'NORMAL', conds: [done('comeback-legacy-match')],
    desc: '一位战术大师看完你的复出录像说：「你的经历成了你的武器，你不是老兵，你是凤凰。」',
    options: [
      { id: 'rise-again', label: '接受这个新定位', chance: 0.65,
        s: { fx: [wl('prodigy'), stat(MORALE, 14), flag('CROSSED_TO_PRODIGY', '转入天才线', 'CUSTOM')], msg: ['你决定用这份经验重新定义自己。', '凤凰浴火，故事翻篇。'], next: null },
        f: { fx: [stat(STRESS, 8)], msg: ['「凤凰」的头衔让你觉得太沉重。', '你把它当成过誉。'], next: 'comeback-fix-desperation' } },
      { id: 'stay-humble3', label: '不接受神话', chance: 0.7,
        s: { fx: [stat(MORALE, 6)], msg: ['你说自己只是个想打球的老人。', '这份清醒让你在场上更稳。'], next: 'comeback-fix-desperation' },
        f: { fx: [stat(MORALE, -4)], msg: ['太谦逊让你错失了一次品牌合作。', '经纪人替你可惜。'], next: 'comeback-fix-desperation' } },
    ],
  },
  {
    id: 'comeback-fix-desperation', title: '绝望诱惑', period: 'NORMAL', conds: [done('comeback-legacy-match')],
    desc: '复出前景不明，经济压力又大。有人递来一个「能保证你打完全程」的邀请。',
    options: [
      { id: 'refuse-fix2', label: '拒绝', chance: 0.75,
        s: { fx: [stat(MORALE, 10), flag('REFUSED_FIX', '拒绝假赛', 'ACHIEVEMENT')], msg: ['你听懂了对方的暗示，直接拒绝。', '你爬过那么长的路，不能在这里跌倒。'], next: 'comeback-z-rehab-day' },
        f: { fx: [stat(STRESS, 10)], msg: ['你拒绝得有些犹豫。', '对方记住了你的犹豫。'], next: 'comeback-z-rehab-day' } },
      { id: 'tempted', label: '动摇了', chance: 0.4,
        s: { fx: [wl('matchfixing'), stat(MORALE, -8), stat(STRESS, 14)], msg: ['你动摇了，第一次没有立刻拒绝。', '这个夜晚，你注定睡不着。'], next: null },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你最终拒绝了，但心里留下了一道裂痕。', '你花了很久才把它填上。'], next: 'comeback-z-rehab-day' } },
    ],
  },
  // ============ 尾声 ============
  {
    id: 'comeback-final-goodbye', title: '最后告别', period: 'NORMAL', conds: [done('comeback-legacy-match')],
    desc: '无论结局如何，你知道这是最后一段路了。你开始认真地和每一个熟悉的地方告别。',
    options: [
      { id: 'thank-everyone', label: '感谢所有人', chance: 0.7,
        s: { fx: [stat(MORALE, 10)], msg: ['你请全队吃了顿饭，说了很多感谢。', '「能遇见你们，是我的运气。」'], next: 'comeback-hall-call' },
        f: { fx: [stat(STRESS, 6)], msg: ['感谢的话说不出口，你只是沉默地敬酒。', '但大家都懂。'], next: 'comeback-hall-call' } },
      { id: 'write-letter', label: '给未来的自己写信', chance: 0.65,
        s: { fx: [stat(MORALE, 12)], msg: ['你写了一封给五年后的自己的信。', '信里只写了一句话：别后悔。'], next: 'comeback-hall-call' },
        f: { fx: [stat(MORALE, -4)], msg: ['信写到一半写不下去了。', '你把它收进了抽屉。'], next: 'comeback-hall-call' } },
    ],
  },
  {
    id: 'comeback-hall-call', title: '荣誉邀请', period: 'NORMAL', conds: [done('comeback-final-goodbye')],
    desc: '你收到一封邀请：行业颁奖礼的「年度复出人物」提名。',
    options: [
      { id: 'attend-award', label: '出席领奖', chance: 0.7,
        s: { fx: [trophy('EVP', 1), stat(MORALE, 12)], msg: ['你站在领奖台上，台下掌声雷动。', '你的故事，成了许多人的故事。'], next: 'comeback-z-stretching' },
        f: { fx: [stat(STRESS, 6)], msg: ['上台前你紧张到手心出汗。', '但说出口的话，比想象中平静。'], next: 'comeback-z-stretching' } },
      { id: 'decline-award', label: '婉拒提名', chance: 0.6,
        s: { fx: [stat(MORALE, 8)], msg: ['你谢绝了提名。', '「我复出不是为了奖项。」'], next: 'comeback-z-stretching' },
        f: { fx: [stat(MORALE, -4)], msg: ['婉拒后你有点遗憾。', '但你知道自己为什么坚持到现在。'], next: 'comeback-z-stretching' } },
    ],
  },
  // ============ 风味日常（可重复） ============
  {
    id: 'comeback-z-stretching', title: '拉伸课', period: 'NORMAL', conds: [], repeatable: true,
    desc: '复出后的必修课：每天两小时的拉伸和核心训练，比比赛还枯燥。',
    options: [
      { id: 'do-stretch', label: '认真完成', chance: 0.7,
        s: { fx: [stat(ENERGY, 6), stat(STRESS, -3)], msg: ['拉伸做得一丝不苟。', '身体反馈很好。'], next: 'comeback-z-film-day' },
        f: { fx: [stat(ENERGY, -3)], msg: ['拉伸草草了事。', '你下午的腰有点紧。'], next: 'comeback-z-film-day' } },
      { id: 'meditate', label: '加练冥想', chance: 0.6,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 4)], msg: ['你在拉伸后加了十分钟冥想。', '心静了不少。'], next: 'comeback-z-film-day' },
        f: { fx: [stat(ENERGY, -3)], msg: ['冥想时你满脑子都是比赛。', '但至少身体放松了。'], next: 'comeback-z-film-day' } },
    ],
  },
  {
    id: 'comeback-z-film-day', title: '录像日', period: 'NORMAL', conds: [], repeatable: true,
    desc: '今天的任务是复盘自己受伤前和复出后的比赛录像，对比差距。',
    options: [
      { id: 'compare-film', label: '认真对比', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 1), stat(MORALE, 4)], msg: ['对比让你看到了自己的成长。', '有些旧习惯，你真的改掉了。'], next: 'comeback-z-rehab-day' },
        f: { fx: [stat(MORALE, -4)], msg: ['对比太扎心，你看了半小时就关了。', '「过去的我更强」的念头又来了。'], next: 'comeback-z-rehab-day' } },
      { id: 'study-opponents', label: '研究对手录像', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2)], msg: ['你研究了一下午对手的习惯。', '这些笔记会在比赛里用上。'], next: 'comeback-z-rehab-day' },
        f: { fx: [stat(ENERGY, -4)], msg: ['录像看多了，眼睛发酸。', '你揉了揉眼，继续看。'], next: 'comeback-z-rehab-day' } },
    ],
  },
  {
    id: 'comeback-z-rehab-day', title: '复健日常', period: 'NORMAL', conds: [], repeatable: true,
    desc: '复健的日子还在继续。理疗师说你的情况「稳定向好」。',
    options: [
      { id: 'steady-progress', label: '按计划复健', chance: 0.7,
        s: { fx: [stat(ENERGY, 6)], msg: ['复健进度一切正常。', '你学会了和身体做朋友。'], next: 'comeback-z-training-day' },
        f: { fx: [stat(STRESS, 4)], msg: ['复健时你分了心，动作没做到位。', '理疗师纠正了你。'], next: 'comeback-z-training-day' } },
      { id: 'ask-details2', label: '多问医生细节', chance: 0.65,
        s: { fx: [stat(STRESS, -4)], msg: ['你问了医生很多细节，心里更有底了。', '「理解」是恐惧的解药。'], next: 'comeback-z-training-day' },
        f: { fx: [stat(STRESS, 4)], msg: ['细节问得越多越焦虑。', '你决定少想一点。'], next: 'comeback-z-training-day' } },
    ],
  },
  {
    id: 'comeback-z-training-day', title: '训练日常', period: 'NORMAL', conds: [], repeatable: true,
    desc: '复出后的训练日：热手、训练赛、专项、拉伸。节奏比过去慢，但更稳。',
    options: [
      { id: 'quality-day', label: '高质量完成', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 1), stat(MORALE, 4)], msg: ['今天的训练很扎实。', '「慢一点」反而让你更强。'], next: 'comeback-z-stretching' },
        f: { fx: [stat(ENERGY, -4)], msg: ['训练时身体有些沉。', '你决定明天调整。'], next: 'comeback-z-stretching' } },
      { id: 'old-school', label: '加练老项目', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.005 }],
        s: { fx: [attr(AIM, 1), stat(MORALE, 6)], msg: ['你练了当年最擅长的项目。', '手感回来了不少。'], next: 'comeback-z-stretching' },
        f: { fx: [stat(ENERGY, -6)], msg: ['老项目对现在的身体负担不小。', '你适可而止了。'], next: 'comeback-z-stretching' } },
    ],
  },
];
