/**
 * grinder 世界线内容（磨砺线）。
 * 入口为既有 grinder-faceit-grind → grinder-parttime-dilemma；本文件内容 gated 在 done(parttime) 之后。
 */
import {
  attr, stat, flag, rmFlag, wl, transfer, role, trophy, cstat,
  done, hasFlag, age, statCond, attrCond, ANY, ALL, NONE,
  MORALE, ENERGY, BALANCE, STRESS, RATING2,
  AIM, GAME_SENSE, LEADERSHIP, CLUTCH, CONSISTENCY, TEAM_CONFLICT,
} from './helpers.js';

const GATE = done('grinder-parttime-dilemma');

export default [
  // ============ 主线：全职训练 ============
  {
    id: 'grinder-bootcamp', title: '集训营', period: 'NORMAL', conds: [GATE],
    desc: '你决定辞掉白天的工作，专心投入训练。集训营报到那天，你只剩三个月的积蓄。',
    options: [
      { id: 'full-commit', label: '全身心投入', chance: 0.65, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 10), flag('FULL_TIME_PLAYER', '全职选手', 'CAREER')], msg: ['没有退路的训练格外有效。', '一个月后你的枪法有了质的提升。'], next: 'grinder-half-day' },
        f: { fx: [stat(STRESS, 12)], msg: ['积蓄见底的速度比你想象得快。', '训练时你总在算钱。'], next: 'grinder-half-day' } },
      { id: 'part-time-plan', label: '保留兼职', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 600), stat(STRESS, -4)], msg: ['你保留了一份灵活的兼职。', '钱够花，但训练时间被切碎。'], next: 'grinder-half-day' },
        f: { fx: [stat(ENERGY, -8), stat(STRESS, 8)], msg: ['兼职和训练两头烧，你两头都没做好。', '你开始怀疑这个选择。'], next: 'grinder-half-day' } },
    ],
  },
  {
    id: 'grinder-half-day', title: '半天班', period: 'NORMAL', conds: [done('grinder-bootcamp')],
    desc: '你的训练计划排满了白天，但房租不会等人。你找了份下午到晚上的便利店班。',
    options: [
      { id: 'night-shift', label: '上夜班保训练', chance: 0.55,
        s: { fx: [cstat('CAREER_EARNINGS', 400), stat(ENERGY, -6)], msg: ['白天训练，晚上收银。', '虽然累，但训练时间保住了。'], next: 'grinder-lower-league' },
        f: { fx: [stat(ENERGY, -14), stat(STRESS, 10)], msg: ['夜班让你的生物钟彻底乱了。', '训练赛里你困得看不清准星。'], next: 'grinder-lower-league' } },
      { id: 'share-rent', label: '找人合租省钱', chance: 0.6,
        s: { fx: [stat(ENERGY, 6), cstat('CAREER_EARNINGS', -200)], msg: ['你搬进了四人合租的公寓。', '省下的钱换来了训练时间。'], next: 'grinder-lower-league' },
        f: { fx: [stat(STRESS, 8)], msg: ['合租室友打呼噜，你睡眠质量堪忧。', '省了钱，赔了状态。'], next: 'grinder-lower-league' } },
    ],
  },
  {
    id: 'grinder-lower-league', title: '低级别联赛', period: 'NORMAL', conds: [done('grinder-half-day')],
    desc: '你加入了一支低级别联赛的队伍。比赛在周末下午，观众席坐不满两排。',
    options: [
      { id: 'dominate', label: '打出身价', chance: 0.6, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('MAPS_PLAYED', 1), cstat('TOTAL_KILLS', 40), stat(MORALE, 8)], msg: ['你在低级联赛里确实显得高人一等。', '但你知道，这只是开始。'], next: 'grinder-teammates-rough' },
        f: { fx: [stat(STRESS, 8)], msg: ['你高估了自己，第一场打得平庸。', '对手虽然弱，但也没有任你宰割。'], next: 'grinder-teammates-rough' } },
      { id: 'learn-base', label: '练基本功', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 2), attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你把这当成练基本功的机会。', '低级联赛的比赛强度正好适合打磨细节。'], next: 'grinder-teammates-rough' },
        f: { fx: [stat(MORALE, -4)], msg: ['你想练的没练成，比赛也输了。', '低级别联赛没那么好混。'], next: 'grinder-teammates-rough' } },
    ],
  },
  {
    id: 'grinder-teammates-rough', title: '粗糙队友', period: 'NORMAL', conds: [done('grinder-lower-league')],
    desc: '队友的水平参差不齐：有的大爷式报点，有的打着打着切出去回消息。',
    options: [
      { id: 'lead-by-calls', label: '自己扛起指挥', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.008 }],
        s: { fx: [attr(LEADERSHIP, 3), stat(MORALE, 6)], msg: ['你开始接管报点和节奏。', '队伍还是糙，但至少有序了。'], next: 'grinder-coach-amateur' },
        f: { fx: [stat(STRESS, 10), stat(TEAM_CONFLICT, 3)], msg: ['你的指挥没人听，比赛乱成一锅粥。', '你第一次体验到带不动。'], next: 'grinder-coach-amateur' } },
      { id: 'adapt-down', label: '降低期待适应他们', chance: 0.7,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 4)], msg: ['你学会了自己兜底。', '一个人补三个人的漏洞，练出了多线意识。'], next: 'grinder-coach-amateur' },
        f: { fx: [stat(MORALE, -6)], msg: ['降低期待变成了摆烂。', '你的状态被拖下去了。'], next: 'grinder-coach-amateur' } },
    ],
  },
  {
    id: 'grinder-coach-amateur', title: '业余教练', period: 'NORMAL', conds: [done('grinder-teammates-rough')],
    desc: '你们的教练本职是出租车司机，战术板是他在纸上画的箭头。',
    options: [
      { id: 'work-with-him', label: '配合他的战术', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['他的箭头虽然糙，但有些思路意外地实用。', '你开始认真研究这套「出租车战术」。'], next: 'grinder-scrim-money' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['你在会上指出了战术的问题。', '教练面子挂不住，战术执行变味了。'], next: 'grinder-scrim-money' } },
      { id: 'self-study', label: '自己研究录像', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 3), stat(ENERGY, -4)], msg: ['你自费买了战术书，自己研究录像。', '你的理解开始超过教练。'], next: 'grinder-scrim-money' },
        f: { fx: [stat(ENERGY, -8)], msg: ['自学太散，你研究了一周没成体系。', '但至少你知道了职业选手在做什么。'], next: 'grinder-scrim-money' } },
    ],
  },
  {
    id: 'grinder-scrim-money', title: '训练赛奖金', period: 'NORMAL', conds: [done('grinder-coach-amateur')],
    desc: '一个赞助商办了低级别训练赛，冠军有 500 块奖金。全队眼睛都亮了。',
    options: [
      { id: 'win-it', label: '全力争冠', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.007 }],
        s: { fx: [cstat('CAREER_EARNINGS', 500), stat(MORALE, 10)], msg: ['你们赢了，500 块到手。', '这点钱不多，但它是你的第一笔比赛奖金。'], next: 'grinder-family-pressure' },
        f: { fx: [stat(STRESS, 8)], msg: ['决赛你们输给了更强的队伍。', '500 块没拿到，但你知道差距在哪。'], next: 'grinder-family-pressure' } },
      { id: 'treat-team', label: '保底参赛，重在参与', chance: 0.7,
        s: { fx: [stat(MORALE, 4), stat(TEAM_CONFLICT, -2)], msg: ['你们抱着玩的心态打完了。', '虽然没赢，但队伍气氛好了。'], next: 'grinder-family-pressure' },
        f: { fx: [stat(MORALE, -4)], msg: ['玩的心态让队伍输得很散。', '有人开始认真，有人还在玩。'], next: 'grinder-family-pressure' } },
    ],
  },
  {
    id: 'grinder-family-pressure', title: '家庭压力', period: 'NORMAL', conds: [done('grinder-scrim-money')],
    desc: '妈妈打电话来，问你「游戏打得怎么样了」。你听得出她语气里的担忧。',
    options: [
      { id: 'honest-report', label: '如实相告', chance: 0.6,
        s: { fx: [stat(MORALE, 8), stat(STRESS, -4)], msg: ['你说了实话：还在打，没收入。', '妈妈沉默了很久，最后说：注意身体。'], next: 'grinder-roommate-money' },
        f: { fx: [stat(STRESS, 10)], msg: ['说实话让你心里发堵。', '挂了电话你盯着屏幕发了很久的呆。'], next: 'grinder-roommate-money' } },
      { id: 'white-lie', label: '报喜不报忧', chance: 0.65,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 4)], msg: ['你说比赛快有眉目了。', '谎话说出口，压力却更大了。'], next: 'grinder-roommate-money' },
        f: { fx: [stat(STRESS, 8)], msg: ['谎话被妈妈识破了。', '她说：你要是实在撑不住，就回来。'], next: 'grinder-roommate-money' } },
    ],
  },
  {
    id: 'grinder-roommate-money', title: '房租分摊', period: 'NORMAL', conds: [done('grinder-family-pressure')],
    desc: '合租室友要搬走了。剩下的房租对你来说是笔不小的数字。',
    options: [
      { id: 'find-sublet', label: '找新室友', chance: 0.55,
        s: { fx: [stat(STRESS, -6), cstat('CAREER_EARNINGS', -100)], msg: ['新室友也是个打游戏的，作息很搭。', '他甚至偶尔陪你对练。'], next: 'grinder-partner-support' },
        f: { fx: [stat(STRESS, 12)], msg: ['新室友打呼噜更响，而且爱半夜开麦。', '你的睡眠彻底报废。'], next: 'grinder-partner-support' } },
      { id: 'move-cheaper', label: '搬到更便宜的地方', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -300), stat(ENERGY, 4)], msg: ['你搬进了一个小单间。', '地方小，但安静，网也好。'], next: 'grinder-partner-support' },
        f: { fx: [stat(ENERGY, -8), stat(STRESS, 8)], msg: ['新地方网络不稳，训练赛掉线两次。', '你开始怀疑省这钱值不值。'], next: 'grinder-partner-support' } },
    ],
  },
  {
    id: 'grinder-partner-support', title: '伴侣支持', period: 'NORMAL', conds: [done('grinder-roommate-money')],
    desc: '对象说想认真聊聊你的职业规划。你怕她劝你放弃，又怕她真的放弃。',
    options: [
      { id: 'share-plan', label: '坦诚讲计划', chance: 0.6,
        s: { fx: [stat(MORALE, 12), flag('PARTNER_BACKING', '有人撑腰', 'CAREER')], msg: ['你把时间表、收入预期全摊开讲了。', '她说：那就再试一年。'], next: 'grinder-borrowed-pc' },
        f: { fx: [stat(STRESS, 10)], msg: ['她没反对，但你听出她在忍。', '这份支持让你更不敢输。'], next: 'grinder-borrowed-pc' } },
      { id: 'downplay', label: '轻描淡写', chance: 0.7,
        s: { fx: [stat(STRESS, -4)], msg: ['你说就是随便打打。', '话题被绕开了，但隔阂也多了一点。'], next: 'grinder-borrowed-pc' },
        f: { fx: [stat(MORALE, -6)], msg: ['她察觉到了你的回避。', '你俩第一次为这件事沉默了很久。'], next: 'grinder-borrowed-pc' } },
    ],
  },
  {
    id: 'grinder-borrowed-pc', title: '借来的电脑', period: 'NORMAL', conds: [done('grinder-partner-support')],
    desc: '你的旧电脑带不动新版本了。队里有人借你一台配置更高的机器，条件是帮他们带分。',
    options: [
      { id: 'accept-loan', label: '接受借用', chance: 0.65,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['新电脑的帧数让你的枪法都顺了。', '你也兑现承诺，帮他们打上了分。'], next: 'grinder-internet-cafe' },
        f: { fx: [stat(STRESS, 8)], msg: ['带分任务挤占了你的训练时间。', '你开始重新算这笔账。'], next: 'grinder-internet-cafe' } },
      { id: 'save-up', label: '攒钱自己买', chance: 0.55,
        s: { fx: [cstat('CAREER_EARNINGS', -800), stat(MORALE, 8), stat(STRESS, -4)], msg: ['你省吃俭用三个月，买下了自己的机器。', '自己的电脑，练起来踏实。'], next: 'grinder-internet-cafe' },
        f: { fx: [stat(STRESS, 10)], msg: ['攒钱计划被一次意外开销打乱。', '旧电脑又卡又烫，你只能咬牙用。'], next: 'grinder-internet-cafe' } },
    ],
  },
  {
    id: 'grinder-internet-cafe', title: '网吧岁月', period: 'NORMAL', conds: [done('grinder-borrowed-pc')],
    desc: '电脑坏了的那一周，你回到网吧训练。旁边打英雄联盟的小孩一直在喊。',
    options: [
      { id: 'noise-proof', label: '练抗干扰', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 4)], msg: ['你在最吵的角落练了一周。', '回到主场后，你发现什么噪音都不怕了。'], next: 'grinder-faceit-streak' },
        f: { fx: [stat(STRESS, 8)], msg: ['噪音让你频繁失误。', '你花更多钱订了包间。'], next: 'grinder-faceit-streak' } },
      { id: 'cafe-community', label: '认识网吧战队', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 2), flag('CAFE_CREW', '网吧兄弟', 'CAREER')], msg: ['网吧里有支本地队伍，水平不错。', '他们邀请你周末一起打线下赛。'], next: 'grinder-faceit-streak' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['网吧战队的打法和你合不来。', '但至少多了几个能约训练的人。'], next: 'grinder-faceit-streak' } },
    ],
  },
  {
    id: 'grinder-faceit-streak', title: '平台连胜', period: 'NORMAL', conds: [done('grinder-internet-cafe')],
    desc: '你在高分段打出了一波连胜。数据网站把你的评级标成了「值得关注」。',
    options: [
      { id: 'ride-streak', label: '趁热冲分', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 8)], msg: ['连胜让你冲进了更高的分段。', '匹配到职业选手的频率变高了。'], next: 'grinder-rank-ladder' },
        f: { fx: [stat(STRESS, 8), stat(ENERGY, -6)], msg: ['你连打太久，连胜被终结在一场熬夜局。', '你为自己的上头付出了代价。'], next: 'grinder-rank-ladder' } },
      { id: 'record-games', label: '录像保存研究', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 4)], msg: ['你把连胜的录像存了下来。', '这些录像后来成了你的分析素材。'], next: 'grinder-rank-ladder' },
        f: { fx: [stat(ENERGY, -4)], msg: ['录像存了但没整理。', '文件夹里躺着几十个没看的文件。'], next: 'grinder-rank-ladder' } },
    ],
  },
  {
    id: 'grinder-rank-ladder', title: '天梯卡段', period: 'NORMAL', conds: [done('grinder-faceit-streak')],
    desc: '你的段位卡在了一个瓶颈：再往上是对枪怪物，往下的对手已经没压力。',
    options: [
      { id: 'analyze-gaps', label: '针对短板特训', chance: 0.55, mods: [{ attribute: GAME_SENSE, perPoint: 0.008 }],
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 6)], msg: ['你发现自己总在残局信息差上吃亏。', '针对性训练两周后，段位开始松动。'], next: 'grinder-losing-tilt' },
        f: { fx: [stat(STRESS, 8)], msg: ['你知道短板在哪，但改起来太难。', '瓶颈期磨掉了你不少耐心。'], next: 'grinder-losing-tilt' } },
      { id: 'duo-queue', label: '找稳定队友双排', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 6)], msg: ['你拉了个打法互补的队友。', '配合比单排好打多了。'], next: 'grinder-losing-tilt' },
        f: { fx: [stat(TEAM_CONFLICT, 3), stat(STRESS, 6)], msg: ['队友脾气差，输了就互相甩锅。', '双排变成了内耗。'], next: 'grinder-losing-tilt' } },
    ],
  },
  {
    id: 'grinder-losing-tilt', title: '上头连败', period: 'NORMAL', conds: [done('grinder-rank-ladder')],
    desc: '一次判负让你心态炸了，你连开十把，全输。天亮时你的胜率掉了一截。',
    options: [
      { id: 'stop-losing', label: '立刻下线冷静', chance: 0.6,
        s: { fx: [stat(STRESS, -10), stat(MORALE, 4)], msg: ['你强迫自己关掉游戏去睡了觉。', '第二天你状态恢复，把分打了回来。'], next: 'grinder-clutch-underdog' },
        f: { fx: [stat(STRESS, 10)], msg: ['你下线了，但满脑子都是那几把。', '你花了两天才缓过来。'], next: 'grinder-clutch-underdog' } },
      { id: 'grind-back', label: '今晚就打回来', chance: 0.45, mods: [{ attribute: CLUTCH, perPoint: 0.007 }],
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 6), stat(ENERGY, -8)], msg: ['你硬生生把胜率打回来了。', '虽然累，但那股劲头让你自己也惊讶。'], next: 'grinder-clutch-underdog' },
        f: { fx: [stat(STRESS, 14), stat(ENERGY, -12)], msg: ['越打越急，你输光了上分周期。', '你的状态和心态双双触底。'], next: 'grinder-clutch-underdog' } },
    ],
  },
  {
    id: 'grinder-clutch-underdog', title: '逆风残局', period: 'NORMAL', conds: [done('grinder-losing-tilt')],
    desc: '平台赛事里你们 0:2 落后，第三局 14:15，你一个人守最后两秒。',
    options: [
      { id: 'hold-angle', label: '架住最后角度', chance: 0.55, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), cstat('CLUTCH_WON', 1), stat(MORALE, 10)], msg: ['你卡着最后 0.5 秒完成击杀。', '这一枪让直播间里多了几个订阅。'], next: 'grinder-scout-attention' },
        f: { fx: [stat(STRESS, 10)], msg: ['最后两秒你手滑了。', '输了，但你的表现被人记住了。'], next: 'grinder-scout-attention' } },
      { id: 'peak-rush', label: '主动出击拼枪', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('CLUTCH_WON', 1), stat(MORALE, 10)], msg: ['你主动拉出去拼枪，赢了。', '解说喊了一句：这就是路人王的胆量。'], next: 'grinder-scout-attention' },
        f: { fx: [stat(STRESS, 12)], msg: ['主动出击变成了白给。', '弹幕都在刷「经典路人」。'], next: 'grinder-scout-attention' } },
    ],
  },
  {
    id: 'grinder-scout-attention', title: '球探注意', period: 'NORMAL', conds: [done('grinder-clutch-underdog')],
    desc: '你的平台数据被一家次级联赛队伍注意到了。他们发来邮件：有兴趣来试训吗？',
    options: [
      { id: 'accept-tryout', label: '接受试训邀请', chance: 0.6,
        s: { fx: [stat(MORALE, 10), flag('SCOUTED', '被球探发现', 'CAREER')], msg: ['你买了车票去试训。', '试训棚里全是和你一样的追梦人。'], next: 'grinder-offer-tier2' },
        f: { fx: [stat(STRESS, 8)], msg: ['你答应了，但请不了假。', '你只能把试训排到周末。'], next: 'grinder-offer-tier2' } },
      { id: 'stay-focus', label: '先专注平台赛', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你想再攒点资本再试训。', '这个决定让你多打了两个月的低级别比赛。'], next: 'grinder-offer-tier2' },
        f: { fx: [stat(MORALE, -4)], msg: ['你拒绝了试训，机会溜走。', '你安慰自己：还会有下次。'], next: 'grinder-offer-tier2' } },
    ],
  },
  {
    id: 'grinder-offer-tier2', title: '次级报价', period: 'NORMAL', conds: [done('grinder-scout-attention')],
    desc: '次级联赛队伍开了合同：月薪 2000，包吃住，训练基地在一栋老居民楼里。',
    options: [
      { id: 'sign-humble', label: '签下合同', chance: 0.7,
        s: { fx: [cstat('CAREER_EARNINGS', 2000), stat(MORALE, 12), flag('PRO_TIER2', '次级职业选手', 'ACHIEVEMENT')], msg: ['2000 块不多，但它是职业合同。', '你搬进老居民楼的那天，拍了张照发给家人。'], next: 'grinder-contract-risky' },
        f: { fx: [stat(STRESS, 8)], msg: ['签合同前你看了三遍条款。', '字越看越紧，但你还是签了。'], next: 'grinder-contract-risky' } },
      { id: 'negotiate-more', label: '再谈待遇', chance: 0.5,
        s: { fx: [cstat('CAREER_EARNINGS', 2600), stat(MORALE, 8)], msg: ['你提了伙食和训练时间的要求。', '对方居然都答应了。'], next: 'grinder-contract-risky' },
        f: { fx: [stat(STRESS, 10)], msg: ['谈待遇差点谈崩。', '对方说你「还没到挑条件的资格」。'], next: 'grinder-contract-risky' } },
    ],
  },
  {
    id: 'grinder-contract-risky', title: '合同风险', period: 'NORMAL', conds: [done('grinder-offer-tier2')],
    desc: '合同里有一条：违约要赔三倍月薪，且不得在一年内加入同级队伍。',
    options: [
      { id: 'lawyer-check', label: '花钱找律师看', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -300), stat(STRESS, -8)], msg: ['律师挑出了两个坑。', '你拿着修改意见重新谈了谈。'], next: 'grinder-first-salary' },
        f: { fx: [cstat('CAREER_EARNINGS', -300), stat(STRESS, 4)], msg: ['律师费花了，但对方拒绝修改条款。', '你只能先签了。'], next: 'grinder-first-salary' } },
      { id: 'sign-blind', label: '直接签', chance: 0.7,
        s: { fx: [cstat('CAREER_EARNINGS', 2000), stat(MORALE, 8)], msg: ['你签了，没细看。', '职业第一课：合同要逐字读。'], next: 'grinder-first-salary' },
        f: { fx: [stat(STRESS, 10)], msg: ['签完你心里发毛。', '你把合同拍照存了三个地方。'], next: 'grinder-first-salary' } },
    ],
  },
  {
    id: 'grinder-first-salary', title: '第一笔工资', period: 'NORMAL', conds: [done('grinder-contract-risky')],
    desc: '月底，2000 块到账。你盯着短信看了很久，这是你打职业以来的第一笔固定收入。',
    options: [
      { id: 'send-home', label: '给家里寄一部分', chance: 0.65,
        s: { fx: [stat(MORALE, 12), cstat('CAREER_EARNINGS', -500)], msg: ['你给妈妈转了 500。', '她没说什么，但你听得出她高兴。'], next: 'grinder-gift-parents' },
        f: { fx: [stat(STRESS, 4)], msg: ['转账后你的余额只剩三位数。', '但心里的石头放下了一块。'], next: 'grinder-gift-parents' } },
      { id: 'save-all', label: '全部存起来', chance: 0.7,
        s: { fx: [stat(STRESS, -6), cstat('CAREER_EARNINGS', 2000)], msg: ['你把钱存进了定期。', '看着数字上涨，你有了安全感。'], next: 'grinder-gift-parents' },
        f: { fx: [stat(MORALE, -4)], msg: ['存钱存出了抠门的名声。', '队友聚餐你总找理由推掉。'], next: 'grinder-gift-parents' } },
    ],
  },
  {
    id: 'grinder-gift-parents', title: '给父母买礼物', period: 'NORMAL', conds: [done('grinder-first-salary')],
    desc: '你给爸妈各买了一双鞋。他们嘴上说浪费，试穿的时候脚却一直没放下来。',
    options: [
      { id: 'modest-gift', label: '买实用的', chance: 0.7,
        s: { fx: [stat(MORALE, 8), cstat('CAREER_EARNINGS', -400)], msg: ['鞋很合脚，妈妈穿去跳广场舞都在炫耀。', '你第一次觉得挣钱有意义。'], next: 'grinder-coach-trust' },
        f: { fx: [stat(MORALE, -4)], msg: ['买小了半码，你妈说不碍事。', '但你知道那鞋她没法穿。'], next: 'grinder-coach-trust' } },
      { id: 'surprise-big', label: '买贵一点的', chance: 0.55,
        s: { fx: [stat(MORALE, 10), cstat('CAREER_EARNINGS', -800)], msg: ['你买了个按摩椅，爸爸嘴上说浪费，晚上偷偷用。', '这事成了全家饭桌上的笑料。'], next: 'grinder-coach-trust' },
        f: { fx: [stat(STRESS, 6), cstat('CAREER_EARNINGS', -800)], msg: ['按摩椅占了半个客厅，妈妈让你退掉。', '最后你把它搬到了自己房间。'], next: 'grinder-coach-trust' } },
    ],
  },
  {
    id: 'grinder-coach-trust', title: '教练信任', period: 'NORMAL', conds: [done('grinder-gift-parents')],
    desc: '新教练上任后重新定首发。他把你叫进办公室，问你想不想当队长。',
    options: [
      { id: 'take-armband', label: '接下队长', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), role('IGL'), stat(MORALE, 10)], msg: ['你戴上了队长袖标。', '责任比想象中沉，但你接住了。'], next: 'grinder-team-schedule' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['队长责任压垮了你的状态。', '你打了半赛季就主动交回了袖标。'], next: 'grinder-team-schedule' } },
      { id: 'pass-it', label: '推给老队员', chance: 0.7,
        s: { fx: [stat(TEAM_CONFLICT, -2), stat(MORALE, 6)], msg: ['你把队长让给了经验更足的人。', '他干得不错，你也乐得专注比赛。'], next: 'grinder-team-schedule' },
        f: { fx: [stat(MORALE, -5)], msg: ['推让让教练觉得你没担当。', '你的首发位置开始微妙起来。'], next: 'grinder-team-schedule' } },
    ],
  },
  {
    id: 'grinder-team-schedule', title: '队伍赛程', period: 'NORMAL', conds: [done('grinder-coach-trust')],
    desc: '次级联赛的赛程很密：周末比赛，周中训练，偶尔还有赞助商线下活动。',
    options: [
      { id: 'follow-pace', label: '适应密集节奏', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 3), stat(ENERGY, -4)], msg: ['你学会了在赛程缝隙里恢复。', '两个月后，你成了队里最稳的人。'], next: 'grinder-lower-tier-title' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 8)], msg: ['密集赛程榨干了你的体能。', '你的状态开始像坐过山车。'], next: 'grinder-lower-tier-title' } },
      { id: 'skip-events', label: '推掉线下活动', chance: 0.65,
        s: { fx: [stat(ENERGY, 6), stat(TEAM_CONFLICT, -2)], msg: ['你推掉了几场活动，专心训练。', '俱乐部没说什么，但心里记了一笔。'], next: 'grinder-lower-tier-title' },
        f: { fx: [stat(MORALE, -4), cstat('CAREER_EARNINGS', -200)], msg: ['推掉活动少了笔补贴。', '你的钱包替你记住了。'], next: 'grinder-lower-tier-title' } },
    ],
  },
  {
    id: 'grinder-lower-tier-title', title: '次级冠军', period: 'NORMAL', conds: [done('grinder-team-schedule')],
    desc: '次级联赛总决赛。对手是去年的冠军，你们是黑马。',
    options: [
      { id: 'clutch-final', label: '全力一搏', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [trophy('S_TIER', 1), stat(MORALE, 15), cstat('TOTAL_KILLS', 45), flag('TIER2_CHAMP', '次级冠军', 'ACHIEVEMENT')], msg: ['你们 3:1 掀翻了卫冕冠军。', '奖杯是玻璃的，但举起来很沉。'], next: 'grinder-promotion-chance' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -4)], msg: ['决胜局你们被翻盘。', '差一点，就差一点。'], next: 'grinder-promotion-chance' } },
      { id: 'underdog-play', label: '当黑马放开了打', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), trophy('S_TIER', 1), stat(MORALE, 12)], msg: ['没人看好你们，你们反而放开了。', '冠军到手，整个基地叫了一晚上。'], next: 'grinder-promotion-chance' },
        f: { fx: [stat(STRESS, 8)], msg: ['放开打变成了乱打。', '黑马倒在了半决赛。'], next: 'grinder-promotion-chance' } },
    ],
  },
  {
    id: 'grinder-promotion-chance', title: '升级机会', period: 'NORMAL', conds: [done('grinder-lower-tier-title')],
    desc: '联赛改制，冠亚军可以晋级到更高级别的赛事体系。你们手握门票。',
    options: [
      { id: 'take-promotion', label: '接受晋级', chance: 0.7,
        s: { fx: [stat(MORALE, 10), flag('PROMOTED', '升级成功', 'ACHIEVEMENT')], msg: ['你们集体升入更高级别。', '新赛程表下来那天，全队围在一起看了很久。'], next: 'grinder-tryout-tier1' },
        f: { fx: [stat(STRESS, 8)], msg: ['晋级意味着更大的开销和更强的对手。', '有人开始打退堂鼓。'], next: 'grinder-tryout-tier1' } },
      { id: 'stay-and-build', label: '留在原级别稳固', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你建议再沉淀一年。', '队伍同意了，但你知道有人不太甘心。'], next: 'grinder-tryout-tier1' },
        f: { fx: [stat(MORALE, -6)], msg: ['你的保守让队内有了裂痕。', '有两个人悄悄在找下家。'], next: 'grinder-tryout-tier1' } },
    ],
  },
  {
    id: 'grinder-tryout-tier1', title: '一线试训', period: 'NORMAL', conds: [done('grinder-promotion-chance')],
    desc: '一支顶级联赛队伍看了你们晋级后的比赛，向你发出试训邀请。',
    options: [
      { id: 'try-hard', label: '全力试训', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 10), flag('TIER1_TRYOUT', '一线试训', 'CAREER')], msg: ['你在试训棚里打出了自己的水平。', '他们让你等一周的消息。'], next: 'grinder-flop-tryout' },
        f: { fx: [stat(STRESS, 12)], msg: ['试训对手太强，你被打懵了。', '你第一次直观感受到顶级水平的差距。'], next: 'grinder-flop-tryout' } },
      { id: 'manage-hype', label: '平常心对待', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你把试训当成普通训练赛。', '心态放松，发挥反而稳定。'], next: 'grinder-flop-tryout' },
        f: { fx: [stat(STRESS, 8)], msg: ['太想表现，你全程紧绷。', '教练看你的眼神带着遗憾。'], next: 'grinder-flop-tryout' } },
    ],
  },
  {
    id: 'grinder-flop-tryout', title: '试训翻车', period: 'NORMAL', conds: [done('grinder-tryout-tier1')],
    desc: '试训结果出来了：不通过。理由是「上限存疑，不值得冒险」。',
    options: [
      { id: 'swallow-it', label: '咽下这口气', chance: 0.6,
        s: { fx: [stat(MORALE, -4), stat(STRESS, -4)], msg: ['你把通知截图存了下来。', '它成了你电脑桌面的背景。'], next: 'grinder-second-chance' },
        f: { fx: [stat(MORALE, -10), stat(STRESS, 8)], msg: ['「上限存疑」这四个字扎了你很久。', '你失眠了三天。'], next: 'grinder-second-chance' } },
      { id: 'ask-why', label: '追问原因', chance: 0.5,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你发邮件问了详细反馈。', '他们居然真的回了：残局决策偏保守。'], next: 'grinder-second-chance' },
        f: { fx: [stat(STRESS, 8)], msg: ['追问没有回音。', '你把邮件当草稿存了半年。'], next: 'grinder-second-chance' } },
    ],
  },
  {
    id: 'grinder-second-chance', title: '第二次机会', period: 'NORMAL', conds: [done('grinder-flop-tryout')],
    desc: '半年后，那支队伍的管理层换了人。新负责人重新翻看了你的数据，发来第二条消息。',
    options: [
      { id: 'retry', label: '再试一次', chance: 0.6, mods: [{ attribute: CLUTCH, perPoint: 0.008 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 12)], msg: ['第二次试训，你针对「残局保守」做了改变。', '这一次，他们让你通过了。'], next: 'grinder-make-team' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你越想证明改变，越被旧习惯拖住。', '第二次试训又失败了。'], next: 'grinder-make-team' } },
      { id: 'prove-in-matches', label: '用比赛证明', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 8)], msg: ['你没去试训，而是带队打出了更好的成绩。', '对方主动把合同递到了你手上。'], next: 'grinder-make-team' },
        f: { fx: [stat(MORALE, -4)], msg: ['比赛证明的进度太慢。', '对方等不及，签了别人。'], next: 'grinder-make-team' } },
    ],
  },
  {
    id: 'grinder-make-team', title: '打进正式队', period: 'NORMAL', conds: [done('grinder-second-chance')],
    desc: '你正式加入顶级联赛队伍。签合同那天，基地的食堂比你租的房间还大。',
    options: [
      { id: 'settle-in', label: '低调融入', chance: 0.7,
        s: { fx: [stat(MORALE, 10), cstat('CAREER_EARNINGS', 4000), flag('TIER1_PLAYER', '顶级联赛选手', 'ACHIEVEMENT')], msg: ['你从替补开始，慢慢适应顶级联赛的节奏。', '你比谁都清楚，这条路走了多久。'], next: 'grinder-first-tier1-match' },
        f: { fx: [stat(STRESS, 8)], msg: ['融入得不算顺利，你总觉得自己是外人。', '你花了很久才敢在训练里大声说话。'], next: 'grinder-first-tier1-match' } },
      { id: 'prove-worth', label: '争取首发', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 10)], msg: ['你在训练赛里打出了首发的水平。', '教练给了你第一场正式比赛的机会。'], next: 'grinder-first-tier1-match' },
        f: { fx: [stat(TEAM_CONFLICT, 2), stat(STRESS, 10)], msg: ['争首发的动作太大，队里有人不高兴。', '你的处子秀被推迟了。'], next: 'grinder-first-tier1-match' } },
    ],
  },
  {
    id: 'grinder-first-tier1-match', title: '顶级首战', period: 'NORMAL', conds: [done('grinder-make-team')],
    desc: '顶级联赛首秀，对手是卫冕冠军。赛前更衣室里，你听见自己的心跳声。',
    options: [
      { id: 'steady-debut', label: '稳着打', chance: 0.55, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), cstat('MAPS_PLAYED', 1), cstat('TOTAL_KILLS', 30), stat(MORALE, 12)], msg: ['你没有亮点，也没有大错。', '教练赛后说：这才是顶级联赛的首秀。'], next: 'grinder-underdog-win' },
        f: { fx: [stat(STRESS, 12)], msg: ['你紧张到第一局鼠标都握不稳。', '好在队友兜住了，但你记住了那种感觉。'], next: 'grinder-underdog-win' } },
      { id: 'statement-game', label: '打一场宣言战', chance: 0.45, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), cstat('TOTAL_KILLS', 45), stat(MORALE, 14)], msg: ['你打了场漂亮的首秀，解说开始查你的资料。', '「这名选手来自次级联赛？」'], next: 'grinder-underdog-win' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['宣言战打成了车祸现场。', '弹幕都在刷「次级联赛水平」。'], next: 'grinder-underdog-win' } },
    ],
  },
  {
    id: 'grinder-underdog-win', title: '爆冷取胜', period: 'NORMAL', conds: [done('grinder-first-tier1-match')],
    desc: '你们 2:0 击败了排名第一的队伍。赛后采访，记者把话筒递给了你。',
    options: [
      { id: 'humble-words', label: '把功劳归给团队', chance: 0.7,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['你说这是全队的胜利。', '队友们在群里疯狂截图夸你会说话。'], next: 'grinder-consistency-problem' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['你话说得太官方，显得疏远。', '但比赛赢了，没人计较。'], next: 'grinder-consistency-problem' } },
      { id: 'share-joy', label: '真情实感庆祝', chance: 0.6,
        s: { fx: [stat(MORALE, 10)], msg: ['你说自己等了三年才等到这场胜利。', '这段话被剪成了短片，传播很广。'], next: 'grinder-consistency-problem' },
        f: { fx: [stat(STRESS, 6)], msg: ['你激动到语无伦次。', '但那股真诚反而很圈粉。'], next: 'grinder-consistency-problem' } },
    ],
  },
  {
    id: 'grinder-consistency-problem', title: '稳定性问题', period: 'NORMAL', conds: [done('grinder-underdog-win')],
    desc: '爆冷后你们连续输给弱队。数据分析师说：队伍上下限差距太大，主因是你。',
    options: [
      { id: 'fix-baseline', label: '先守住下限', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 6)], msg: ['你放弃了一些高风险的打法。', '下限稳住了，上限暂时放一边。'], next: 'grinder-coach-fix' },
        f: { fx: [stat(STRESS, 8)], msg: ['你试着求稳，反而打得束手束脚。', '下限没守住，上限也没了。'], next: 'grinder-coach-fix' } },
      { id: 'find-pattern', label: '找状态波动规律', chance: 0.55,
        s: { fx: [attr(GAME_SENSE, 2), attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你发现自己的波动和睡眠高度相关。', '你开始强制保证睡眠。'], next: 'grinder-coach-fix' },
        f: { fx: [stat(ENERGY, -6)], msg: ['规律没找到，你先把自己研究焦虑了。', '分析师摇摇头。'], next: 'grinder-coach-fix' } },
    ],
  },
  {
    id: 'grinder-coach-fix', title: '教练矫正', period: 'NORMAL', conds: [done('grinder-consistency-problem')],
    desc: '教练把你从自由人调回突破手：「你的价值是撕开防线，不是绕后偷人。」',
    options: [
      { id: 'obey-change', label: '服从调整', chance: 0.6, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), role('ENTRY'), stat(MORALE, 6)], msg: ['回到突破手，你的数据立刻回暖。', '教练的判断是对的。'], next: 'grinder-slump' },
        f: { fx: [stat(MORALE, -4), stat(STRESS, 6)], msg: ['换位置让你状态下滑了两周。', '你心里不服，但数据很诚实。'], next: 'grinder-slump' } },
      { id: 'negotiate-role', label: '争取折中方案', chance: 0.55,
        s: { fx: [role('LURK'), attr(GAME_SENSE, 2), stat(MORALE, 8)], msg: ['你提出保留自由人但有更多配合。', '教练同意试一个月。'], next: 'grinder-slump' },
        f: { fx: [stat(TEAM_CONFLICT, 3), stat(STRESS, 8)], msg: ['讨价还价让教练皱眉。', '最终你还是改了位置，但留了疙瘩。'], next: 'grinder-slump' } },
    ],
  },
  {
    id: 'grinder-slump', title: '状态低谷', period: 'NORMAL', conds: [done('grinder-coach-fix')],
    desc: '状态低谷毫无预兆地来了：训练赛全在梦游，正式比赛数据垫底。',
    options: [
      { id: 'push-through', label: '硬练度过', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 4), stat(ENERGY, -6)], msg: ['你靠加练硬生生熬过了低谷。', '虽然过程痛苦，但枪感回来了。'], next: 'grinder-rebound' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 10)], msg: ['硬练让你的低谷更长了。', '教练强制你休息了两天。'], next: 'grinder-rebound' } },
      { id: 'step-back', label: '退一步调整', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), stat(STRESS, -8)], msg: ['你主动降强度，休息加复盘。', '一周后，状态自己回来了。'], next: 'grinder-rebound' },
        f: { fx: [stat(MORALE, -6)], msg: ['休息让你错过了关键训练赛。', '首发位置开始被质疑。'], next: 'grinder-rebound' } },
    ],
  },
  {
    id: 'grinder-rebound', title: '状态反弹', period: 'NORMAL', conds: [done('grinder-slump')],
    desc: '低谷过后，你打出了职业生涯最连贯的一周。有人开始讨论你的「上限」。',
    options: [
      { id: 'capitalize', label: '趁势多打比赛', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你在这一周里打进了队伍历史数据前列。', '「上限」这个词开始和你挂钩。'], next: 'grinder-sponsor-local' },
        f: { fx: [stat(ENERGY, -8)], msg: ['连续加赛消耗了你。', '好状态没能延续到下周。'], next: 'grinder-sponsor-local' } },
      { id: 'stay-grounded', label: '不膨胀', chance: 0.7,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 6)], msg: ['你提醒自己这只是低谷后的反弹。', '这份清醒让你躲过了不少吹捧。'], next: 'grinder-sponsor-local' },
        f: { fx: [stat(MORALE, -4)], msg: ['太冷静显得不合群，队友说你扫兴。', '但你自己知道，冷静是对的。'], next: 'grinder-sponsor-local' } },
    ],
  },
  {
    id: 'grinder-sponsor-local', title: '本地赞助', period: 'NORMAL', conds: [done('grinder-rebound')],
    desc: '一家本地电竞馆找你代言：拍宣传照，每周去一次线下活动，给 3000 块。',
    options: [
      { id: 'take-local', label: '接本地代言', chance: 0.7,
        s: { fx: [cstat('CAREER_EARNINGS', 3000), stat(MORALE, 6)], msg: ['宣传照拍得有些土，但钱是实的。', '你每周去电竞馆打一场表演赛。'], next: 'grinder-stream-side' },
        f: { fx: [stat(STRESS, 6)], msg: ['宣传活动挤占了训练。', '你开始怀疑这笔钱值不值。'], next: 'grinder-stream-side' } },
      { id: 'decline-local', label: '婉拒，专注训练', chance: 0.6,
        s: { fx: [stat(MORALE, 6), stat(ENERGY, 4)], msg: ['你婉拒了，时间全留给训练。', '电竞馆老板有点失望，但没勉强。'], next: 'grinder-stream-side' },
        f: { fx: [stat(MORALE, -4)], msg: ['拒绝后，本地圈子觉得你「红了就端架子」。', '你无所谓，但流言很烦。'], next: 'grinder-stream-side' } },
    ],
  },
  {
    id: 'grinder-stream-side', title: '直播副业', period: 'NORMAL', conds: [done('grinder-sponsor-local')],
    desc: '有平台想签你做兼职主播：每月播 40 小时，收入按礼物分成。',
    options: [
      { id: 'stream-extra', label: '接下直播合同', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 1500), stat(MORALE, 6)], msg: ['直播带来了额外收入，人气也在涨。', '但 40 小时是真的挤时间。'], next: 'grinder-time-split' },
        f: { fx: [stat(ENERGY, -10), stat(STRESS, 6)], msg: ['直播和训练打架，你两边的质量都下滑。', '你不得不砍掉一半直播。'], next: 'grinder-time-split' } },
      { id: 'no-stream', label: '不碰直播', chance: 0.7,
        s: { fx: [stat(ENERGY, 4), stat(STRESS, -4)], msg: ['你回绝了直播合同。', '少一笔钱，多一份清净。'], next: 'grinder-time-split' },
        f: { fx: [stat(MORALE, -4)], msg: ['看着别人直播带货，你偶尔也眼热。', '但你的训练表确实排不下。'], next: 'grinder-time-split' } },
    ],
  },
  {
    id: 'grinder-time-split', title: '时间分配', period: 'NORMAL', conds: [done('grinder-stream-side')],
    desc: '训练、比赛、直播、休息，四件事在抢你的 24 小时。你第一次体会到时间管理的重要。',
    options: [
      { id: 'build-schedule', label: '做时间表', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 2), stat(ENERGY, 8)], msg: ['你给自己排了严格的时间表。', '执行一周后，效率明显提升。'], next: 'grinder-injury-poverty' },
        f: { fx: [stat(STRESS, 6)], msg: ['时间表排得太满，执行三天就崩了。', '你学会了给计划留白。'], next: 'grinder-injury-poverty' } },
      { id: 'flex-mode', label: '顺其自然', chance: 0.6,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 4)], msg: ['你不强求计划，状态好就多练。', '这套弹性模式意外地适合你。'], next: 'grinder-injury-poverty' },
        f: { fx: [stat(ENERGY, -6)], msg: ['顺其自然的代价是训练时长不稳。', '教练开始过问你的作息。'], next: 'grinder-injury-poverty' } },
    ],
  },
  {
    id: 'grinder-injury-poverty', title: '没钱治伤', period: 'NORMAL', conds: [done('grinder-time-split')],
    desc: '手腕旧伤复发，队医建议做理疗，但俱乐部报销只覆盖一半。',
    options: [
      { id: 'self-pay', label: '自费理疗', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -800), stat(ENERGY, 8), flag('HAND_FIXED', '手腕恢复', 'CAREER')], msg: ['你花自己的钱做了完整理疗。', '手腕好利索了，钱也花出去了。'], next: 'grinder-health-call' },
        f: { fx: [cstat('CAREER_EARNINGS', -800), stat(STRESS, 8)], msg: ['理疗费让你心疼了好几天。', '但你知道，这钱省不得。'], next: 'grinder-health-call' } },
      { id: 'cheap-therapy', label: '找便宜的方式', chance: 0.5,
        s: { fx: [stat(ENERGY, 4), stat(STRESS, 4)], msg: ['你找了个便宜的中医馆。', '效果慢，但手腕确实好转了。'], next: 'grinder-health-call' },
        f: { fx: [stat(STRESS, 10), stat(ENERGY, -4)], msg: ['便宜理疗不管用，手腕反而更疼。', '你最后还是回了正规理疗。'], next: 'grinder-health-call' } },
    ],
  },
  {
    id: 'grinder-health-call', title: '健康抉择', period: 'NORMAL', conds: [done('grinder-injury-poverty')],
    desc: '体检报告显示你的颈椎和腰椎都有劳损。医生建议减少训练时长。',
    options: [
      { id: 'listen-doctor', label: '听医生的', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), stat(STRESS, -6)], msg: ['你开始规律拉伸，减了加练时长。', '身体稳住了，训练效率反而高了。'], next: 'grinder-big-match' },
        f: { fx: [stat(MORALE, -4)], msg: ['你听医生的话，但总怕训练量不够。', '你在「听劝」和「不甘心」之间拉扯。'], next: 'grinder-big-match' } },
      { id: 'play-through', label: '坚持高强度', chance: 0.45,
        s: { fx: [stat(ENERGY, 6), stat(MORALE, 6), flag('BODY_ALARM', '身体警报', 'MENTAL')], msg: ['你咬牙维持高强度训练。', '短期内状态不错，但你知道这是透支。'], next: 'grinder-big-match' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 10)], msg: ['你的腰在训练中突然疼得直不起来。', '队医强制你休息两周。'], next: 'grinder-big-match' } },
    ],
  },
  {
    id: 'grinder-big-match', title: '关键比赛', period: 'NORMAL', conds: [done('grinder-health-call')],
    desc: '赛季末的关键战：赢就进季后赛，输就放假回家。',
    options: [
      { id: 'clutch-key', label: '关键时刻顶上', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 12)], msg: ['你在关键局顶住了压力。', '队伍晋级，你就是功臣之一。'], next: 'grinder-championship' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你在大场面又手软了。', '晋级的门票从你手里滑走。'], next: 'grinder-championship' } },
      { id: 'team-first', label: '当绿叶保队友', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['你主动打辅助位，把资源让给状态好的队友。', '他们赢了，你也跟着进了季后赛。'], next: 'grinder-championship' },
        f: { fx: [stat(MORALE, -6)], msg: ['让资源的队友没能站出来。', '你成了「牺牲也没用」的注脚。'], next: 'grinder-championship' } },
    ],
  },
  {
    id: 'grinder-championship', title: '季后赛', period: 'FINAL_DECISIVE_MOMENT', conds: [done('grinder-big-match')],
    desc: '季后赛首轮，你们对阵常规赛冠军。赛前赔率 1 比 7。',
    options: [
      { id: 'giant-kill', label: '创造奇迹', chance: 0.4, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('S_TIER', 1), stat(MORALE, 15)], msg: ['你们爆冷淘汰了常规赛冠军。', '解说管这轮系列赛叫「本年度最大冷门」。'], next: 'grinder-rival' },
        f: { fx: [stat(STRESS, 12)], msg: ['奇迹没有发生，你们 0:3 出局。', '但你们每一局都打得很拼。'], next: 'grinder-rival' } },
      { id: 'learn-series', label: '当学习机会', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 8)], msg: ['你们输给了冠军，但偷到了他们的战术。', '这套战术后来帮你们赢了不少比赛。'], next: 'grinder-rival' },
        f: { fx: [stat(STRESS, 8)], msg: ['学习的机会变成了被碾压。', '你们输得毫无还手之力。'], next: 'grinder-rival' } },
    ],
  },
  {
    id: 'grinder-rival', title: '宿敌对决', period: 'NORMAL', conds: [done('grinder-championship')],
    desc: '联赛里有一支队伍总在针对你：赛前嘲讽、赛后阴阳、训练赛下死手。',
    options: [
      { id: 'beat-them', label: '用胜利回击', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 12), cstat('TOTAL_KILLS', 40)], msg: ['你在对阵他们时打出了统治级表现。', '赛后他们的社交媒体安静了很久。'], next: 'grinder-veteran-advice2' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你又输给了他们。', '他们的嘲讽越发得意。'], next: 'grinder-veteran-advice2' } },
      { id: 'ignore-them', label: '无视挑衅', chance: 0.7,
        s: { fx: [stat(STRESS, -8), stat(MORALE, 4)], msg: ['你选择无视，专注自己的比赛。', '他们找不到你的情绪破绽，反而有点慌。'], next: 'grinder-veteran-advice2' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['无视被解读成认怂。', '队友说你太软了。'], next: 'grinder-veteran-advice2' } },
    ],
  },
  {
    id: 'grinder-veteran-advice2', title: '老将忠告', period: 'NORMAL', conds: [done('grinder-rival')],
    desc: '队里最老的选手快退役了。他约你吃饭，说他从你身上看到了自己当年的影子。',
    options: [
      { id: 'listen-career', label: '听他的职业总结', chance: 0.7,
        s: { fx: [attr(GAME_SENSE, 2), attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['他讲了十年职业生涯的三个后悔。', '你把这些话记在了手机备忘录里。'], next: 'grinder-team-drama' },
        f: { fx: [stat(ENERGY, -4)], msg: ['你听了一半，觉得这些离自己还远。', '后来你才明白他为什么说那些话。'], next: 'grinder-team-drama' } },
      { id: 'ask-success', label: '问他成功的秘密', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['他说：不是天赋，是每天多做一点。', '这句话成了你的座右铭。'], next: 'grinder-team-drama' },
        f: { fx: [stat(STRESS, 6)], msg: ['他回答得很笼统。', '「秘密」这种东西，果然不能指望别人给。'], next: 'grinder-team-drama' } },
    ],
  },
  {
    id: 'grinder-team-drama', title: '队伍内讧', period: 'NORMAL', conds: [done('grinder-veteran-advice2')],
    desc: '两名主力因为一张地图的战术吵了起来，越吵越凶，训练室的门被摔得哐哐响。',
    options: [
      { id: 'mediate', label: '出面调解', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), stat(TEAM_CONFLICT, -5), stat(MORALE, 8)], msg: ['你把两人拉到会议室，让他们把话说完。', '吵完之后，战术反而统一了。'], next: 'grinder-captain-role' },
        f: { fx: [stat(TEAM_CONFLICT, 5), stat(STRESS, 8)], msg: ['调解变成三方混战。', '你被两个人都记恨上了。'], next: 'grinder-captain-role' } },
      { id: 'stay-out', label: '不掺和', chance: 0.7,
        s: { fx: [stat(STRESS, -4)], msg: ['你选择不站队。', '风波过去后，两人都当你是自己人。'], next: 'grinder-captain-role' },
        f: { fx: [stat(TEAM_CONFLICT, 3)], msg: ['不掺和的代价是队伍散了心。', '接下来的比赛打得一盘散沙。'], next: 'grinder-captain-role' } },
    ],
  },
  {
    id: 'grinder-captain-role', title: '队长之位', period: 'NORMAL', conds: [done('grinder-team-drama')],
    desc: '队长转会了。俱乐部问了一圈，最后把目光停在你身上。',
    options: [
      { id: 'take-armband2', label: '接过队长袖标', chance: 0.6, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), role('IGL'), stat(MORALE, 10), flag('TEAM_CAPTAIN', '队长', 'ACHIEVEMENT')], msg: ['你成了这支队伍的队长。', '从一个低级联赛的替补，到顶级联赛的队长。'], next: 'grinder-leadership-chance' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['队长责任让你分心，状态下滑。', '你撑了半个赛季就交了出去。'], next: 'grinder-leadership-chance' } },
      { id: 'decline-armband', label: '让贤', chance: 0.65,
        s: { fx: [stat(TEAM_CONFLICT, -2), stat(MORALE, 6)], msg: ['你推荐了更年轻的指挥苗子。', '他干得不错，你专注自己的比赛。'], next: 'grinder-leadership-chance' },
        f: { fx: [stat(MORALE, -4)], msg: ['让贤之后，队内觉得你没担当。', '你的话语权悄悄变弱了。'], next: 'grinder-leadership-chance' } },
    ],
  },
  {
    id: 'grinder-leadership-chance', title: '领袖机会', period: 'NORMAL', conds: [done('grinder-captain-role')],
    desc: '赛季中期，队伍陷入低谷。更衣室里没人说话，大家都在等一个声音。',
    options: [
      { id: 'speak-first', label: '第一个开口', chance: 0.6, mods: [{ attribute: LEADERSHIP, perPoint: 0.01 }],
        s: { fx: [attr(LEADERSHIP, 3), stat(MORALE, 10)], msg: ['你打破了沉默，把问题摆上台面。', '那场会议后，队伍重新拧成一股绳。'], next: 'grinder-national-tour' },
        f: { fx: [stat(TEAM_CONFLICT, 3), stat(STRESS, 8)], msg: ['你的发言被质疑，更衣室更冷了。', '你第一次体会到领袖的代价。'], next: 'grinder-national-tour' } },
      { id: 'wait-out', label: '等教练处理', chance: 0.7,
        s: { fx: [stat(STRESS, -4)], msg: ['你把问题留给教练。', '教练处理了，但队伍少了点「自己人」的感觉。'], next: 'grinder-national-tour' },
        f: { fx: [stat(MORALE, -6)], msg: ['等来等去，问题发酵成了连败。', '你后悔当时没开口。'], next: 'grinder-national-tour' } },
    ],
  },
  {
    id: 'grinder-national-tour', title: '全国巡回', period: 'NORMAL', conds: [done('grinder-leadership-chance')],
    desc: '俱乐部组织了全国巡回表演赛。每个城市都有粉丝举着你的 ID 牌。',
    options: [
      { id: 'enjoy-tour', label: '享受巡回赛', chance: 0.7,
        s: { fx: [stat(MORALE, 12), cstat('CAREER_EARNINGS', 800)], msg: ['你第一次感受到被粉丝包围的感觉。', '一个小孩举着你的签名板等了两个小时。'], next: 'grinder-media-recognition' },
        f: { fx: [stat(ENERGY, -8)], msg: ['连续赶场让你疲惫不堪。', '后半程你的表演赛状态很差。'], next: 'grinder-media-recognition' } },
      { id: 'keep-training', label: '巡回中也训练', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 2), stat(ENERGY, -6)], msg: ['你带着训练计划跑完了全程。', '巡回结束后，你的状态没有掉队。'], next: 'grinder-media-recognition' },
        f: { fx: [stat(ENERGY, -10)], msg: ['训练和赶场两头顾，你累垮了。', '巡回结束你躺了三天。'], next: 'grinder-media-recognition' } },
    ],
  },
  {
    id: 'grinder-media-recognition', title: '媒体关注', period: 'NORMAL', conds: [done('grinder-national-tour')],
    desc: '一篇题为「从网吧到顶级联赛」的报道让你出了圈。评论区吵翻了：有夸的，有说炒作的。',
    options: [
      { id: 'ride-media', label: '接受更多采访', chance: 0.6,
        s: { fx: [stat(MORALE, 8), cstat('CAREER_EARNINGS', 1000)], msg: ['采访邀请越来越多，你讲的故事越来越完整。', '品牌方也开始找你。'], next: 'grinder-family-pride' },
        f: { fx: [stat(STRESS, 10)], msg: ['采访中你的一句话被断章取义。', '舆论开始翻你的旧账。'], next: 'grinder-family-pride' } },
      { id: 'keep-head-down', label: '低调回应', chance: 0.7,
        s: { fx: [stat(STRESS, -6)], msg: ['你只回了句「谢谢，继续努力」。', '热度过去得很快，生活恢复平静。'], next: 'grinder-family-pride' },
        f: { fx: [stat(MORALE, -4)], msg: ['低调被解读成傲慢。', '「红了就飘」的帽子扣了上来。'], next: 'grinder-family-pride' } },
    ],
  },
  {
    id: 'grinder-family-pride', title: '家人骄傲', period: 'NORMAL', conds: [done('grinder-media-recognition')],
    desc: '妈妈转发了一条你的比赛集锦到家庭群里，配文：「我儿子」。亲戚们纷纷点赞。',
    options: [
      { id: 'feel-proud', label: '坦然接受这份骄傲', chance: 0.7,
        s: { fx: [stat(MORALE, 12)], msg: ['你给妈妈回了句：妈，看到了。', '家庭群的记录你截图存了下来。'], next: 'grinder-midlife-crisis' },
        f: { fx: [stat(STRESS, 6)], msg: ['家人的期待让你压力陡增。', '「不能让他们失望」成了新的枷锁。'], next: 'grinder-midlife-crisis' } },
      { id: 'share-back', label: '回馈家人', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -1500), stat(MORALE, 10)], msg: ['你给家里换了台新空调。', '妈妈说：别乱花钱。语气却藏不住高兴。'], next: 'grinder-midlife-crisis' },
        f: { fx: [stat(STRESS, 6)], msg: ['钱花出去了，家里却说你「飘了」。', '孝顺和距离之间的分寸，你还没学会。'], next: 'grinder-midlife-crisis' } },
    ],
  },
  {
    id: 'grinder-midlife-crisis', title: '瓶颈中年', period: 'NORMAL', conds: [done('grinder-family-pride')],
    desc: '你 26 岁了。在电竞圈，这个年龄被称为「职业生涯后期」。你开始数着日子打比赛。',
    options: [
      { id: 'adapt-game', label: '转型靠经验打球', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 3), attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['你发现自己打不动对枪了，但读得懂比赛。', '你转型成了队伍的大脑。'], next: 'grinder-retire-thought' },
        f: { fx: [stat(STRESS, 8)], msg: ['转型尝试很别扭，你不适应新的打法。', '你卡在「该变又不敢变」的中间。'], next: 'grinder-retire-thought' } },
      { id: 'train-harder', label: '不服老，加练', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 6), stat(ENERGY, -8)], msg: ['你靠加倍训练维持着手感。', '效果有，但恢复越来越慢。'], next: 'grinder-retire-thought' },
        f: { fx: [stat(ENERGY, -14), stat(STRESS, 8)], msg: ['你的身体开始拒绝加练。', '腰和手腕都在抗议。'], next: 'grinder-retire-thought' } },
    ],
  },
  {
    id: 'grinder-retire-thought', title: '退役念头', period: 'NORMAL', conds: [done('grinder-midlife-crisis')],
    desc: '深夜训练结束后，你盯着天花板想：要不，打完今年就退了吧。这个念头一冒出来就甩不掉。',
    options: [
      { id: 'finish-season', label: '打完这赛季再说', chance: 0.65,
        s: { fx: [stat(MORALE, 6), stat(STRESS, -6)], msg: ['你决定把念头按下，先打完这个赛季。', '有了期限，比赛反而打得更纯粹。'], next: 'grinder-last-shot' },
        f: { fx: [stat(MORALE, -6), stat(STRESS, 8)], msg: ['「最后一季」的心态让你患得患失。', '每场比赛都像在倒计时。'], next: 'grinder-last-shot' } },
      { id: 'push-harder', label: '再拼一年', chance: 0.55,
        s: { fx: [stat(MORALE, 8), stat(ENERGY, -4)], msg: ['你决定不退了，再拼一年。', '这个决定让你训练得更认真。'], next: 'grinder-last-shot' },
        f: { fx: [stat(ENERGY, -10)], msg: ['想拼的心很热，身体却跟不上。', '你第一次感觉自己在和年龄赛跑。'], next: 'grinder-last-shot' } },
    ],
  },
  {
    id: 'grinder-last-shot', title: '最后一搏', period: 'FINAL_DECISIVE_MOMENT', conds: [done('grinder-retire-thought')],
    desc: '你职业生涯最重要的比赛：赢下它，你能带着冠军退役；输了，就带着遗憾离开。',
    options: [
      { id: 'all-in-legacy', label: '拼尽所有', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('S_TIER', 1), cstat('TOTAL_KILLS', 42), flag('LEGACY_MATCH', '封神之战', 'ACHIEVEMENT')], msg: ['你打出了职业生涯最好的比赛。', '夺冠那晚，你的手机响了一整夜。'], next: 'grinder-prodigy-burst' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你拼尽了全力，还是输了。', '赛后你坐在休息室里，很久没有起身。'], next: 'grinder-prodigy-burst' } },
      { id: 'play-free', label: '放开打不留遗憾', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 2), trophy('S_TIER', 1), stat(MORALE, 12)], msg: ['你卸下所有包袱，打得又稳又放松。', '冠军到手，你反而没有想象中激动。'], next: 'grinder-prodigy-burst' },
        f: { fx: [stat(STRESS, 10)], msg: ['放开打变成乱打，你们输了。', '但赛后你睡得意外地香。'], next: 'grinder-prodigy-burst' } },
    ],
  },
  // ============ 极端事件 ============
  {
    id: 'grinder-betrayal', title: '队友背叛', period: 'NORMAL', conds: [done('grinder-last-shot')],
    desc: '你发现一位队友在向对手泄露你们的战术。证据，是他深夜和对方教练的通话录音。',
    options: [
      { id: 'report-leak', label: '上报俱乐部', chance: 0.55,
        s: { fx: [stat(TEAM_CONFLICT, -6), stat(MORALE, 10), flag('LEAK_EXPOSED', '泄密被查', 'CAREER')], msg: ['俱乐部介入调查，他被迫离队。', '你保全了队伍，也失去了一位「朋友」。'], next: 'grinder-fake-illness' },
        f: { fx: [stat(STRESS, 12)], msg: ['上报后证据不足，他留了下来。', '你知道他知道了你知道。'], next: 'grinder-fake-illness' } },
      { id: 'confront-him', label: '当面质问', chance: 0.5,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['你把他堵在楼梯间。', '他承认了，也道歉了，但信任已经碎了。'], next: 'grinder-fake-illness' },
        f: { fx: [stat(TEAM_CONFLICT, 6), stat(STRESS, 14)], msg: ['他不承认，反而倒打一耙。', '你成了「多疑的人」。'], next: 'grinder-fake-illness' } },
    ],
  },
  {
    id: 'grinder-fake-illness', title: '诈伤风波', period: 'NORMAL', conds: [done('grinder-betrayal')],
    desc: '有个替补为了保首发，谎称伤病让关键选手休息。你偶然发现了他的体检造假。',
    options: [
      { id: 'expose-truth', label: '揭穿真相', chance: 0.55,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 10)], msg: ['你把证据交给了队医。', '替补被处理，但你也成了「爱管闲事」的人。'], next: 'grinder-sponsor-drop' },
        f: { fx: [stat(STRESS, 12)], msg: ['揭穿失败，反而让替补记恨你。', '他开始在队里散播你的谣言。'], next: 'grinder-sponsor-drop' } },
      { id: 'mind-own', label: '装作不知道', chance: 0.7,
        s: { fx: [stat(STRESS, -6)], msg: ['你选择不掺和。', '但每次看见他，你都觉得别扭。'], next: 'grinder-sponsor-drop' },
        f: { fx: [stat(MORALE, -6)], msg: ['装傻让你良心不安。', '关键选手真的因顶替而受伤时，你后悔了。'], next: 'grinder-sponsor-drop' } },
    ],
  },
  {
    id: 'grinder-sponsor-drop', title: '赞助撤资', period: 'NORMAL', conds: [done('grinder-fake-illness')],
    desc: '大赞助商突然撤资，俱乐部说工资要推迟一个月。更衣室炸了。',
    options: [
      { id: 'stay-put', label: '相信俱乐部', chance: 0.55,
        s: { fx: [stat(MORALE, 4), stat(STRESS, 6)], msg: ['你选择留下共渡难关。', '一个月后工资补上了，俱乐部记了你的情。'], next: 'grinder-dream-killer' },
        f: { fx: [stat(STRESS, 12), cstat('CAREER_EARNINGS', -1000)], msg: ['工资推迟成了两个月。', '你的房租开始告急。'], next: 'grinder-dream-killer' } },
      { id: 'jump-early', label: '提前找下家', chance: 0.5,
        s: { fx: [transfer('b8'), stat(MORALE, 8)], msg: ['你在风波前谈好了新队。', '新俱乐部待遇更好，但老东家骂你无情。'], next: 'grinder-dream-killer' },
        f: { fx: [stat(STRESS, 14)], msg: ['下家没谈成，老东家也对你寒心。', '你两头都没落着。'], next: 'grinder-dream-killer' } },
    ],
  },
  {
    id: 'grinder-dream-killer', title: '梦想劝退', period: 'NORMAL', conds: [done('grinder-sponsor-drop')],
    desc: '一位退役多年的前辈劝你：「趁年轻，去找份正经工作吧。」这句话比所有嘲讽都重。',
    options: [
      { id: 'hold-dream', label: '继续追梦', chance: 0.6,
        s: { fx: [stat(MORALE, 8), stat(STRESS, -4)], msg: ['你谢过前辈的好意。', '你比谁都清楚自己为什么还在打。'], next: 'grinder-final-salary' },
        f: { fx: [stat(MORALE, -8), stat(STRESS, 8)], msg: ['那晚你辗转难眠。', '「要不要听他的」这个问题缠了你一周。'], next: 'grinder-final-salary' } },
      { id: 'listen-senior', label: '认真考虑退路', chance: 0.55,
        s: { fx: [stat(STRESS, -6), flag('BACKUP_PLAN', '有退路', 'CAREER')], msg: ['你开始抽空学视频剪辑，给自己留退路。', '有退路之后，打比赛反而放松了。'], next: 'grinder-final-salary' },
        f: { fx: [stat(STRESS, 8)], msg: ['退路让你分心。', '你既没学成剪辑，也没打好比赛。'], next: 'grinder-final-salary' } },
    ],
  },
  {
    id: 'grinder-final-salary', title: '最后一笔工资', period: 'NORMAL', conds: [done('grinder-dream-killer')],
    desc: '俱乐部通知：赛季结束，你和另一位老将被列入离队名单。这是你在这里的最后一笔工资。',
    options: [
      { id: 'graceful-exit', label: '体面离开', chance: 0.7,
        s: { fx: [stat(MORALE, 8), stat(STRESS, -6)], msg: ['你谢过教练，和队友一一握手。', '离开那天，训练室的灯还亮着。'], next: 'grinder-prodigy-burst' },
        f: { fx: [stat(MORALE, -6)], msg: ['你走得不甘心。', '「为什么是我」这个问题没有人回答。'], next: 'grinder-prodigy-burst' } },
      { id: 'ask-stay', label: '争取留下', chance: 0.5,
        s: { fx: [stat(MORALE, 6), stat(TEAM_CONFLICT, -2)], msg: ['你和管理层谈了一晚，争取到了半个赛季。', '这半个赛季你打出了回春表现。'], next: 'grinder-prodigy-burst' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -6)], msg: ['挽留失败，名单没改。', '你带着遗憾离开了。'], next: 'grinder-prodigy-burst' } },
    ],
  },
  // ============ 世界线转换 ============
  {
    id: 'grinder-prodigy-burst', title: '一夜爆发', period: 'NORMAL', conds: [done('grinder-last-shot')],
    desc: '一位顶级分析师看了你的录像后说：「这个人的上限被他的经历低估了。」',
    options: [
      { id: 'believe-him', label: '相信自己的上限', chance: 0.65,
        s: { fx: [wl('prodigy'), stat(MORALE, 15), flag('CROSSED_TO_PRODIGY', '转入天才线', 'CUSTOM')], msg: ['你决定不再用「努力型选手」定义自己。', '上限这种东西，只有试了才知道。'], next: null },
        f: { fx: [stat(STRESS, 8)], msg: ['你不相信自己有那个上限。', '那句话成了你心里的一根刺。'], next: 'grinder-rookie-return' } },
      { id: 'stay-grinder', label: '按自己的节奏走', chance: 0.7,
        s: { fx: [stat(MORALE, 6)], msg: ['你谢过分析师，继续按部就班。', '稳扎稳打没什么不好。'], next: 'grinder-rookie-return' } ,
        f: { fx: [stat(MORALE, -4)], msg: ['拒绝高期待让你松口气，也让你遗憾。', '「如果当时赌一把呢？」'], next: 'grinder-rookie-return' } },
    ],
  },
  {
    id: 'grinder-rookie-return', title: '回炉重造', period: 'NORMAL', conds: [done('grinder-last-shot')],
    desc: '经纪人建议你换个环境：「去一支青训体系健全的队伍，重新打磨基本功。」',
    options: [
      { id: 'go-back', label: '放下身段回炉', chance: 0.6,
        s: { fx: [wl('rookie'), stat(MORALE, 10), flag('CROSSED_TO_ROOKIE', '转入新秀线', 'CUSTOM')], msg: ['你回到青训体系的队伍，从头打磨。', '这一次，你是带着经验回去的。'], next: null },
        f: { fx: [stat(STRESS, 8)], msg: ['放不下身段，你错过了这个建议。', '「回炉」两个字让你难受了很久。'], next: 'grinder-comeback-old' } },
      { id: 'stay-old', label: '留在熟悉环境', chance: 0.7,
        s: { fx: [stat(MORALE, 6)], msg: ['你选择留在熟悉的环境。', '舒服，但也单调。'], next: 'grinder-comeback-old' },
        f: { fx: [stat(MORALE, -4)], msg: ['留下后你总觉得缺了点什么。', '环境太熟，人容易懒。'], next: 'grinder-comeback-old' } },
    ],
  },
  {
    id: 'grinder-comeback-old', title: '老将再出发', period: 'NORMAL', conds: [done('grinder-last-shot')],
    desc: '有支队伍想签你当「更衣室定海神针」。他们不要你的数据，要你的经验。',
    options: [
      { id: 'senior-role', label: '以老将身份加盟', chance: 0.65,
        s: { fx: [wl('comeback'), stat(MORALE, 12), flag('CROSSED_TO_COMEBACK', '转入复出线', 'CUSTOM')], msg: ['你以老将身份加盟，开始了新的篇章。', '这个年纪，经验就是武器。'], next: null },
        f: { fx: [stat(STRESS, 8)], msg: ['「定海神针」这个头衔让你压力很大。', '你拒绝了，但心里不是滋味。'], next: 'grinder-matchfixing-desperate' } },
      { id: 'decline-role', label: '婉拒', chance: 0.7,
        s: { fx: [stat(MORALE, 6)], msg: ['你婉拒了那份邀约。', '你还想以主力身份打几年。'], next: 'grinder-matchfixing-desperate' },
        f: { fx: [stat(MORALE, -4)], msg: ['婉拒之后，你发现市场上的位置越来越少。', '你开始重新考虑那份邀约。'], next: 'grinder-matchfixing-desperate' } },
    ],
  },
  {
    id: 'grinder-matchfixing-desperate', title: '绝望诱惑', period: 'NORMAL', conds: [done('grinder-last-shot')],
    desc: '你面临退役，手头拮据。有人递来一张名片：「一场比赛，够你两年的工资。」',
    options: [
      { id: 'refuse-fix', label: '拒绝', chance: 0.75,
        s: { fx: [stat(MORALE, 10), flag('REFUSED_FIX', '拒绝假赛', 'ACHIEVEMENT')], msg: ['你把名片还了回去。', '穷，但不能脏。'], next: 'grinder-z-training-day' },
        f: { fx: [stat(STRESS, 10)], msg: ['你拒绝得不够干脆，对方记住了你。', '之后几周，总有人在看台上盯着你。'], next: 'grinder-z-training-day' } },
      { id: 'hear-offer', label: '听他说完', chance: 0.4,
        s: { fx: [wl('matchfixing'), stat(MORALE, -6), stat(STRESS, 14)], msg: ['你听完了那个数字。', '它够你付两年房租，也够你毁掉十年名声。'], next: null },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你听完后拒绝了，但那笔数字挥之不去。', '你花了很久才把它忘掉。'], next: 'grinder-z-training-day' } },
    ],
  },
  // ============ 风味日常（可重复） ============
  {
    id: 'grinder-z-training-day', title: '日常训练', period: 'NORMAL', conds: [], repeatable: true,
    desc: '磨砺线的日常：早上热身，上午训练赛，下午专项，晚上复盘。',
    options: [
      { id: 'do-it-all', label: '完成全部计划', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 1), stat(MORALE, 4)], msg: ['今天的训练计划全部完成。', '这样的日子你已经过了好几年。'], next: 'grinder-z-faceit-night' },
        f: { fx: [stat(ENERGY, -4)], msg: ['计划完成度七成。', '你决定明天补上。'], next: 'grinder-z-faceit-night' } },
      { id: 'extra-grind', label: '加练到深夜', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.005 }],
        s: { fx: [attr(AIM, 1), stat(ENERGY, -6)], msg: ['加练让你又往前挪了一点。', '一点一点，就是磨砺的意义。'], next: 'grinder-z-faceit-night' },
        f: { fx: [stat(ENERGY, -10)], msg: ['加练过头，第二天训练赛状态下滑。', '你学会了细水长流。'], next: 'grinder-z-faceit-night' } },
    ],
  },
  {
    id: 'grinder-z-faceit-night', title: '平台之夜', period: 'NORMAL', conds: [], repeatable: true,
    desc: '晚上没事，你打开平台打排位。这一打，可能又是一整夜。',
    options: [
      { id: 'queue-some', label: '打几把就下', chance: 0.65,
        s: { fx: [stat(MORALE, 4), stat(ENERGY, -2)], msg: ['你打了几把，赢了就收手。', '自律让明天的训练更轻松。'], next: 'grinder-z-team-chat' },
        f: { fx: [stat(ENERGY, -6)], msg: ['「最后一把」说了四次。', '凌晨两点你才关电脑。'], next: 'grinder-z-team-chat' } },
      { id: 'coach-friends', label: '带朋友上分', chance: 0.6,
        s: { fx: [stat(MORALE, 6), stat(ENERGY, -4)], msg: ['你带朋友上了个段位。', '朋友谢了又谢，你心情不错。'], next: 'grinder-z-team-chat' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['朋友菜得让你上头。', '你差点说出伤人的话。'], next: 'grinder-z-team-chat' } },
    ],
  },
  {
    id: 'grinder-z-team-chat', title: '队内闲聊', period: 'NORMAL', conds: [], repeatable: true,
    desc: '训练结束，大家在群里聊得热火朝天：谁家的外卖好吃，谁又开了新店。',
    options: [
      { id: 'chat-along', label: '一起聊', chance: 0.7,
        s: { fx: [stat(TEAM_CONFLICT, -2), stat(MORALE, 5)], msg: ['你加入了外卖话题。', '群里气氛很轻松。'], next: 'grinder-z-training-day' },
        f: { fx: [stat(STRESS, 3)], msg: ['你插了句话，没人接。', '你默默关掉了群聊。'], next: 'grinder-z-training-day' } },
      { id: 'early-rest', label: '早点休息', chance: 0.65,
        s: { fx: [stat(ENERGY, 6)], msg: ['你选择早点睡。', '第二天的你精神饱满。'], next: 'grinder-z-training-day' },
        f: { fx: [stat(ENERGY, 2)], msg: ['躺下后又刷了会儿手机。', '效果打了一半折扣。'], next: 'grinder-z-training-day' } },
    ],
  },
];
