/**
 * prodigy 世界线内容（天才线）。
 * 入口为既有 prodigy-first-lan；本文件内容 gated 在 done(prodigy-first-lan) 之后。
 */
import {
  attr, stat, flag, rmFlag, wl, transfer, role, trophy, cstat,
  done, hasFlag, age, statCond, attrCond, ANY, ALL, NONE, gm,
  MORALE, ENERGY, BALANCE, STRESS, RATING2,
  AIM, GAME_SENSE, LEADERSHIP, CLUTCH, CONSISTENCY, TEAM_CONFLICT,
} from './helpers.js';

const GATE = done('prodigy-first-lan');

export default [
  // ============ 主线：光环与压力 ============
  {
    id: 'prodigy-hype-check', title: '光环初显', period: 'NORMAL', conds: [GATE],
    desc: '你的首秀录像被各大媒体转载。「下一个天才」的标题开始出现在你名字旁边。',
    options: [
      { id: 'soak-hype', label: '享受光环', chance: 0.6,
        s: { fx: [stat(MORALE, 12), flag('HYPE_RISING', '热度上升', 'CAREER')], msg: ['你开始习惯被镜头对着的感觉。', '但光环下的每一步都被放大。'], next: 'prodigy-media-darling' },
        f: { fx: [stat(STRESS, 8)], msg: ['享受之后是更大的期待。', '你有点被「天才」两个字压得喘不过气。'], next: 'prodigy-media-darling' } },
      { id: 'stay-cool', label: '保持冷静', chance: 0.7,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 6)], msg: ['你说自己只是运气好。', '这份谦逊让不少老玩家对你改观。'], next: 'prodigy-media-darling' },
        f: { fx: [stat(MORALE, -4)], msg: ['你的冷静被解读成「装」。', '舆论开始等着看你翻车。'], next: 'prodigy-media-darling' } },
    ],
  },
  {
    id: 'prodigy-media-darling', title: '媒体宠儿', period: 'NORMAL', conds: [done('prodigy-hype-check')],
    desc: '采访邀约排到了下个月。记者们的问题从比赛问到你的早餐吃什么。',
    options: [
      { id: 'give-interviews', label: '配合采访', chance: 0.6,
        s: { fx: [stat(MORALE, 8), flag('MEDIA_FAV', '媒体宠儿', 'CAREER')], msg: ['你的采访都很配合，报道很正面。', '但训练时间被采访悄悄吃掉。'], next: 'prodigy-stream-explosion' },
        f: { fx: [stat(STRESS, 10), stat(ENERGY, -6)], msg: ['连续采访让你疲惫，状态下滑。', '媒体开始质疑你的专注度。'], next: 'prodigy-stream-explosion' } },
      { id: 'limit-media', label: '限制采访次数', chance: 0.65,
        s: { fx: [stat(ENERGY, 6)], msg: ['你把采访控制在每周一次。', '媒体觉得你「有架子」，但训练没落下。'], next: 'prodigy-stream-explosion' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['拒绝采访让公关部很为难。', '俱乐部开始催你「配合工作」。'], next: 'prodigy-stream-explosion' } },
    ],
  },
  {
    id: 'prodigy-stream-explosion', title: '直播爆火', period: 'NORMAL', conds: [done('prodigy-media-darling')],
    desc: '你的一场直播冲上平台热搜：一次匪夷所思的残局操作被反复播放。',
    options: [
      { id: 'ride-wave', label: '趁热开播', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 2000), stat(MORALE, 8)], msg: ['你连播一周，订阅暴涨。', '钱来了，训练时间被压缩了。'], next: 'prodigy-skill-ego' },
        f: { fx: [stat(ENERGY, -10), stat(STRESS, 6)], msg: ['高强度直播让你身体报警。', '训练赛里你打出了直播后遗症。'], next: 'prodigy-skill-ego' } },
      { id: 'stay-focused', label: '专注训练', chance: 0.65,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你没接住这波热度。', '但训练状态保持得很好。'], next: 'prodigy-skill-ego' },
        f: { fx: [stat(MORALE, -4)], msg: ['「错过热度」让你有点懊恼。', '你安慰自己：实力才是流量。'], next: 'prodigy-skill-ego' } },
    ],
  },
  {
    id: 'prodigy-skill-ego', title: '天才自负', period: 'NORMAL', conds: [done('prodigy-stream-explosion')],
    desc: '训练赛里你开始不按战术打。「这种局，靠枪法就够了」——你越来越常这么想。',
    options: [
      { id: 'check-ego', label: '收敛个人英雄主义', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(TEAM_CONFLICT, -3)], msg: ['你重新按战术打了几场。', '队伍配合回来了，你的数据也没掉。'], next: 'prodigy-coach-grounding' },
        f: { fx: [stat(STRESS, 6)], msg: ['你嘴上说收敛，枪一热又上头。', '队友开始抱怨你的「自由发挥」。'], next: 'prodigy-coach-grounding' } },
      { id: 'trust-guns', label: '相信枪法为王', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 8)], msg: ['你的个人数据确实好看。', '但教练看你的眼神越来越沉。'], next: 'prodigy-coach-grounding' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(MORALE, -4)], msg: ['你有一场白给输了比赛。', '「天才」这个标签第一次压住了你。'], next: 'prodigy-coach-grounding' } },
    ],
  },
  {
    id: 'prodigy-coach-grounding', title: '教练泼冷水', period: 'NORMAL', conds: [done('prodigy-skill-ego')],
    desc: '教练把你叫到办公室：「天才我见多了，绝大多数连一年都撑不过去。」',
    options: [
      { id: 'prove-him', label: '用表现证明', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你把这句话当成燃料。', '接下来一个月，你是队里最稳的。'], next: 'prodigy-rival-duel' },
        f: { fx: [stat(MORALE, -8), stat(STRESS, 8)], msg: ['教练的话让你焦虑到失眠。', '你越想证明，发挥越差。'], next: 'prodigy-rival-duel' } },
      { id: 'ask-detail', label: '追问原因', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你问他为什么这么说。', '他讲了三个陨落天才的故事。'], next: 'prodigy-rival-duel' },
        f: { fx: [stat(STRESS, 8)], msg: ['教练没细说，只说了句「你自己想」。', '这句话你琢磨了一整晚。'], next: 'prodigy-rival-duel' } },
    ],
  },
  {
    id: 'prodigy-rival-duel', title: '宿命对决', period: 'NORMAL', conds: [done('prodigy-coach-grounding')],
    desc: '圈里有个和你同龄的选手，也被称为「天才」。媒体开始炒作你们的对决。',
    options: [
      { id: 'accept-duel', label: '接下对决', chance: 0.6, mods: [{ attribute: CLUTCH, perPoint: 0.008 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 10)], msg: ['你和他正面对决，赢了。', '媒体标题：天才之争，他赢了第一回合。'], next: 'prodigy-rival-lose' },
        f: { fx: [stat(STRESS, 12)], msg: ['你输了，被反复比较。', '「另一个天才」的标题开始出现在你身上。'], next: 'prodigy-rival-lose' } },
      { id: 'duck-duel', label: '回避炒作', chance: 0.7,
        s: { fx: [stat(STRESS, -6)], msg: ['你说对决只是媒体的游戏。', '避开舆论，你专注自己的比赛。'], next: 'prodigy-rival-lose' },
        f: { fx: [stat(MORALE, -4)], msg: ['回避被解读成怯战。', '媒体开始单方面替你认输。'], next: 'prodigy-rival-lose' } },
    ],
  },
  {
    id: 'prodigy-rival-lose', title: '输给宿敌', period: 'NORMAL', conds: [done('prodigy-rival-duel')],
    desc: '你们在正式比赛相遇。你打出了生涯罕见的糟糕表现，他的队伍赢了。',
    options: [
      { id: 'study-loss', label: '复盘这场失败', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 6)], msg: ['你发现他不是枪法赢的你。', '是节奏和心态。'], next: 'prodigy-comeback-win' },
        f: { fx: [stat(STRESS, 10)], msg: ['你把失败归咎于运气。', '同一类失误在下一次比赛又出现了。'], next: 'prodigy-comeback-win' } },
      { id: 'vent-tilt', label: '发泄情绪', chance: 0.5,
        s: { fx: [stat(STRESS, -4), stat(TEAM_CONFLICT, 2)], msg: ['你摔了耳机，第二天就道歉了。', '情绪发泄出来，反而没那么堵了。'], next: 'prodigy-comeback-win' },
        f: { fx: [stat(TEAM_CONFLICT, 5), stat(STRESS, 8)], msg: ['你的脾气让队友开始疏远你。', '「天才的脾气」成了队内标签。'], next: 'prodigy-comeback-win' } },
    ],
  },
  {
    id: 'prodigy-comeback-win', title: '复仇', period: 'NORMAL', conds: [done('prodigy-rival-lose')],
    desc: '一个月后，你们再次相遇。这一次，你带着复盘笔记上场。',
    options: [
      { id: 'execute-plan', label: '按计划复仇', chance: 0.6, mods: [{ attribute: GAME_SENSE, perPoint: 0.009 }],
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 12), cstat('TOTAL_KILLS', 40)], msg: ['你按计划打赢了。', '他赛后主动和你握手，说了句「不错」。'], next: 'prodigy-team-envy' },
        f: { fx: [stat(STRESS, 12)], msg: ['计划执行到一半被打乱。', '你又输了。'], next: 'prodigy-team-envy' } },
      { id: 'gun-duel', label: '用枪法正名', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 12)], msg: ['你和他对位三次，全赢。', '舆论风向终于转了。'], next: 'prodigy-team-envy' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['对位三次输三次。', '「天才陨落」的标题开始出现。'], next: 'prodigy-team-envy' } },
    ],
  },
  {
    id: 'prodigy-team-envy', title: '队内嫉妒', period: 'NORMAL', conds: [done('prodigy-comeback-win')],
    desc: '你的光环越来越亮，队里有人开始阴阳怪气：「天才不用训练，闭着眼睛都能赢。」',
    options: [
      { id: 'downplay-self', label: '主动低调', chance: 0.65,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 4)], msg: ['你开始把功劳分给队友。', '嫉妒的声音小了一些。'], next: 'prodigy-ally' },
        f: { fx: [stat(STRESS, 8)], msg: ['你的低调被当成虚伪。', '阴阳怪气变成了当面嘲讽。'], next: 'prodigy-ally' } },
      { id: 'confront-envy', label: '当面挑明', chance: 0.5,
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -3), stat(MORALE, 8)], msg: ['你把话挑明了：我不欠你们任何人。', '说完之后，反而没人再阴阳了。'], next: 'prodigy-ally' },
        f: { fx: [stat(TEAM_CONFLICT, 6), stat(STRESS, 8)], msg: ['挑明变成了撕破脸。', '更衣室分裂成两派。'], next: 'prodigy-ally' } },
    ],
  },
  {
    id: 'prodigy-ally', title: '拉拢队友', period: 'NORMAL', conds: [done('prodigy-team-envy')],
    desc: '你意识到单靠自己是走不远的。你决定主动和队友建立关系。',
    options: [
      { id: 'small-gestures', label: '从小事做起', chance: 0.7,
        s: { fx: [stat(TEAM_CONFLICT, -5), stat(MORALE, 8), flag('TEAM_BOND', '队内团结', 'CAREER')], msg: ['你给队友带早餐、帮忙复盘。', '关系一点点热了起来。'], next: 'prodigy-first-mvp' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['你的示好被当成别有用心。', '「天才突然对我好，肯定有求于我。」'], next: 'prodigy-first-mvp' } },
      { id: 'share-credit', label: '赛后主动分功', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -4)], msg: ['赢球后你总是先夸队友。', '有队友开始真心实意地帮你补位。'], next: 'prodigy-first-mvp' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['分功显得刻意，队友不太买账。', '但至少关系没再恶化。'], next: 'prodigy-first-mvp' } },
    ],
  },
  {
    id: 'prodigy-first-mvp', title: '首个MVP', period: 'NORMAL', conds: [done('prodigy-ally')],
    desc: '你在一场大赛中拿下 MVP。颁奖时灯光打在你身上，你听见全场的欢呼。',
    options: [
      { id: 'grab-trophy', label: '享受这一刻', chance: 0.65,
        s: { fx: [trophy('MVP', 1), stat(MORALE, 14)], msg: ['你举起奖杯，全场欢呼。', '「天才」终于有了第一个证明。'], next: 'prodigy-pressure-solo' },
        f: { fx: [stat(STRESS, 8)], msg: ['拿下 MVP 后，你开始害怕配不上它。', '「天才陨落」的剧本似乎离你不远。'], next: 'prodigy-pressure-solo' } },
      { id: 'share-mvp', label: '感谢团队', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['你在获奖感言里感谢了所有人。', '队里的气氛前所未有的好。'], next: 'prodigy-pressure-solo' },
        f: { fx: [stat(MORALE, -4)], msg: ['你的感谢词太官方，显得疏远。', '有人调侃：天才就是会说话。'], next: 'prodigy-pressure-solo' } },
    ],
  },
  {
    id: 'prodigy-pressure-solo', title: '单核压力', period: 'NORMAL', conds: [done('prodigy-first-mvp')],
    desc: '队伍开始围绕你打战术。「把球给我」变成了「把资源给我」。输赢都压在你肩上。',
    options: [
      { id: 'carry-role', label: '接住这份责任', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 10), stat(STRESS, 6)], msg: ['你确实打出了核心的价值。', '但你知道，这样的日子不会永远好过。'], next: 'prodigy-support-ask' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['单核压力让你状态起伏剧烈。', '输的时候，骂声全冲着你来。'], next: 'prodigy-support-ask' } },
      { id: 'share-load', label: '要求分担火力', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -2)], msg: ['你建议教练分散资源。', '队友们打了几个不错的小局。'], next: 'prodigy-support-ask' },
        f: { fx: [stat(TEAM_CONFLICT, 3)], msg: ['「让天才当核心」的呼声压过了你。', '你的建议没人听。'], next: 'prodigy-support-ask' } },
    ],
  },
  {
    id: 'prodigy-support-ask', title: '求援队友', period: 'NORMAL', conds: [done('prodigy-pressure-solo')],
    desc: '你主动找队友谈心，承认自己一个人扛不住。这是你第一次示弱。',
    options: [
      { id: 'open-up', label: '坦诚示弱', chance: 0.65,
        s: { fx: [stat(TEAM_CONFLICT, -5), stat(MORALE, 10), flag('REAL_TEAM', '真队友', 'CAREER')], msg: ['你说了实话：我需要你们。', '那天晚上，队伍罕见地一条心。'], next: 'prodigy-igc-offer' },
        f: { fx: [stat(STRESS, 8)], msg: ['你的示弱被队友视为「天才的软弱」。', '你后悔说了那些话。'], next: 'prodigy-igc-offer' } },
      { id: 'tough-it', label: '继续硬撑', chance: 0.55,
        s: { fx: [attr(CONSISTENCY, 2), stat(STRESS, 8)], msg: ['你选择自己消化压力。', '短期内状态还行，但你知道这是透支。'], next: 'prodigy-igc-offer' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['硬撑的结果是某场比赛你彻底崩了。', '「天才也会有今天」的标题满天飞。'], next: 'prodigy-igc-offer' } },
    ],
  },
  {
    id: 'prodigy-igc-offer', title: '指挥邀约', period: 'NORMAL', conds: [done('prodigy-support-ask')],
    desc: '有队伍想挖你当指挥。他们说你的「比赛阅读」比你的枪法更值钱。',
    options: [
      { id: 'try-igc', label: '转型指挥', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), role('IGL'), stat(MORALE, 8)], msg: ['你开始学指挥，读比赛的速度比你想象得快。', '「天才枪手转型大脑」的报道很轰动。'], next: 'prodigy-focus-choice' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['指挥让你两头顾不上。', '枪法下滑，指挥也混乱。'], next: 'prodigy-focus-choice' } },
      { id: 'stay-awper', label: '专心打枪', chance: 0.65,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你拒绝了转型，专心打磨枪法。', '你的定位越来越清晰。'], next: 'prodigy-focus-choice' },
        f: { fx: [stat(MORALE, -4)], msg: ['拒绝后你偶尔会想「如果」。', '「指挥天才」的故事停留在别人的嘴里。'], next: 'prodigy-focus-choice' } },
    ],
  },
  {
    id: 'prodigy-focus-choice', title: '专注抉择', period: 'NORMAL', conds: [done('prodigy-igc-offer')],
    desc: '选择多了反而更难：直播、代言、指挥、个人训练，每条路都在招手。',
    options: [
      { id: 'one-path', label: '选定一条路专注', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 3), stat(STRESS, -6)], msg: ['你砍掉了杂项，专注最擅长的。', '状态肉眼可见地稳了。'], next: 'prodigy-form-peak' },
        f: { fx: [stat(STRESS, 10)], msg: ['你选定了，但忍不住回头。', '专注成了三天打鱼两天晒网。'], next: 'prodigy-form-peak' } },
      { id: 'multi-track', label: '多线发展', chance: 0.55,
        s: { fx: [cstat('CAREER_EARNINGS', 1500), stat(MORALE, 8), stat(STRESS, 6)], msg: ['你什么都接，收入很可观。', '但训练时间被摊薄了。'], next: 'prodigy-form-peak' },
        f: { fx: [stat(ENERGY, -12), stat(STRESS, 8)], msg: ['多线作战让你疲惫不堪。', '比赛状态开始报警。'], next: 'prodigy-form-peak' } },
    ],
  },
  {
    id: 'prodigy-form-peak', title: '状态巅峰', period: 'NORMAL', conds: [done('prodigy-focus-choice')],
    desc: '你进入了职业生涯状态最好的时期：对枪自信、决策果断、运气也站在你这边。',
    options: [
      { id: 'ride-peak', label: '趁巅峰多打比赛', chance: 0.6,
        s: { fx: [attr(AIM, 3), cstat('TOTAL_KILLS', 55), stat(MORALE, 12)], msg: ['巅峰期的你打出了统治级数据。', '媒体开始拿你和传奇选手比较。'], next: 'prodigy-form-crash' },
        f: { fx: [stat(ENERGY, -8)], msg: ['赛程太密，巅峰没能完全兑现。', '你开始担心巅峰会过去。'], next: 'prodigy-form-crash' } },
      { id: 'protect-peak', label: '保护状态', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 3), stat(ENERGY, 6)], msg: ['你主动调整赛程，保护状态。', '「知道什么时候收手」也是一种天才。'], next: 'prodigy-form-crash' },
        f: { fx: [stat(MORALE, -4)], msg: ['保护过头变成了保守。', '你的锐气少了一点。'], next: 'prodigy-form-crash' } },
    ],
  },
  {
    id: 'prodigy-form-crash', title: '状态崩塌', period: 'NORMAL', conds: [done('prodigy-form-peak')],
    desc: '毫无征兆地，你的状态跌入谷底：训练赛空枪、比赛梦游、数据垫底。',
    options: [
      { id: 'find-cause', label: '找原因', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你发现是调整期和睡眠问题叠加。', '找到原因后，情况开始好转。'], next: 'prodigy-coach-rescue' },
        f: { fx: [stat(STRESS, 10)], msg: ['你找不出原因，越找越慌。', '「天才陨落」的报道开始铺天盖地。'], next: 'prodigy-coach-rescue' } },
      { id: 'grind-out', label: '靠训练硬扛', chance: 0.5, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 4), stat(ENERGY, -8)], msg: ['你靠加练熬了过来。', '但代价是身心俱疲。'], next: 'prodigy-coach-rescue' },
        f: { fx: [stat(ENERGY, -14), stat(STRESS, 10)], msg: ['硬扛让谷底更深了。', '你第一次觉得「天才」是诅咒。'], next: 'prodigy-coach-rescue' } },
    ],
  },
  {
    id: 'prodigy-coach-rescue', title: '教练救命', period: 'NORMAL', conds: [done('prodigy-form-crash')],
    desc: '教练把你从训练室拽出来，带你去吃了顿烧烤。「你再这样练，就废了。」',
    options: [
      { id: 'listen-coach', label: '听教练的', chance: 0.65,
        s: { fx: [stat(ENERGY, 12), stat(STRESS, -8)], msg: ['你休息了两天，吃烧烤，散步。', '回来时，状态回来了一半。'], next: 'prodigy-injury-fear' },
        f: { fx: [stat(STRESS, 8)], msg: ['你嘴上答应，晚上又回去练了。', '教练看你油盐不进，叹了口气。'], next: 'prodigy-injury-fear' } },
      { id: 'trust-own', label: '按自己的节奏来', chance: 0.55,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你按自己的方法调整了一周。', '意外地，状态恢复得不错。'], next: 'prodigy-injury-fear' },
        f: { fx: [stat(STRESS, 10), stat(ENERGY, -6)], msg: ['你自己的方法没见效。', '教练的烧烤夜宵白请了。'], next: 'prodigy-injury-fear' } },
    ],
  },
  {
    id: 'prodigy-injury-fear', title: '伤病恐惧', period: 'NORMAL', conds: [done('prodigy-coach-rescue')],
    desc: '你的手腕开始频繁酸痛。队医说：「你的训练量对职业选手来说太大了。」',
    options: [
      { id: 'cut-volume', label: '减少训练量', chance: 0.65,
        s: { fx: [stat(ENERGY, 10), stat(STRESS, -6), flag('HAND_HEALTHY', '手腕无恙', 'CAREER')], msg: ['你开始科学安排训练量。', '手腕不疼了，状态也没掉。'], next: 'prodigy-major-run2' },
        f: { fx: [stat(STRESS, 8)], msg: ['减少训练量让你焦虑。', '你总觉得自己在退步。'], next: 'prodigy-major-run2' } },
      { id: 'push-pain', label: '忍着继续练', chance: 0.45,
        s: { fx: [stat(MORALE, 8), stat(ENERGY, -8)], msg: ['你咬牙撑过了这段魔鬼赛程。', '手腕还在疼，但你赢了比赛。'], next: 'prodigy-major-run2' },
        f: { fx: [stat(STRESS, 12), stat(ENERGY, -12), flag('WRIST_DAMAGE', '手腕劳损', 'MENTAL')], msg: ['你终于撑不住，被强制休养三周。', '复出后，你总觉得手腕不如从前。'], next: 'prodigy-major-run2' } },
    ],
  },
  {
    id: 'prodigy-major-run2', title: '大赛之旅', period: 'FINAL_DECISIVE_MOMENT', conds: [done('prodigy-injury-fear')],
    desc: '你们杀入大赛四强。半决赛的对手是卫冕冠军，全场都期待你「封神」。',
    options: [
      { id: 'peak-show', label: '拿出巅峰状态', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 12)], msg: ['你在半决赛打出了职业生涯代表作。', '「天才」这个词被解说喊了三遍。'], next: 'prodigy-finals-choke' },
        f: { fx: [stat(STRESS, 12)], msg: ['半决赛你发挥平平，差点被淘汰。', '好在队友兜住了。'], next: 'prodigy-finals-choke' } },
      { id: 'team-tactics', label: '靠战术取胜', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 10)], msg: ['你放弃个人表现，专注战术执行。', '半决赛赢了，虽然你没拿到 MVP。'], next: 'prodigy-finals-choke' },
        f: { fx: [stat(STRESS, 8)], msg: ['战术执行被对手破解。', '你们靠个人能力惊险过关。'], next: 'prodigy-finals-choke' } },
    ],
  },
  {
    id: 'prodigy-finals-choke', title: '决赛心魔', period: 'FINAL_DECISIVE_MOMENT', conds: [done('prodigy-major-run2')],
    desc: '决赛 15:14，你又一次站上决胜局。上一次决赛的失误在脑海里反复回放。',
    options: [
      { id: 'calm-breath', label: '深呼吸，相信肌肉记忆', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('MAJOR', 1), stat(MORALE, 15), flag('MAJOR_CHAMP', '大赛冠军', 'ACHIEVEMENT')], msg: ['你按住了心跳，打出关键枪。', '捧杯的那一刻，心魔彻底散去。'], next: 'prodigy-finals-triumph' },
        f: { fx: [stat(STRESS, 16), stat(MORALE, -10)], msg: ['同样的失误再次发生。', '「大赛软脚虾」的帽子扣了下来。'], next: 'prodigy-finals-triumph' } },
      { id: 'overdrive', label: '用愤怒打爆对面', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), trophy('MAJOR', 1), flag('MAJOR_CHAMP', '大赛冠军', 'ACHIEVEMENT')], msg: ['你把怒火对准了对面，打出了爆发。', '捧杯时你面无表情，但手在抖。'], next: 'prodigy-finals-triumph' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['愤怒让你失去判断，连送三局。', '你输掉了最想赢的比赛。'], next: 'prodigy-finals-triumph' } },
    ],
  },
  {
    id: 'prodigy-finals-triumph', title: '决赛封神', period: 'NORMAL', conds: [done('prodigy-finals-choke')],
    desc: '你终于拿到了梦寐以求的冠军。颁奖台上，聚光灯追着你，你听见全场高呼你的 ID。',
    options: [
      { id: 'celebrate', label: '尽情庆祝', chance: 0.7,
        s: { fx: [trophy('MVP', 1), stat(MORALE, 15), cstat('CAREER_EARNINGS', 5000)], msg: ['你把奖杯举过头顶，转了三圈。', '这个画面后来被印在了杂志封面上。'], next: 'prodigy-backlash' },
        f: { fx: [stat(STRESS, 6)], msg: ['庆祝时你有一瞬间恍惚。', '「这一切是真的吗？」'], next: 'prodigy-backlash' } },
      { id: 'stay-humble', label: '保持谦逊', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 10)], msg: ['你在采访里说这只是开始。', '「这个天才有点不一样」的评论很多。'], next: 'prodigy-backlash' },
        f: { fx: [stat(MORALE, -4)], msg: ['过度谦逊让气氛有点尴尬。', '队友调侃你「得了便宜还卖乖」。'], next: 'prodigy-backlash' } },
    ],
  },
  {
    id: 'prodigy-backlash', title: '捧杀反噬', period: 'NORMAL', conds: [done('prodigy-finals-triumph')],
    desc: '夺冠后的吹捧铺天盖地：有人开始说你是「历史最佳候选」。风向变得很快。',
    options: [
      { id: 'resist-flattery', label: '抵抗吹捧', chance: 0.6,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 6)], msg: ['你关掉了吹捧你的帖子。', '「历史最佳」这四个字被你锁进了备忘录。'], next: 'prodigy-haters' },
        f: { fx: [stat(STRESS, 10)], msg: ['你嘴上说不信，却开始反复看那些帖子。', '「最佳候选」开始影响你的心态。'], next: 'prodigy-haters' } },
      { id: 'ride-hype', label: '顺势接受', chance: 0.55,
        s: { fx: [stat(MORALE, 10), flag('HYPE_BACKLASH', '捧杀风险', 'MENTAL')], msg: ['你接受了这个定位，接的活动越来越多。', '但你知道，捧得越高摔得越狠。'], next: 'prodigy-haters' },
        f: { fx: [stat(STRESS, 12)], msg: ['接受吹捧让你开始表演「天才」。', '状态开始为表演让路。'], next: 'prodigy-haters' } },
    ],
  },
  {
    id: 'prodigy-haters', title: '全网黑', period: 'NORMAL', conds: [done('prodigy-backlash')],
    desc: '一次失利后，全网开始清算你的「历史最佳候选」言论。你的每条动态下都是嘲讽。',
    options: [
      { id: 'block-world', label: '卸载社交软件', chance: 0.6,
        s: { fx: [stat(STRESS, -10), stat(MORALE, 4)], msg: ['你卸载了所有社交软件。', '世界安静了，训练也专注了。'], next: 'prodigy-meltdown' },
        f: { fx: [stat(STRESS, 12)], msg: ['你卸载了，但借队友的手机看。', '你控制不住自己。'], next: 'prodigy-meltdown' } },
      { id: 'fight-back', label: '发文回应', chance: 0.5,
        s: { fx: [stat(MORALE, 8), stat(STRESS, -4)], msg: ['你发了一条长文，不卑不亢。', '舆论开始分化，但你站稳了。'], next: 'prodigy-meltdown' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['你的回应被断章取义，火上浇油。', '你第一次体会到百口莫辩。'], next: 'prodigy-meltdown' } },
    ],
  },
  {
    id: 'prodigy-meltdown', title: '心理崩溃', period: 'NORMAL', conds: [done('prodigy-haters')], modes: ['HARDCORE'],
    desc: '深夜，你在训练室盯着屏幕发呆。你突然想不起来自己为什么要打这个游戏。',
    options: [
      { id: 'ask-help', label: '主动寻求帮助', chance: 0.55,
        s: { fx: [stat(MORALE, 6), flag('HELP_ACCEPTED', '接受帮助', 'MENTAL')], msg: ['你第一次约了心理医生。', '哭完之后，你感觉好了一点。'], next: 'prodigy-rebuild' },
        f: { fx: [stat(STRESS, 10)], msg: ['你约了医生，却临阵退缩。', '那份预约单躺在你的抽屉里。'], next: 'prodigy-rebuild' } },
      { id: 'push-through-dark', label: '自己扛过去', chance: 0.45,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 4), stat(STRESS, 8)], msg: ['你靠意志熬过了那段日子。', '但你知道，那层壳已经很薄了。'], next: 'prodigy-rebuild' },
        f: { fx: [stat(STRESS, 16), stat(MORALE, -12), flag('MENTAL_CRISIS', '心理危机', 'MENTAL')], msg: ['你没能扛住，在训练赛中途离开了。', '教练第一次看见你哭。'], next: 'prodigy-rebuild' } },
    ],
  },
  {
    id: 'prodigy-rebuild', title: '重建心态', period: 'NORMAL', conds: [done('prodigy-meltdown')],
    desc: '你决定重新开始：从「做回自己」开始，而不是做回「天才」。',
    options: [
      { id: 'redefine-self', label: '重新定义自己', chance: 0.65,
        s: { fx: [stat(MORALE, 12), stat(STRESS, -8)], msg: ['你不再用天才定义自己。', '你只是一个还在进步的职业选手。'], next: 'prodigy-sports-psych' },
        f: { fx: [stat(STRESS, 8)], msg: ['重建比想象中难。', '「天才」的标签已经长进了皮肤里。'], next: 'prodigy-sports-psych' } },
      { id: 'small-wins', label: '从小目标开始', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 8)], msg: ['你把目标拆成每天的小事。', '完成一个，打一个勾。'], next: 'prodigy-sports-psych' },
        f: { fx: [stat(STRESS, 6)], msg: ['小目标也总是完不成。', '你对自己更失望了。'], next: 'prodigy-sports-psych' } },
    ],
  },
  {
    id: 'prodigy-sports-psych', title: '心理医生', period: 'NORMAL', conds: [done('prodigy-rebuild')],
    desc: '俱乐部的心理医生约你定期见面。你原本觉得这是「弱者的游戏」。',
    options: [
      { id: 'open-sessions', label: '认真对待咨询', chance: 0.65,
        s: { fx: [stat(STRESS, -10), stat(MORALE, 8)], msg: ['几次咨询后，你学会了一些处理情绪的工具。', '你开始觉得这不是弱者的游戏。'], next: 'prodigy-team-change' },
        f: { fx: [stat(STRESS, 6)], msg: ['你应付了事，没把咨询当回事。', '情绪问题还在原地打转。'], next: 'prodigy-team-change' } },
      { id: 'self-methods', label: '用自己的方法', chance: 0.6,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 6)], msg: ['你写日记、跑步、规律作息。', '你的土办法意外地有效。'], next: 'prodigy-team-change' },
        f: { fx: [stat(STRESS, 8)], msg: ['土办法三天打鱼两天晒网。', '心理医生还是那句话：考虑考虑专业帮助。'], next: 'prodigy-team-change' } },
    ],
  },
  {
    id: 'prodigy-team-change', title: '转会风波', period: 'TRANSFER_WINDOW', conds: [done('prodigy-sports-psych')],
    desc: '有豪门开出了天价转会费。俱乐部想留你，但价格足够让所有人动摇。',
    options: [
      { id: 'stay-put2', label: '留下', chance: 0.6,
        s: { fx: [stat(MORALE, 8), flag('LOYAL_STAR', '忠诚明星', 'CAREER')], msg: ['你选择留下。', '俱乐部把你写进了长期计划。'], next: 'prodigy-new-home' },
        f: { fx: [stat(STRESS, 6)], msg: ['留下后，转会传闻还是缠着你。', '「他是不是在等更好的报价？」'], next: 'prodigy-new-home' } },
      { id: 'move-on2', label: '转会豪门', chance: 0.55,
        s: { fx: [transfer('faze'), stat(MORALE, 12)], msg: ['你转会到了豪门。', '新环境、新队友、更高的舞台。'], next: 'prodigy-new-home' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['转会谈判拖了一个月，最后黄了。', '你留在老东家，处境却尴尬了。'], next: 'prodigy-new-home' } },
    ],
  },
  {
    id: 'prodigy-new-home', title: '新队伍', period: 'NORMAL', conds: [done('prodigy-team-change')],
    desc: '新队伍的训练风格和你习惯的完全不同：更严谨、更纪律化。你像重新当了一次新人。',
    options: [
      { id: 'adapt-system', label: '适应新体系', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 8)], msg: ['你放下了天才的身段，重新学体系。', '三个月后，你成了新体系的核心。'], next: 'prodigy-captain-prodigy' },
        f: { fx: [stat(STRESS, 12)], msg: ['新体系和你格格不入。', '你在新队伍的位置开始模糊。'], next: 'prodigy-captain-prodigy' } },
      { id: 'import-style', label: '坚持自己的打法', chance: 0.55,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6), stat(TEAM_CONFLICT, 2)], msg: ['你坚持自己的节奏。', '新教练由着你，但配合始终差一口气。'], next: 'prodigy-captain-prodigy' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(STRESS, 8)], msg: ['「天才不服管」的名声传开了。', '你在新队伍更加孤立。'], next: 'prodigy-captain-prodigy' } },
    ],
  },
  {
    id: 'prodigy-captain-prodigy', title: '天才队长', period: 'NORMAL', conds: [done('prodigy-new-home')],
    desc: '新教练提议让你当队长：「你该学会把天才变成队伍的天才。」',
    options: [
      { id: 'captain-learn', label: '接下队长学习领导', chance: 0.6, mods: [{ attribute: LEADERSHIP, perPoint: 0.009 }],
        s: { fx: [attr(LEADERSHIP, 3), role('IGL'), stat(MORALE, 10)], msg: ['你开始学怎么带人，而不只是带枪。', '队伍的氛围肉眼可见地变了。'], next: 'prodigy-schedule-madness' },
        f: { fx: [stat(STRESS, 12)], msg: ['队长身份让你分心，状态下滑。', '你怀疑自己是不是这块料。'], next: 'prodigy-schedule-madness' } },
      { id: 'decline-captain', label: '专注个人表现', chance: 0.65,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你婉拒了队长，专心打自己的。', '个人数据很漂亮，队伍却缺了点灵魂。'], next: 'prodigy-schedule-madness' },
        f: { fx: [stat(MORALE, -4)], msg: ['婉拒后，教练觉得你「不够格」。', '你在队内的话语权开始下降。'], next: 'prodigy-schedule-madness' } },
    ],
  },
  {
    id: 'prodigy-schedule-madness', title: '赛程地狱', period: 'NORMAL', conds: [done('prodigy-captain-prodigy')],
    desc: '豪门队伍的赛程是地狱模式：每周两赛，外加赞助商活动、媒体日、纪录片拍摄。',
    options: [
      { id: 'manage-load', label: '科学管理体能', chance: 0.6,
        s: { fx: [stat(ENERGY, 10), stat(STRESS, -6)], msg: ['你学会了在缝隙里休息。', '赛程地狱没能榨干你。'], next: 'prodigy-rest-revolt' },
        f: { fx: [stat(ENERGY, -10)], msg: ['你的恢复计划执行得很差。', '两周后你的状态开始报警。'], next: 'prodigy-rest-revolt' } },
      { id: 'say-no', label: '拒绝部分活动', chance: 0.55,
        s: { fx: [stat(ENERGY, 8), stat(TEAM_CONFLICT, -2)], msg: ['你推掉了几个活动。', '俱乐部不太高兴，但你的状态保住了。'], next: 'prodigy-rest-revolt' },
        f: { fx: [stat(MORALE, -6)], msg: ['拒绝活动让你被贴上了「难搞」的标签。', '公关部开始绕着你走。'], next: 'prodigy-rest-revolt' } },
    ],
  },
  {
    id: 'prodigy-rest-revolt', title: '拒绝休息', period: 'NORMAL', conds: [done('prodigy-schedule-madness')],
    desc: '教练强制你休息一周。你半夜爬起来偷偷训练，被抓个正着。',
    options: [
      { id: 'obey-rest', label: '老实休息', chance: 0.65,
        s: { fx: [stat(ENERGY, 14), stat(STRESS, -8)], msg: ['你老实休息了一周。', '回来时你发现状态前所未有的好。'], next: 'prodigy-burnout' },
        f: { fx: [stat(STRESS, 8)], msg: ['休息让你焦虑，你总想「落后」。', '你休息得不踏实。'], next: 'prodigy-burnout' } },
      { id: 'sneak-train', label: '偷偷加练', chance: 0.45,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6), stat(ENERGY, -8)], msg: ['你偷偷练了三天，枪感确实在。', '但教练的眼神说明他什么都知道了。'], next: 'prodigy-burnout' },
        f: { fx: [stat(ENERGY, -12), flag('OVERTRAINED', '训练过度', 'MENTAL')], msg: ['偷偷加练让你身体彻底罢工。', '你被抬进了医务室。'], next: 'prodigy-burnout' } },
    ],
  },
  {
    id: 'prodigy-burnout', title: '天才倦怠', period: 'NORMAL', conds: [done('prodigy-rest-revolt')],
    desc: '你开始对比赛感到厌倦。赢球不再让你兴奋，输球也不再让你难过。',
    options: [
      { id: 'rekindle', label: '找回初心', chance: 0.6,
        s: { fx: [stat(MORALE, 8), flag('FIRE_REKINDLED', '重燃热爱', 'MENTAL')], msg: ['你翻出第一次打比赛的录像。', '那个在网吧打比赛的少年还在。'], next: 'prodigy-coach-talk' },
        f: { fx: [stat(MORALE, -6)], msg: ['你找不回那种感觉了。', '比赛变成了工作，天才变成了机器。'], next: 'prodigy-coach-talk' } },
      { id: 'fake-it', label: '装出热情', chance: 0.55,
        s: { fx: [stat(STRESS, 8), stat(MORALE, 2)], msg: ['你在镜头前继续微笑。', '但深夜的训练室，你盯着屏幕发呆。'], next: 'prodigy-coach-talk' },
        f: { fx: [stat(STRESS, 12)], msg: ['装热情越来越累。', '有队友发现了你的异常。'], next: 'prodigy-coach-talk' } },
    ],
  },
  {
    id: 'prodigy-coach-talk', title: '教练谈心', period: 'NORMAL', conds: [done('prodigy-burnout')],
    desc: '教练约你深夜喝茶。他说他见过太多天才倒在「燃尽」这道坎上。',
    options: [
      { id: 'share-burnout', label: '坦白状态', chance: 0.65,
        s: { fx: [stat(MORALE, 8), stat(STRESS, -6)], msg: ['你说了实话：我有点燃尽了。', '教练没安慰你，只说了句「正常」。'], next: 'prodigy-second-wind' },
        f: { fx: [stat(STRESS, 8)], msg: ['你只说「还行」，教练没有追问。', '但那份孤独感更重了。'], next: 'prodigy-second-wind' } },
      { id: 'ask-him', label: '问他怎么扛过来的', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 8)], msg: ['教练讲了自己当选手时的低谷。', '「天才也会累，但天才也知道怎么休息。」'], next: 'prodigy-second-wind' },
        f: { fx: [stat(STRESS, 6)], msg: ['教练讲了，但你只听了开头。', '你还在自己的情绪里打转。'], next: 'prodigy-second-wind' } },
    ],
  },
  {
    id: 'prodigy-second-wind', title: '第二春', period: 'NORMAL', conds: [done('prodigy-coach-talk')],
    desc: '调整了三个月后，你打出了夺冠以来的最佳状态。有人说你「找回自己了」。',
    options: [
      { id: 'protect-fire', label: '保护好这股劲', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你学会了在状态好时留余力。', '第二春不再是昙花一现。'], next: 'prodigy-sponsor-war' },
        f: { fx: [stat(STRESS, 6)], msg: ['你太怕第二春结束，反而又紧张了。', '状态好景不长。'], next: 'prodigy-sponsor-war' } },
      { id: 'seize-moment', label: '趁状态全开', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('TOTAL_KILLS', 50), stat(MORALE, 12)], msg: ['你趁状态好打出了统治数据。', '「天才回来了」的标题再次刷屏。'], next: 'prodigy-sponsor-war' },
        f: { fx: [stat(ENERGY, -8)], msg: ['太用力，第二春提前结束。', '你又在谷底待了两周。'], next: 'prodigy-sponsor-war' } },
    ],
  },
  {
    id: 'prodigy-sponsor-war', title: '赞助商大战', period: 'NORMAL', conds: [done('prodigy-second-wind')],
    desc: '两家大品牌同时找你代言，条件互相冲突：一家要求你独享外设，另一家要求「开放合作」。',
    options: [
      { id: 'pick-one', label: '选条件优厚的', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 8000), stat(MORALE, 8)], msg: ['你选了条件更好的那家。', '另一家扬言「以后别合作」。'], next: 'prodigy-endorsement-trap' },
        f: { fx: [stat(STRESS, 8)], msg: ['选完之后你开始担心得罪人。', '品牌圈的水比你想的深。'], next: 'prodigy-endorsement-trap' } },
      { id: 'stay-neutral', label: '都不签', chance: 0.55,
        s: { fx: [stat(MORALE, 6), stat(STRESS, -4)], msg: ['你选择都不签，保持中立。', '少赚了钱，但清净。'], next: 'prodigy-endorsement-trap' },
        f: { fx: [stat(MORALE, -4)], msg: ['拒绝两家让品牌圈觉得你「难谈」。', '之后的代言邀约明显变少。'], next: 'prodigy-endorsement-trap' } },
    ],
  },
  {
    id: 'prodigy-endorsement-trap', title: '代言陷阱', period: 'NORMAL', conds: [done('prodigy-sponsor-war')],
    desc: '一份代言合同里夹着「负面舆情兜底条款」：你出丑闻，代言费要翻倍退回。',
    options: [
      { id: 'read-fineprint', label: '仔细读条款', chance: 0.65,
        s: { fx: [cstat('CAREER_EARNINGS', 5000), stat(STRESS, -6), flag('SHARP_CONTRACT', '合同专家', 'CAREER')], msg: ['你发现了那个条款，让律师改了。', '品牌方夸你「专业」。'], next: 'prodigy-fan-club' },
        f: { fx: [stat(STRESS, 8)], msg: ['你读出了问题，但对方不松口。', '你最后拒签了这份合同。'], next: 'prodigy-fan-club' } },
      { id: 'sign-quick', label: '大笔一挥就签', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 8000), stat(MORALE, 8)], msg: ['钱到手很快。', '但那笔「兜底」的代价，你还没机会意识到。'], next: 'prodigy-fan-club' },
        f: { fx: [stat(STRESS, 10)], msg: ['签完你才仔细看条款，冷汗直冒。', '你开始祈祷别出事。'], next: 'prodigy-fan-club' } },
    ],
  },
  {
    id: 'prodigy-fan-club', title: '粉丝狂热', period: 'NORMAL', conds: [done('prodigy-endorsement-trap')],
    desc: '你的后援会越来越庞大。有人在你酒店楼下蹲守，有人给你寄了奇怪的礼物。',
    options: [
      { id: 'appreciate-fans', label: '珍惜粉丝', chance: 0.7,
        s: { fx: [stat(MORALE, 8)], msg: ['你偶尔在直播里读粉丝来信。', '大部分粉丝是真的在支持你。'], next: 'prodigy-privacy-loss' },
        f: { fx: [stat(STRESS, 6)], msg: ['你开始害怕回应用户，怕说错话。', '热情让你压力山大。'], next: 'prodigy-privacy-loss' } },
      { id: 'set-boundaries', label: '划清界限', chance: 0.65,
        s: { fx: [stat(STRESS, -6)], msg: ['你让团队发布了粉丝守则。', '过界的私信被统一处理。'], next: 'prodigy-privacy-loss' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['划界限的声明让部分粉丝寒心。', '你掉了些关注，但生活清净了。'], next: 'prodigy-privacy-loss' } },
    ],
  },
  {
    id: 'prodigy-privacy-loss', title: '隐私消失', period: 'NORMAL', conds: [done('prodigy-fan-club')],
    desc: '有人扒出了你的家庭住址，甚至拍到了你父母家的小区。',
    options: [
      { id: 'security-up', label: '加强安保', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -2000), stat(STRESS, -6)], msg: ['你换了住处，加了安保。', '家人那边也做了安排。'], next: 'prodigy-fake-friends' },
        f: { fx: [stat(STRESS, 10)], msg: ['安保开销让你心疼。', '但你更心疼父母的安宁。'], next: 'prodigy-fake-friends' } },
      { id: 'ignore-it', label: '不理会', chance: 0.55,
        s: { fx: [stat(MORALE, 4)], msg: ['你觉得这是「成名的代价」。', '直到有一次真的被堵在了门口。'], next: 'prodigy-fake-friends' },
        f: { fx: [stat(STRESS, 14)], msg: ['被堵门那次你报了警。', '从那以后你才开始认真对待隐私。'], next: 'prodigy-fake-friends' } },
    ],
  },
  {
    id: 'prodigy-fake-friends', title: '假朋友', period: 'NORMAL', conds: [done('prodigy-privacy-loss')],
    desc: '成名后，身边突然多了很多「朋友」。有人约你投资，有人想蹭你的流量。',
    options: [
      { id: 'filter-people', label: '筛选身边的人', chance: 0.65,
        s: { fx: [stat(MORALE, 6), stat(TEAM_CONFLICT, -2)], msg: ['你开始分辨谁是真朋友。', '疏远了一些人，世界安静了。'], next: 'prodigy-true-ally' },
        f: { fx: [stat(STRESS, 8)], msg: ['你谁也不信了，连真朋友也疏远了。', '孤独感开始包围你。'], next: 'prodigy-true-ally' } },
      { id: 'enjoy-social', label: '享受人脉', chance: 0.55,
        s: { fx: [cstat('CAREER_EARNINGS', 2000), stat(MORALE, 8)], msg: ['你的社交圈越来越大。', '有人引荐你认识了不少圈内大佬。'], next: 'prodigy-true-ally' },
        f: { fx: [stat(STRESS, 10), cstat('CAREER_EARNINGS', -1000)], msg: ['你被忽悠投了一笔亏钱的「项目」。', '那顿饭教会了你一课。'], next: 'prodigy-true-ally' } },
    ],
  },
  {
    id: 'prodigy-true-ally', title: '真朋友', period: 'NORMAL', conds: [done('prodigy-fake-friends')],
    desc: '在你最低谷的那段日子，有个老朋友一直陪着你。他现在约你吃饭，想聊聊未来。',
    options: [
      { id: 'cherish-ally', label: '珍惜这段关系', chance: 0.7,
        s: { fx: [stat(MORALE, 10), flag('TRUE_FRIEND', '真朋友', 'CAREER')], msg: ['你们聊到深夜，他说你变了。', '「变强了，也变累了。」'], next: 'prodigy-comeback-injury' },
        f: { fx: [stat(STRESS, 6)], msg: ['你话太少，那顿饭有点沉默。', '但你知道，他在。'], next: 'prodigy-comeback-injury' } },
      { id: 'invest-together', label: '合伙做点事', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -3000), stat(MORALE, 8)], msg: ['你们合伙开了家小电竞馆。', '打职业之外，你有了第二份事业。'], next: 'prodigy-comeback-injury' },
        f: { fx: [cstat('CAREER_EARNINGS', -3000), stat(STRESS, 8)], msg: ['电竞馆生意平平。', '但你和老友的关系反而更铁了。'], next: 'prodigy-comeback-injury' } },
    ],
  },
  // ============ 极端事件 ============
  {
    id: 'prodigy-sabotage', title: '被针对狙击', period: 'NORMAL', conds: [done('prodigy-true-ally')],
    desc: '你发现有人在训练赛里「故意演你」：该补的枪不补，该报的点不报。',
    options: [
      { id: 'expose-sabotage', label: '当场拆穿', chance: 0.55,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['你指出了那个人的问题，他哑口无言。', '从那以后没人再演你。'], next: 'prodigy-sensei' },
        f: { fx: [stat(TEAM_CONFLICT, 5), stat(STRESS, 10)], msg: ['拆穿后他倒打一耙，说你「玻璃心」。', '你在这支队伍的日子更难了。'], next: 'prodigy-sensei' } },
      { id: 'play-around', label: '自己扛住', chance: 0.6,
        s: { fx: [attr(CLUTCH, 2), stat(MORALE, 4)], msg: ['你选择靠自己赢。', '你确实赢了，但那份委屈积在心里。'], next: 'prodigy-sensei' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['靠自己没能扛住，你输了几场。', '「天才被演」的流言开始传播。'], next: 'prodigy-sensei' } },
    ],
  },
  {
    id: 'prodigy-sensei', title: '亦师亦友', period: 'NORMAL', conds: [done('prodigy-sabotage')],
    desc: '一位传奇选手退役后开始带新人。他看了你的比赛，主动加了你。',
    options: [
      { id: 'learn-sensei', label: '拜他为师', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 3), attr(CLUTCH, 2), stat(MORALE, 10)], msg: ['他每周给你开一次小灶。', '你从他的复盘里看到了另一个世界。'], next: 'prodigy-bet' },
        f: { fx: [stat(STRESS, 6)], msg: ['你不好意思开口拜师。', '但他的建议你每条都记了下来。'], next: 'prodigy-bet' } },
      { id: 'stay-peers', label: '保持平辈交流', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你们以朋友身份交流。', '他偶尔提醒你「别飘」。'], next: 'prodigy-bet' },
        f: { fx: [stat(MORALE, -4)], msg: ['平辈交流让你没能学到他的全部。', '但那份关系很轻松。'], next: 'prodigy-bet' } },
    ],
  },
  {
    id: 'prodigy-bet', title: '天才赌约', period: 'NORMAL', conds: [done('prodigy-sensei')],
    desc: '那位传奇选手和你打赌：三个月内你能把他保持的残局纪录刷新。',
    options: [
      { id: 'take-bet', label: '接下赌约', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), trophy('EVP', 1), stat(MORALE, 12)], msg: ['三个月后，你差一点就破了纪录。', '他请客吃饭，说「下次一定」。'], next: 'prodigy-hometown' },
        f: { fx: [stat(STRESS, 10)], msg: ['赌约让你训练过度，状态下滑。', '你没破纪录，还伤了一周。'], next: 'prodigy-hometown' } },
      { id: 'no-bet', label: '不接赌约', chance: 0.7,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 4)], msg: ['你笑着说「纪录是你的，我不抢」。', '他哈哈大笑，说你有分寸。'], next: 'prodigy-hometown' },
        f: { fx: [stat(MORALE, -4)], msg: ['不接赌约让你显得「没野心」。', '你自己知道，你只是不想受伤。'], next: 'prodigy-hometown' } },
    ],
  },
  {
    id: 'prodigy-hometown', title: '荣归故里', period: 'NORMAL', conds: [done('prodigy-bet')],
    desc: '你回到家乡办见面会。母校的小学弟们排着队要你签名。',
    options: [
      { id: 'warm-return', label: '用心分享经历', chance: 0.7,
        s: { fx: [stat(MORALE, 12)], msg: ['你讲了低谷的故事，而不是只有高光。', '有个小学弟眼眶红了。'], next: 'prodigy-museum' },
        f: { fx: [stat(STRESS, 6)], msg: ['你讲得太官方，孩子们有点走神。', '但签名环节他们还是很开心。'], next: 'prodigy-museum' } },
      { id: 'donate-gear', label: '捐设备给母校', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', -1000), stat(MORALE, 10)], msg: ['你给母校的机房捐了十台电脑。', '校长说要在机房门口挂你的照片。'], next: 'prodigy-museum' },
        f: { fx: [stat(MORALE, -4)], msg: ['设备采购出了岔子，拖了两个月。', '但最后还是落地了。'], next: 'prodigy-museum' } },
    ],
  },
  {
    id: 'prodigy-museum', title: '名人堂门票', period: 'NORMAL', conds: [done('prodigy-hometown')],
    desc: '你收到一封邀请：入选本年度的行业名人堂候选名单。距离「名留青史」只差一步。',
    options: [
      { id: 'accept-honor', label: '接受荣誉', chance: 0.7,
        s: { fx: [trophy('MVP', 1), stat(MORALE, 12), flag('HALL_OF_FAME', '名人堂候选', 'ACHIEVEMENT')], msg: ['你站在领奖台上，底下是曾经仰望的前辈。', '你终于成了故事里的人。'], next: 'prodigy-redefine' },
        f: { fx: [stat(STRESS, 8)], msg: ['荣誉让你有点不知所措。', '「我配吗」这个问题困扰了你几天。'], next: 'prodigy-redefine' } },
      { id: 'decline-honor', label: '婉拒提名', chance: 0.55,
        s: { fx: [stat(MORALE, 8)], msg: ['你说自己还不够格。', '主办方说：谦虚是好事，但你的数据不会说谎。'], next: 'prodigy-redefine' },
        f: { fx: [stat(MORALE, -4)], msg: ['婉拒之后你有点后悔。', '「错过了可能就没有下次了。」'], next: 'prodigy-redefine' } },
    ],
  },
  // ============ 世界线转换 ============
  {
    id: 'prodigy-comeback-injury', title: '伤病坠落', period: 'NORMAL', conds: [done('prodigy-museum')],
    desc: '一次意外的训练伤让你的赛季报销。医生说得休息半年。半年，在电竞圈像一辈子。',
    options: [
      { id: 'rehab-comeback', label: '养伤后复出', chance: 0.6,
        s: { fx: [wl('comeback'), stat(MORALE, 8), flag('CROSSED_TO_COMEBACK', '转入复出线', 'CUSTOM')], msg: ['你选择了康复和复出。', '这条路，你要从头走一遍。'], next: null },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你害怕复出后回不到巅峰。', '这份恐惧开始啃噬你。'], next: 'prodigy-fall-grinder' } },
      { id: 'refuse-rest', label: '拒绝长时间休养', chance: 0.45,
        s: { fx: [stat(MORALE, 6), stat(ENERGY, -8)], msg: ['你提前复出了，状态勉强在线。', '但你知道，这是在赌。'], next: 'prodigy-fall-grinder' },
        f: { fx: [stat(STRESS, 14), stat(ENERGY, -14)], msg: ['提前复出让伤病加重。', '你被迫休了更久。'], next: 'prodigy-fall-grinder' } },
    ],
  },
  {
    id: 'prodigy-fall-grinder', title: '坠落磨砺', period: 'NORMAL', conds: [done('prodigy-museum')],
    desc: '状态下滑后，没有豪门再愿意冒险。你的经纪人建议：「去低级别联赛，重新打出身价。」',
    options: [
      { id: 'humble-again', label: '放下身段去低级别', chance: 0.6,
        s: { fx: [wl('grinder'), stat(MORALE, 10), flag('CROSSED_TO_GRINDER', '转入磨砺线', 'CUSTOM')], msg: ['你去了低级别联赛。', '从豪门核心到低级联赛，落差很大，但你还想打。'], next: null },
        f: { fx: [stat(STRESS, 10)], msg: ['你放不下身段，拒绝了建议。', '但市场上的邀约越来越少。'], next: 'prodigy-fix-tempt' } },
      { id: 'stay-tier1', label: '留在顶级等机会', chance: 0.55,
        s: { fx: [stat(MORALE, 6)], msg: ['你留在顶级联赛当替补。', '机会还有，但要看运气。'], next: 'prodigy-fix-tempt' },
        f: { fx: [stat(MORALE, -6), stat(STRESS, 8)], msg: ['替补席上坐久了，你的状态继续下滑。', '「过气天才」的标签开始出现。'], next: 'prodigy-fix-tempt' } },
    ],
  },
  {
    id: 'prodigy-fix-tempt', title: '天才诱惑', period: 'NORMAL', conds: [done('prodigy-museum')],
    desc: '有人约你吃饭，暗示「有一场稳赢的比赛，配合一下，保你职业生涯不会断档」。',
    options: [
      { id: 'refuse-tempt', label: '拒绝', chance: 0.75,
        s: { fx: [stat(MORALE, 10), flag('REFUSED_FIX', '拒绝假赛', 'ACHIEVEMENT')], msg: ['你听了一半就起身走了。', '天才的名声不能折在这里。'], next: 'prodigy-z-training-day' },
        f: { fx: [stat(STRESS, 10)], msg: ['你拒绝得不够坚决。', '对方记住了你，之后总在试探。'], next: 'prodigy-z-training-day' } },
      { id: 'consider-it', label: '犹豫了', chance: 0.4,
        s: { fx: [wl('matchfixing'), stat(MORALE, -8), stat(STRESS, 14)], msg: ['你犹豫了，因为实在太难了。', '你最终没有当场拒绝。'], next: null },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你犹豫了几天，最后还是拒绝了。', '但那顿饭的阴影留了很久。'], next: 'prodigy-z-training-day' } },
    ],
  },
  // ============ 尾声 ============
  {
    id: 'prodigy-redefine', title: '重新定义', period: 'FINAL_DECISIVE_MOMENT', conds: [done('prodigy-museum')],
    desc: '你把「天才」两个字从身上摘了下来。现在你只是一个还想赢的老选手。',
    options: [
      { id: 'play-for-love', label: '为热爱而战', chance: 0.65,
        s: { fx: [stat(MORALE, 12), stat(STRESS, -8)], msg: ['你不再为证明什么而打。', '「天才」退场，选手登场。'], next: 'prodigy-legacy' },
        f: { fx: [stat(STRESS, 8)], msg: ['你想放下，但放不干净。', '「天才」两个字还黏在背上。'], next: 'prodigy-legacy' } },
      { id: 'prove-once-more', label: '最后证明一次', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), trophy('MAJOR', 1), stat(MORALE, 14)], msg: ['你用一个冠军证明了自己。', '这次不是天才，是你自己。'], next: 'prodigy-legacy' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['最后一次证明失败了。', '但你已经不在乎别人怎么评价。'], next: 'prodigy-legacy' } },
    ],
  },
  {
    id: 'prodigy-legacy', title: '传奇之证', period: 'NORMAL', conds: [done('prodigy-redefine')],
    desc: '你的职业生涯被写进了行业年鉴。编辑问你：你觉得自己的故事该怎么结尾？',
    options: [
      { id: 'open-ending', label: '未完待续', chance: 0.7,
        s: { fx: [stat(MORALE, 10)], msg: ['你说：故事还没结束。', '编辑笑了笑，把这句话写进了导语。'], next: 'prodigy-retire-star' },
        f: { fx: [stat(STRESS, 6)], msg: ['你想了半天没想好结尾。', '编辑说：那留白也挺好。'], next: 'prodigy-retire-star' } },
      { id: 'full-circle', label: '回望起点', chance: 0.6,
        s: { fx: [stat(MORALE, 12)], msg: ['你把故事的起点写成了第一场比赛。', '那年你 17 岁，赢了第一场线下赛。'], next: 'prodigy-retire-star' },
        f: { fx: [stat(MORALE, -4)], msg: ['回望起点时你有点感伤。', '时间过得真快。'], next: 'prodigy-retire-star' } },
    ],
  },
  {
    id: 'prodigy-retire-star', title: '巨星谢幕', period: 'NORMAL', conds: [done('prodigy-legacy')],
    desc: '你的最后一场比赛。全场起立鼓掌，对手也为你停了手。',
    options: [
      { id: 'wave-goodbye', label: '挥手谢幕', chance: 0.7,
        s: { fx: [stat(MORALE, 12), trophy('EVP', 1)], msg: ['你对着全场挥手，像完成了一次漫长的旅行。', '灯光暗下，掌声还在响。'], next: 'prodigy-z-training-day' },
        f: { fx: [stat(MORALE, -4)], msg: ['你哽咽了，说不出话。', '但你已经不需要再说什么。'], next: 'prodigy-z-training-day' } },
      { id: 'one-last-play', label: '最后打一次比赛', chance: 0.6,
        s: { fx: [attr(CLUTCH, 2), cstat('TOTAL_KILLS', 30), stat(MORALE, 10)], msg: ['你的最后一局打得很尽兴。', '这比任何告别词都好。'], next: 'prodigy-z-training-day' },
        f: { fx: [stat(STRESS, 8)], msg: ['最后一局你发挥一般。', '但你笑着走下了舞台。'], next: 'prodigy-z-training-day' } },
    ],
  },
  // ============ 风味日常（可重复） ============
  {
    id: 'prodigy-z-training-day', title: '训练日常', period: 'NORMAL', conds: [], repeatable: true,
    desc: '天才的日常和普通人没什么两样：热手、训练赛、复盘。',
    options: [
      { id: 'clean-day', label: '高质量完成训练', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 1), stat(MORALE, 4)], msg: ['今天的训练完成度很高。', '天赋只是入场券，练习才是日常。'], next: 'prodigy-z-duel-night' },
        f: { fx: [stat(ENERGY, -4)], msg: ['你有点不在状态。', '你决定明天加倍。'], next: 'prodigy-z-duel-night' } },
      { id: 'push-edge', label: '练极限操作', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.005 }],
        s: { fx: [attr(AIM, 1), stat(MORALE, 6)], msg: ['你练了几个极限身位。', '虽然比赛用不上几次，但手感很爽。'], next: 'prodigy-z-duel-night' },
        f: { fx: [stat(STRESS, 4)], msg: ['极限操作练了半小时没成功一次。', '你有点挫败，但那股劲更足了。'], next: 'prodigy-z-duel-night' } },
    ],
  },
  {
    id: 'prodigy-z-duel-night', title: '单挑之夜', period: 'NORMAL', conds: [], repeatable: true,
    desc: '有人约你晚上 1v1 单挑，赌一顿烧烤。你应战了。',
    options: [
      { id: 'win-duel', label: '全力应战', chance: 0.65, mods: [{ attribute: AIM, perPoint: 0.005 }],
        s: { fx: [attr(AIM, 1), stat(MORALE, 6)], msg: ['你赢了，烧烤到嘴。', '输的人请客，愿赌服输。'], next: 'prodigy-z-team-chat' },
        f: { fx: [stat(MORALE, -4)], msg: ['你输了，请了顿烧烤。', '但你记住了对方的身位习惯。'], next: 'prodigy-z-team-chat' } },
      { id: 'coach-friend', label: '边打边教', chance: 0.6,
        s: { fx: [stat(MORALE, 8), stat(LEADERSHIP, 1)], msg: ['你教了对方几个点位。', '他输得很服气，还约你下次再练。'], next: 'prodigy-z-team-chat' },
        f: { fx: [stat(ENERGY, -4)], msg: ['你边教边打，结果自己也乱了。', '但气氛很好。'], next: 'prodigy-z-team-chat' } },
    ],
  },
  {
    id: 'prodigy-z-team-chat', title: '队内闲聊', period: 'NORMAL', conds: [], repeatable: true,
    desc: '训练结束，队友们在休息室讨论新版本改动。你的意见大家都想听。',
    options: [
      { id: 'share-insight', label: '分享自己的理解', chance: 0.7,
        s: { fx: [attr(GAME_SENSE, 1), stat(MORALE, 5)], msg: ['你讲了新版本的理解。', '队友们认真听了，还做了笔记。'], next: 'prodigy-z-training-day' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['你的理解被队友质疑。', '你没有争，但心里记下了。'], next: 'prodigy-z-training-day' } },
      { id: 'relax-alone', label: '自己安静待着', chance: 0.65,
        s: { fx: [stat(STRESS, -4), stat(ENERGY, 4)], msg: ['你没有参与讨论，安静休息。', '独处的时光让你恢复得很快。'], next: 'prodigy-z-training-day' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['不参与讨论让队友觉得你「高冷」。', '天才的人设又加深了一点。'], next: 'prodigy-z-training-day' } },
    ],
  },
];
