/**
 * rookie 世界线内容（新秀之路）。
 * 入口为既有 rookie-scrim-rotation；本文件内容全部 gated 在 COMPLETED_EVENT rookie-scrim-rotation 之后。
 * 文风：冷静纪实、两难抉择、含蓄留白。
 */
import {
  attr, stat, flag, rmFlag, wl, transfer, role, trophy, cstat,
  done, hasFlag, age, statCond, attrCond, ANY, ALL, NONE,
  MORALE, ENERGY, BALANCE, STRESS, RATING2,
  AIM, GAME_SENSE, LEADERSHIP, CLUTCH, CONSISTENCY, TEAM_CONFLICT,
} from './helpers.js';

const GATE = done('rookie-scrim-rotation');

export default [
  // ============ 主线：站稳脚跟 ============
  {
    id: 'rookie-first-season', title: '首个赛季', period: 'NORMAL', conds: [GATE],
    desc: '轮换名单上有你的名字，但首发位置还要靠表现争取。赛季第一场训练赛，教练在看你。',
    options: [
      { id: 'steady-start', label: '稳扎稳打按战术打', chance: 0.6, mods: [{ attribute: GAME_SENSE, perPoint: 0.008 }],
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 8), flag('ROOKIE_SETTLING', '站稳脚跟', 'CAREER')], msg: ['第一场训练赛你按战术执行，失误很少。', '教练在复盘时把你的名字多提了两次。'], next: 'rookie-bench-lesson' },
        f: { fx: [stat(STRESS, 8), stat(MORALE, -3)], msg: ['战术执行到一半你还是犹豫了。', '教练没有点你的名，但赛后单独留你加练。'], next: 'rookie-bench-lesson' } },
      { id: 'flashy-play', label: '用枪法抢镜头', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 10), flag('ROOKIE_MAVERICK', '敢打敢拼', 'CAREER')], msg: ['一次 1v3 残局你全收，训练室有人吹了声口哨。', '教练没夸你，但也没批你。'], next: 'rookie-bench-lesson' },
        f: { fx: [stat(STRESS, 12), stat(TEAM_CONFLICT, 2)], msg: ['你为了镜头强行拉枪，白送了两分。', '队友没说什么，沉默比批评更难受。'], next: 'rookie-bench-lesson' } },
    ],
  },
  {
    id: 'rookie-bench-lesson', title: '板凳一课', period: 'NORMAL', conds: [done('rookie-first-season')],
    desc: '轮换到你替补。你坐在长凳上看完整场，第一次从旁观者角度读比赛。',
    options: [
      { id: 'watch-and-learn', label: '认真记录对面习惯', chance: 0.7,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 5)], msg: ['你发现对面指挥总是在残局前换到 A 点。', '这份笔记后来成了队内资料。'], next: 'rookie-substitute-life' },
        f: { fx: [stat(ENERGY, -5)], msg: ['你看了半场就走神了。', '下场后你把笔记补完，但错过了关键细节。'], next: 'rookie-substitute-life' } },
      { id: 'ask-for-time', label: '向教练申请上场时间', chance: 0.4,
        s: { fx: [stat(MORALE, 12), stat(STRESS, 6)], msg: ['教练说下一场给你两局的机会。', '你把这当成唯一的机会。'], next: 'rookie-substitute-life' },
        f: { fx: [stat(MORALE, -8), stat(STRESS, 10)], msg: ['教练说先看表现，没有松口。', '你回到长凳，把不满咽了回去。'], next: 'rookie-substitute-life' } },
    ],
  },
  {
    id: 'rookie-substitute-life', title: '替补日常', period: 'NORMAL', conds: [done('rookie-bench-lesson')],
    desc: '你进入「训练赛主力、正式赛替补」的循环。名册上有你，聚光灯没你。',
    options: [
      { id: 'grind-solo', label: '每天加练到深夜', chance: 0.65, mods: [{ attribute: AIM, perPoint: 0.006 }],
        s: { fx: [attr(AIM, 3), stat(ENERGY, -8), stat(MORALE, 6)], msg: ['夜深人静的训练室只剩你和准星。', '枪感肉眼可见地回来了。'], next: 'rookie-comms-lesson' },
        f: { fx: [stat(ENERGY, -15), stat(STRESS, 8)], msg: ['加练到凌晨，第二天训练赛状态更差了。', '你开始怀疑努力的方向。'], next: 'rookie-comms-lesson' } },
      { id: 'bond-with-team', label: '帮主力做战术笔记', chance: 0.55,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 8), flag('TEAM_INSIDER', '队内熟面孔', 'CAREER')], msg: ['你给主力递了几条有用的观察。', '从那以后，战术会议开始有你的位置。'], next: 'rookie-comms-lesson' },
        f: { fx: [stat(MORALE, -4)], msg: ['笔记递上去没什么人看。', '但你至少知道了战术怎么走。'], next: 'rookie-comms-lesson' } },
    ],
  },
  {
    id: 'rookie-comms-lesson', title: '沟通课', period: 'NORMAL', conds: [done('rookie-substitute-life')],
    desc: '指挥说你的报点太啰嗦。信息像堵车一样卡在队伍频道里。',
    options: [
      { id: 'short-calls', label: '练习三秒报点', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 6)], msg: ['你把报点压缩成关键词。', '队伍频道清静了很多，指挥开始听你的信息。'], next: 'rookie-lan-debut' },
        f: { fx: [stat(STRESS, 8), stat(TEAM_CONFLICT, 2)], msg: ['你越想简短越说错。', '有队友说：还不如闭嘴。'], next: 'rookie-lan-debut' } },
      { id: 'speak-more', label: '抢着提供信息', chance: 0.45,
        s: { fx: [attr(GAME_SENSE, 2), flag('CALLER_ROOKIE', '敢喊话的新人', 'CAREER')], msg: ['你开始主动报位置和血量。', '有几条信息真的救了局。'], next: 'rookie-lan-debut' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(STRESS, 6)], msg: ['频道里七嘴八舌，指挥吼了一声。', '你决定以后少说两句。'], next: 'rookie-lan-debut' } },
    ],
  },
  {
    id: 'rookie-lan-debut', title: '线下首秀', period: 'NORMAL', conds: [done('rookie-comms-lesson')],
    desc: '队伍打进线下赛。舞台灯光比你想象得亮，台下第一排坐着你的家人。',
    options: [
      { id: 'breathe-and-play', label: '深呼吸按训练打', chance: 0.6, mods: [{ attribute: CONSISTENCY, perPoint: 0.008 }],
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10), cstat('MAPS_PLAYED', 1)], msg: ['第一局你打出了训练水平。', '下场时有人喊了你的 ID。'], next: 'rookie-stage-fright' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -5)], msg: ['你枪口抖了两下，手感全无。', '你低着头走回休息室。'], next: 'rookie-stage-fright' } },
      { id: 'show-off', label: '想秀一把大的', chance: 0.4, mods: [{ attribute: CLUTCH, perPoint: 0.006 }],
        s: { fx: [attr(CLUTCH, 3), stat(MORALE, 12), cstat('CLUTCH_WON', 1)], msg: ['你跳出来打了个不可思议的 1v2。', '观众席炸了。'], next: 'rookie-stage-fright' },
        f: { fx: [stat(STRESS, 15), stat(MORALE, -8)], msg: ['秀操作变成了白给。', '队友安慰你，但你记了一整晚。'], next: 'rookie-stage-fright' } },
    ],
  },
  {
    id: 'rookie-stage-fright', title: '舞台恐惧', period: 'NORMAL', conds: [done('rookie-lan-debut')],
    desc: '站上舞台后你的手心全是汗。观众席的欢呼像隔着一层水。',
    options: [
      { id: 'face-it', label: '硬着头皮打', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.007 }],
        s: { fx: [attr(CLUTCH, 2), attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['前几回合你还是紧张。', '打到一半，你突然忘了紧张这回事。'], next: 'rookie-captain-notice' },
        f: { fx: [stat(STRESS, 14), stat(ENERGY, -6)], msg: ['你整场像在梦游。', '赛后教练只说了句：下次会好。'], next: 'rookie-captain-notice' } },
      { id: 'corner-hug', label: '躲在角落求稳', chance: 0.65,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 4)], msg: ['你打得很保守，但至少没拖后腿。', '有人觉得你稳，也有人觉得你怂。'], next: 'rookie-captain-notice' },
        f: { fx: [stat(MORALE, -6), stat(STRESS, 8)], msg: ['保守也没换来好结果。', '你开始怀疑自己适不适合这个舞台。'], next: 'rookie-captain-notice' } },
    ],
  },
  {
    id: 'rookie-captain-notice', title: '队长注意', period: 'NORMAL', conds: [done('rookie-stage-fright')],
    desc: '队长在赛后找到你，说他观察了你三场比赛。你的某些习惯让他印象深刻。',
    options: [
      { id: 'ask-details', label: '虚心请教具体问题', chance: 0.7,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 10), flag('CAPTAIN_EYE', '队长看好你', 'CAREER')], msg: ['队长给你讲了三个站位问题。', '他把你的 ID 记在了手机备忘录里。'], next: 'rookie-role-experiment' },
        f: { fx: [stat(STRESS, 6)], msg: ['你听得一知半解，没好意思追问。', '但至少队长认识你了。'], next: 'rookie-role-experiment' } },
      { id: 'brag-a-little', label: '说自己状态很好', chance: 0.5,
        s: { fx: [stat(MORALE, 8), stat(TEAM_CONFLICT, 1)], msg: ['你说自己没问题。', '队长笑了笑，让你拿比赛说话。'], next: 'rookie-role-experiment' },
        f: { fx: [stat(MORALE, -5), stat(STRESS, 8)], msg: ['你吹了两句，结果被队长举出的数据打脸。', '你涨红了脸。'], next: 'rookie-role-experiment' } },
    ],
  },
  {
    id: 'rookie-role-experiment', title: '位置实验', period: 'NORMAL', conds: [done('rookie-captain-notice')],
    desc: '教练想试试把你从突破手换到自由人。这个位置你只在路人局里玩过。',
    options: [
      { id: 'try-new-role', label: '接下新位置', chance: 0.55, mods: [{ attribute: GAME_SENSE, perPoint: 0.008 }],
        s: { fx: [attr(GAME_SENSE, 3), role('LURK'), stat(MORALE, 8)], msg: ['你第一次感受到地图另一边的世界。', '教练说这个位置有戏。'], next: 'rookie-coach-critique' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['你在新位置上迷路了好几次。', '教练没放弃，但你有点动摇。'], next: 'rookie-coach-critique' } },
      { id: 'stay-role', label: '坚持老位置', chance: 0.7,
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你留在突破手的位置上。', '熟悉的地方让你安心。'], next: 'rookie-coach-critique' },
        f: { fx: [stat(MORALE, -3)], msg: ['你留在老位置，但心里开始犯嘀咕。', '教练会不会觉得你不肯学？'], next: 'rookie-coach-critique' } },
    ],
  },
  {
    id: 'rookie-coach-critique', title: '教练批评', period: 'NORMAL', conds: [done('rookie-role-experiment')],
    desc: '教练当着全队的面说你「打得像路人局」。气氛安静了三秒。',
    options: [
      { id: 'take-it', label: '低头认错', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 2)], msg: ['你没辩解，把问题记在手机上。', '教练说：至少态度还行。'], next: 'rookie-mentor-advice' },
        f: { fx: [stat(MORALE, -10), stat(STRESS, 8)], msg: ['你认了错，但心里堵得慌。', '那一晚训练你打得稀烂。'], next: 'rookie-mentor-advice' } },
      { id: 'talk-back', label: '当面解释', chance: 0.4,
        s: { fx: [stat(LEADERSHIP, 2), stat(TEAM_CONFLICT, 1)], msg: ['你解释了当时的判断逻辑。', '教练听完，难得地沉默了一下。'], next: 'rookie-mentor-advice' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(MORALE, -6)], msg: ['顶嘴让场面更难堪。', '有几个队友看你的眼神变了。'], next: 'rookie-mentor-advice' } },
    ],
  },
  {
    id: 'rookie-mentor-advice', title: '老将指点', period: 'NORMAL', conds: [done('rookie-coach-critique')],
    desc: '队里最老的选手约你吃饭。他说想给你讲点「说明书上没写的东西」。',
    options: [
      { id: 'soak-it', label: '认真听完整场饭', chance: 0.7,
        s: { fx: [attr(LEADERSHIP, 2), attr(GAME_SENSE, 2), flag('MENTOR_LINK', '老将提携', 'CAREER')], msg: ['他讲了三个版本更替期活下来的秘诀。', '散伙时他说：下次请客。'], next: 'rookie-clutch-moment' },
        f: { fx: [stat(ENERGY, -5)], msg: ['你听了一半开始走神。', '老将没再说下去，只是拍了拍你。'], next: 'rookie-clutch-moment' } },
      { id: 'ask-sharp', label: '只问最尖锐的问题', chance: 0.5,
        s: { fx: [attr(GAME_SENSE, 3), stat(TEAM_CONFLICT, 1)], msg: ['你直接问：这队里谁不能信。', '老将愣了一下，给你指了个人。'], next: 'rookie-clutch-moment' },
        f: { fx: [stat(TEAM_CONFLICT, 3)], msg: ['你的问题太直，老将打哈哈过去了。', '但那顿饭之后，你对队里的事更留了个心眼。'], next: 'rookie-clutch-moment' } },
    ],
  },
  {
    id: 'rookie-clutch-moment', title: '残局时刻', period: 'NORMAL', conds: [done('rookie-mentor-advice')],
    desc: '比赛进入 1v3 残局，全场只剩你一个人。耳机里队友在报点，声音都在抖。',
    options: [
      { id: 'go-fast', label: '抢时间打快枪', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('CLUTCH_WON', 1), stat(MORALE, 10)], msg: ['你连拉三个枪位，全部命中。', '赛后大家叫你「小残局」。'], next: 'rookie-injury-scare' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -4)], msg: ['你冲得太快，第一个就被架死了。', '耳机里只剩下叹气声。'], next: 'rookie-training-routine' } },
      { id: 'play-smart', label: '拖时间打角度', chance: 0.6, mods: [{ attribute: GAME_SENSE, perPoint: 0.008 }],
        s: { fx: [attr(GAME_SENSE, 3), cstat('CLUTCH_WON', 1), stat(MORALE, 8)], msg: ['你把对面拆成一个个 1v1。', '赢下时你的手还在抖。'], next: 'rookie-training-routine' },
        f: { fx: [stat(STRESS, 12)], msg: ['角度算得没错，但枪没跟上。', '你差一点就能赢。'], next: 'rookie-training-routine' } },
    ],
  },
  {
    id: 'rookie-injury-scare', title: '伤病虚惊', period: 'NORMAL', conds: [done('rookie-clutch-moment')],
    desc: '训练时你的手腕突然疼了一下。队医看了一眼，说可能是腱鞘炎前兆。',
    options: [
      { id: 'rest-early', label: '立刻停训一周', chance: 0.7,
        s: { fx: [stat(ENERGY, 12), stat(STRESS, -6), flag('HEALTHY_HABIT', '健康习惯', 'CAREER')], msg: ['你老老实实歇了一周。', '回来时手腕没事，手感还在。'], next: 'rookie-training-routine' },
        f: { fx: [stat(MORALE, -6)], msg: ['你歇了三天就坐不住了。', '手腕还有点酸，但你决定硬扛。'], next: 'rookie-training-routine' } },
      { id: 'push-through', label: '忍痛继续练', chance: 0.4,
        s: { fx: [stat(STRESS, 8), stat(MORALE, 6)], msg: ['你咬着牙练完了这一周。', '手腕没更糟，但你心里记了一笔。'], next: 'rookie-training-routine' },
        f: { fx: [stat(STRESS, 15), stat(ENERGY, -10)], msg: ['第三天手腕肿了起来。', '队医的脸色很难看。'], next: 'rookie-training-routine' } },
    ],
  },
  {
    id: 'rookie-training-routine', title: '训练作息', period: 'NORMAL', conds: [done('rookie-clutch-moment')],
    desc: '连续的加练让你的作息乱成一团。白天困、晚上精神，训练赛状态像过山车。',
    options: [
      { id: 'fix-schedule', label: '调整作息早睡', chance: 0.65,
        s: { fx: [stat(ENERGY, 12), stat(MORALE, 6)], msg: ['你把睡觉时间提前了三小时。', '一周后，你的状态稳定多了。'], next: 'rookie-media-interview' },
        f: { fx: [stat(STRESS, 6)], msg: ['你定了计划，但半夜还是爬起来打了两把。', '第二天你盯着屏幕发呆。'], next: 'rookie-media-interview' } },
      { id: 'caffeine-crutch', label: '靠咖啡顶着', chance: 0.5,
        s: { fx: [stat(ENERGY, 6), stat(STRESS, 4)], msg: ['咖啡因确实管用，训练赛没那么困了。', '但你知道这不是长久之计。'], next: 'rookie-media-interview' },
        f: { fx: [stat(ENERGY, -8), stat(STRESS, 10)], msg: ['咖啡喝到心跳加速。', '训练赛你手抖得厉害。'], next: 'rookie-media-interview' } },
    ],
  },
  {
    id: 'rookie-media-interview', title: '首次采访', period: 'NORMAL', conds: [done('rookie-training-routine')],
    desc: '赛后混采区有记者把话筒递到你面前。镜头红灯亮起的那一刻，你忘了要说什么。',
    options: [
      { id: 'honest-words', label: '实话实说', chance: 0.6,
        s: { fx: [stat(MORALE, 8), flag('MEDIA_FRIENDLY', '媒体好感', 'CAREER')], msg: ['你说自己还在学习。', '这段采访意外地被粉丝剪成了片段。'], next: 'rookie-stream-clip' },
        f: { fx: [stat(STRESS, 10)], msg: ['你结结巴巴说了两句就结束了。', '晚上你反复回看自己的采访，想找个地缝。'], next: 'rookie-stream-clip' } },
      { id: 'safe-answers', label: '背准备好的答案', chance: 0.7,
        s: { fx: [stat(STRESS, -4)], msg: ['你把官方套话背得很流利。', '记者没挖到爆点，但也没出错。'], next: 'rookie-stream-clip' },
        f: { fx: [stat(MORALE, -4)], msg: ['套话背到一半卡壳了。', '镜头尴尬地切走。'], next: 'rookie-stream-clip' } },
    ],
  },
  {
    id: 'rookie-stream-clip', title: '直播切片', period: 'NORMAL', conds: [done('rookie-media-interview')],
    desc: '你直播时的一段搞笑切片上了热门。评论一半在笑，一半在夸你的反应。',
    options: [
      { id: 'lean-in', label: '顺势整活营业', chance: 0.6,
        s: { fx: [cstat('CAREER_EARNINGS', 300), stat(MORALE, 8)], msg: ['你顺着梗录了条回应视频。', '涨了粉丝，也多了点零花钱。'], next: 'rookie-haters-wave' },
        f: { fx: [stat(STRESS, 8)], msg: ['整活没接住梗，评论区开始嘲讽。', '你关了弹幕，心里还是难受。'], next: 'rookie-haters-wave' } },
      { id: 'stay-low', label: '不回应，专心训练', chance: 0.7,
        s: { fx: [attr(AIM, 2), stat(MORALE, 4)], msg: ['你选择让热度自己过去。', '训练室里没人再提那件事。'], next: 'rookie-haters-wave' },
        f: { fx: [stat(MORALE, -5)], msg: ['不回应也是一种回应。', '节奏还是跟了你一周。'], next: 'rookie-haters-wave' } },
    ],
  },
  {
    id: 'rookie-haters-wave', title: '网络质疑', period: 'NORMAL', conds: [done('rookie-stream-clip')],
    desc: '一场发挥平平的比赛后，评论区说你「靠剪辑火起来的」。这些字你每条都看完了。',
    options: [
      { id: 'ignore-them', label: '关掉评论区', chance: 0.7,
        s: { fx: [stat(STRESS, -8), stat(MORALE, 4)], msg: ['你把社交软件卸了三天。', '训练状态反而好了一点。'], next: 'rookie-comeback-clutch' },
        f: { fx: [stat(STRESS, 12)], msg: ['你告诉自己别看了，手却停不下来。', '那几天你睡得很差。'], next: 'rookie-comeback-clutch' } },
      { id: 'prove-it', label: '憋着一口气练', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.007 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 6), stat(ENERGY, -6)], msg: ['你把质疑截图存下来当屏保。', '下一场比赛你打出了自己的声音。'], next: 'rookie-comeback-clutch' },
        f: { fx: [stat(STRESS, 12), stat(ENERGY, -10)], msg: ['你越想证明越用力过猛。', '训练赛失误更多了。'], next: 'rookie-comeback-clutch' } },
    ],
  },
  {
    id: 'rookie-comeback-clutch', title: '逆转残局', period: 'NORMAL', conds: [done('rookie-haters-wave')],
    desc: '决胜图 13:14，你一个人面对三个拆包的人。这一局可能决定整个系列赛。',
    options: [
      { id: 'cold-clutch', label: '冷静按步骤拆', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.009 }],
        s: { fx: [attr(CLUTCH, 3), cstat('CLUTCH_WON', 1), stat(MORALE, 12)], msg: ['你先放倒一个，再切枪换位，最后刀了拆包的。', '全场都在喊你的 ID。'], next: 'rookie-transfer-rumor' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['你差一枪就能赢。', '赛后那句「差一点」在脑子里回放了一路。'], next: 'rookie-transfer-rumor' } },
      { id: 'yolo-rush', label: '莽一把赌手感', chance: 0.4, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('CLUTCH_WON', 1), flag('CLUTCH_KING', '残局王', 'ACHIEVEMENT')], msg: ['你直接跳出来一串三。', '这个操作被剪成了当周 TOP 集锦。'], next: 'rookie-transfer-rumor' },
        f: { fx: [stat(STRESS, 12)], msg: ['赌输了。', '你的莽在赛后复盘里被反复拉出来。'], next: 'rookie-transfer-rumor' } },
    ],
  },
  {
    id: 'rookie-transfer-rumor', title: '转会传闻', period: 'TRANSFER_WINDOW', conds: [done('rookie-comeback-clutch')],
    desc: '有经纪公司托人带话：一支中游战队想签你，报价比你现在高两倍。',
    options: [
      { id: 'take-the-leap', label: '接触看看', chance: 0.6,
        s: { fx: [stat(MORALE, 10), stat(STRESS, 6), flag('TRANSFER_INTEREST', '转会邀约', 'CAREER')], msg: ['你和对方约了一次视频通话。', '他们给的承诺很具体。'], next: 'rookie-pro-contract' },
        f: { fx: [stat(STRESS, 10)], msg: ['消息不小心走漏了。', '队里开始有人用奇怪的眼神看你。'], next: 'rookie-pro-contract' } },
      { id: 'stay-loyal', label: '留下来', chance: 0.7,
        s: { fx: [stat(MORALE, 8), flag('LOYAL_ROOKIE', '忠诚新秀', 'CAREER')], msg: ['你回绝了报价。', '教练听说后，把你调进了首发。'], next: 'rookie-pro-contract' },
        f: { fx: [stat(MORALE, -4), stat(STRESS, 8)], msg: ['你拒绝了，但心里开始计算代价。', '这个念头偶尔还会冒出来。'], next: 'rookie-pro-contract' } },
    ],
  },
  {
    id: 'rookie-pro-contract', title: '职业合同', period: 'NORMAL', conds: [done('rookie-transfer-rumor')],
    desc: '正式合同摆在你面前。签字意味着你从青训选手变成职业选手，也意味着更多的责任。',
    options: [
      { id: 'sign-it', label: '签字', chance: 0.8,
        s: { fx: [cstat('CAREER_EARNINGS', 2000), stat(MORALE, 12), flag('PRO_PLAYER', '职业选手', 'ACHIEVEMENT')], msg: ['笔落下的时候，你的手是稳的。', '经纪人发来一句：欢迎入行。'], next: 'rookie-first-pro-win' },
        f: { fx: [stat(STRESS, 8)], msg: ['你签了，但条款里有些字你看得不够细。', '晚上你翻合同翻到凌晨。'], next: 'rookie-first-pro-win' } },
      { id: 'negotiate', label: '再谈一轮', chance: 0.5,
        s: { fx: [cstat('CAREER_EARNINGS', 2800), stat(MORALE, 8)], msg: ['你提了一个数字，对面居然松口了。', '你第一次意识到谈判也是技术活。'], next: 'rookie-first-pro-win' },
        f: { fx: [stat(STRESS, 10)], msg: ['谈判僵住了一周，差点黄了。', '最后还是签了，但彼此都留了点疙瘩。'], next: 'rookie-first-pro-win' } },
    ],
  },
  {
    id: 'rookie-first-pro-win', title: '职业首胜', period: 'NORMAL', conds: [done('rookie-pro-contract')],
    desc: '转职业后的第一场正式比赛。赛前你紧张到把鼠标线绕了个结。',
    options: [
      { id: 'play-my-game', label: '按自己的节奏打', chance: 0.6, mods: [{ attribute: CONSISTENCY, perPoint: 0.008 }],
        s: { fx: [attr(CONSISTENCY, 3), cstat('MAPS_PLAYED', 1), cstat('TOTAL_KILLS', 45), stat(MORALE, 12)], msg: ['你打出了自己的节奏，2:0 拿下。', '数据板上你的击杀数是全场第二。'], next: 'rookie-losing-streak' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -3)], msg: ['第一局你打得磕磕绊绊。', '好在队伍赢了，但你知道这不是你的功劳。'], next: 'rookie-losing-streak' } },
      { id: 'prove-now', label: '证明自己值身价', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), cstat('TOTAL_KILLS', 58), stat(MORALE, 12)], msg: ['你打出 58 击杀，全场最高。', '赛后采访你第一次被叫「明星选手」。'], next: 'rookie-losing-streak' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -8)], msg: ['越想证明越变形，你打出了生涯最差数据。', '好在队伍还是赢了，你逃过一劫。'], next: 'rookie-losing-streak' } },
    ],
  },
  {
    id: 'rookie-losing-streak', title: '三连败', period: 'NORMAL', conds: [done('rookie-first-pro-win')],
    desc: '赢了一周后，队伍连输三场。训练室里的空气变得很重，谁都不想先开口。',
    options: [
      { id: 'speak-up', label: '主动开复盘会', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.008 }],
        s: { fx: [attr(LEADERSHIP, 3), stat(MORALE, 8), flag('TEAM_GLUE', '队伍粘合剂', 'CAREER')], msg: ['你第一个把问题摆到桌上。', '复盘开到深夜，但大家的脸色好看多了。'], next: 'rookie-team-blame' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(STRESS, 8)], msg: ['会议开成了吵架。', '你后悔自己开了这个头。'], next: 'rookie-team-blame' } },
      { id: 'grind-quiet', label: '默默加练', chance: 0.6, mods: [{ attribute: AIM, perPoint: 0.006 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 4)], msg: ['你选择用枪说话。', '第四场你的状态救了队伍一命。'], next: 'rookie-team-blame' },
        f: { fx: [stat(ENERGY, -8), stat(STRESS, 6)], msg: ['加练到后半夜，你的状态反而更差了。', '连败的阴影还在。'], next: 'rookie-team-blame' } },
    ],
  },
  {
    id: 'rookie-team-blame', title: '甩锅风波', period: 'NORMAL', conds: [done('rookie-losing-streak')],
    desc: '有队友在直播里暗示连败是因为「新人拖节奏」。弹幕立刻刷到了你脸上。',
    options: [
      { id: 'front-it-out', label: '当面对质', chance: 0.45, mods: [{ attribute: LEADERSHIP, perPoint: 0.007 }],
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['你直接找他对质，话赶话差点动手。', '但说完之后，彼此反而把话说开了。'], next: 'rookie-veteran-conflict' },
        f: { fx: [stat(TEAM_CONFLICT, 6), stat(STRESS, 12)], msg: ['对质变成了单方面挨批。', '你意识到这个队里有人不想让你待下去。'], next: 'rookie-fight-back' } },
      { id: 'data-talks', label: '用数据回击', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 2), stat(MORALE, 6)], msg: ['你把三场连败的击杀和首杀数据拉出来。', '数据不会说谎，弹幕安静了。'], next: 'rookie-fight-back' },
        f: { fx: [stat(STRESS, 10)], msg: ['数据摆出来了，但没人看。', '你第一次明白舆论不认数据。'], next: 'rookie-fight-back' } },
    ],
  },
  {
    id: 'rookie-veteran-conflict', title: '老将冲突', period: 'NORMAL', conds: [done('rookie-team-blame')],
    desc: '那位甩锅的队友其实是队内资历最老的人。你当众反驳他之后，更衣室分成两派。',
    options: [
      { id: 'mend-fence', label: '私下缓和关系', chance: 0.6,
        s: { fx: [stat(TEAM_CONFLICT, -5), stat(MORALE, 6)], msg: ['你买了杯咖啡放他桌上。', '他没说话，但训练时愿意和你配合了。'], next: 'rookie-fight-back' },
        f: { fx: [stat(TEAM_CONFLICT, 2), stat(STRESS, 8)], msg: ['示好被晾在一边。', '你觉得热脸贴了冷屁股。'], next: 'rookie-fight-back' } },
      { id: 'stay-firm', label: '坚持不低头', chance: 0.5,
        s: { fx: [attr(LEADERSHIP, 3), stat(TEAM_CONFLICT, 3), stat(MORALE, 8)], msg: ['你不觉得自己有错。', '半个队支持你，这让老将很难办。'], next: 'rookie-fight-back' },
        f: { fx: [stat(TEAM_CONFLICT, 5), stat(STRESS, 12)], msg: ['坚持到底变成了孤立无援。', '训练时没人再和你搭话。'], next: 'rookie-fight-back' } },
    ],
  },
  {
    id: 'rookie-fight-back', title: '反击上位', period: 'NORMAL', conds: [done('rookie-team-blame')],
    desc: '教练把首发名单换了：你顶替了那位老将的位置。更衣室安静得像没人。',
    options: [
      { id: 'carry-the-weight', label: '用表现说话', chance: 0.6, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), attr(CONSISTENCY, 2), stat(MORALE, 10)], msg: ['你打出了职业以来最好的一场比赛。', '教练赛后拍了拍你的肩膀。'], next: 'rookie-second-team' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['压力太大，你发挥失常。', '替补席上有人轻轻笑了一声。'], next: 'rookie-second-team' } },
      { id: 'share-credit', label: '把功劳分给队友', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 3), stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['赛后采访你把功劳推给了全队。', '更衣室的气氛悄悄回暖了。'], next: 'rookie-second-team' },
        f: { fx: [stat(TEAM_CONFLICT, 2)], msg: ['你让功劳显得刻意。', '有人觉得你在表演。'], next: 'rookie-second-team' } },
    ],
  },
  {
    id: 'rookie-second-team', title: '二队征调', period: 'NORMAL', conds: [done('rookie-fight-back')],
    desc: '俱乐部二队缺人，想临时调你去打两场线下。一队教练不想放人。',
    options: [
      { id: 'go-help', label: '去二队救场', chance: 0.6,
        s: { fx: [cstat('MAPS_PLAYED', 2), cstat('TOTAL_KILLS', 62), stat(MORALE, 8)], msg: ['你在二队打了两场，表现很稳。', '回来时，一队教练对你更放心了。'], next: 'rookie-leadership-test' },
        f: { fx: [stat(ENERGY, -8), stat(STRESS, 6)], msg: ['两边奔波让你疲惫不堪。', '二队赢了一场，但你累得够呛。'], next: 'rookie-leadership-test' } },
      { id: 'refuse', label: '专心一队', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你留在了一队。', '但二队那边对你的评价变成了「架子大」。'], next: 'rookie-leadership-test' },
        f: { fx: [stat(MORALE, -4)], msg: ['你拒绝了，心里却有点不安。', '「会不会显得我不肯帮忙？」'], next: 'rookie-leadership-test' } },
    ],
  },
  {
    id: 'rookie-leadership-test', title: '指挥试炼', period: 'NORMAL', conds: [done('rookie-second-team')],
    desc: '指挥临时请假，教练把麦克风交给你：「今天你来带节奏。」你紧张得想上厕所。',
    options: [
      { id: 'lead-calm', label: '按战术板带', chance: 0.55, mods: [{ attribute: LEADERSHIP, perPoint: 0.01 }],
        s: { fx: [attr(LEADERSHIP, 3), attr(GAME_SENSE, 2), stat(MORALE, 10)], msg: ['你第一次完整地指挥完一场比赛。', '虽然磕绊，但赢了下来。'], next: 'rookie-sponsor-deal' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['你的指挥让队伍陷入混乱。', '赛后教练说：至少你知道了指挥有多难。'], next: 'rookie-sponsor-deal' } },
      { id: 'listen-elders', label: '多听老队员意见', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 2), stat(TEAM_CONFLICT, -2), stat(MORALE, 6)], msg: ['你把节奏交给经验最丰富的人。', '比赛赢了，大家都舒了口气。'], next: 'rookie-sponsor-deal' },
        f: { fx: [stat(TEAM_CONFLICT, 3)], msg: ['你的「民主」让场上指令混乱。', '有人开始质疑你的决策。'], next: 'rookie-sponsor-deal' } },
    ],
  },
  {
    id: 'rookie-sponsor-deal', title: '首个赞助', period: 'NORMAL', conds: [done('rookie-leadership-test')],
    desc: '一家外设品牌找到你：签一年赞助，代价是训练必须用他们的新款鼠标。',
    options: [
      { id: 'take-sponsor', label: '签下赞助', chance: 0.7,
        s: { fx: [cstat('CAREER_EARNINGS', 1500), stat(MORALE, 8)], msg: ['钱到账了，鼠标也到了。', '你用新鼠标打了一周，手感意外地不错。'], next: 'rookie-endorsement-deal' },
        f: { fx: [stat(STRESS, 8), stat(MORALE, -4)], msg: ['新鼠标的握感和你的习惯差太多。', '你连着失误了好几天，开始后悔。'], next: 'rookie-endorsement-deal' } },
      { id: 'test-first', label: '先试用再谈', chance: 0.6,
        s: { fx: [stat(MORALE, 4), flag('SHARP_EYE', '眼光毒辣', 'CAREER')], msg: ['你要求试用两周再决定。', '试用后你发现手感确实差，没签。'], next: 'rookie-endorsement-deal' },
        f: { fx: [stat(STRESS, 6)], msg: ['试用期对方等得不耐烦，撤了报价。', '你错过了这笔钱。'], next: 'rookie-endorsement-deal' } },
    ],
  },
  {
    id: 'rookie-endorsement-deal', title: '代言取舍', period: 'NORMAL', conds: [done('rookie-sponsor-deal')],
    desc: '另一家更大的品牌来了，条件是用他们的外设出席线下活动。你刚和上家签完字。',
    options: [
      { id: 'honor-contract', label: '守住现有合同', chance: 0.7,
        s: { fx: [stat(MORALE, 8), flag('TRUSTWORTHY', '信守承诺', 'CAREER')], msg: ['你回绝了大品牌。', '上家听说后，主动给你加了点价。'], next: 'rookie-scrim-strong' },
        f: { fx: [stat(MORALE, -5)], msg: ['你回绝了，但心里开始算那笔差价。', '这念头跟着你进了训练室。'], next: 'rookie-scrim-strong' } },
      { id: 'break-for-big', label: '违约跳槽', chance: 0.4,
        s: { fx: [cstat('CAREER_EARNINGS', 4000), stat(MORALE, 10), flag('MERCENARY', '雇佣兵', 'CUSTOM')], msg: ['违约金虽然高，但新合同更肥。', '上家的公关稿里语气并不客气。'], next: 'rookie-scrim-strong' },
        f: { fx: [stat(STRESS, 15), cstat('CAREER_EARNINGS', -1500)], msg: ['谈判破裂，你赔了违约金。', '品牌圈开始流传你的名字，带着贬义。'], next: 'rookie-scrim-strong' } },
    ],
  },
  {
    id: 'rookie-scrim-strong', title: '强队训练', period: 'NORMAL', conds: [done('rookie-endorsement-deal')],
    desc: '约到一支 Top10 队伍打训练赛。赛前队长说：「别想着赢，想着别输得太难看。」',
    options: [
      { id: 'treat-as-final', label: '当决赛打', chance: 0.5, mods: [{ attribute: CLUTCH, perPoint: 0.008 }],
        s: { fx: [attr(CLUTCH, 3), attr(GAME_SENSE, 2), stat(MORALE, 10)], msg: ['你打出了超常发挥。', '对面教练赛后问了一句：你们这个新人叫什么？'], next: 'rookie-humbling-loss' },
        f: { fx: [stat(STRESS, 12), stat(MORALE, -6)], msg: ['你越紧张越白给。', '对方有个人局局针对你。'], next: 'rookie-humbling-loss' } },
      { id: 'copy-them', label: '偷学对面套路', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 6)], msg: ['你全程录像，赛后逐帧研究。', '你学到了三个新战术。'], next: 'rookie-humbling-loss' },
        f: { fx: [stat(ENERGY, -6)], msg: ['光顾着看对面，自己的节奏丢了。', '录像存了，但研究了一半就困了。'], next: 'rookie-humbling-loss' } },
    ],
  },
  {
    id: 'rookie-humbling-loss', title: '被暴打一课', period: 'NORMAL', conds: [done('rookie-scrim-strong')],
    desc: '正式比赛里遇到那支 Top10 队伍，你们 0:2 干净利落地输了。赛后数据惨不忍睹。',
    options: [
      { id: 'review-everything', label: '通宵复盘', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 4), stat(ENERGY, -10), stat(MORALE, 4)], msg: ['你把自己的每个失误都标了出来。', '第二天你把复盘笔记交给了教练。'], next: 'rookie-breakthrough' },
        f: { fx: [stat(ENERGY, -15), stat(STRESS, 8)], msg: ['复盘到凌晨三点，你睡着在键盘上。', '笔记半途而废。'], next: 'rookie-breakthrough' } },
      { id: 'move-on', label: '翻篇，下一场再来', chance: 0.7,
        s: { fx: [stat(MORALE, 6), stat(STRESS, -6)], msg: ['你选择把这场忘掉。', '心态稳了，但有些问题也没来得及总结。'], next: 'rookie-breakthrough' },
        f: { fx: [stat(STRESS, 8)], msg: ['嘴上说翻篇，脑子里全是那场比赛。', '训练时你频繁走神。'], next: 'rookie-breakthrough' } },
    ],
  },
  {
    id: 'rookie-breakthrough', title: '突破瓶颈', period: 'NORMAL', conds: [done('rookie-humbling-loss')],
    desc: '你的数据卡在一个平台上很久了。教练说差的是「阅读比赛的层次」，不是枪法。',
    options: [
      { id: 'watch-pro-demons', label: '拆解顶级选手第一视角', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 4), stat(MORALE, 8)], msg: ['你连续两周研究顶级自由人的走位。', '某天训练赛，你突然「看懂」了地图。'], next: 'rookie-form-waves' },
        f: { fx: [stat(ENERGY, -8)], msg: ['视频看了很多，但没消化。', '你卡在「好像懂了」的阶段。'], next: 'rookie-form-waves' } },
      { id: 'custom-drills', label: '定制训练项目', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 8)], msg: ['你给自己排了每天两小时的专项训练。', '两周后枪法有了肉眼可见的提升。'], next: 'rookie-form-waves' },
        f: { fx: [stat(STRESS, 8), stat(ENERGY, -8)], msg: ['训练计划太难，你坚持了三天就乱了。', '瓶颈还是那个瓶颈。'], next: 'rookie-form-waves' } },
    ],
  },
  {
    id: 'rookie-form-waves', title: '状态起伏', period: 'NORMAL', conds: [done('rookie-breakthrough')],
    desc: '你的状态开始像过山车：上午神挡杀神，下午空枪三连。没人说得清为什么。',
    options: [
      { id: 'track-data', label: '记录状态曲线', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 6)], msg: ['你开始记录每天的状态、睡眠和饮食。', '一个月后你找到了自己的「黄金时段」。'], next: 'rookie-exhaustion' },
        f: { fx: [stat(STRESS, 6)], msg: ['记录坚持了一周就断了。', '起伏还在继续。'], next: 'rookie-exhaustion' } },
      { id: 'ride-waves', label: '顺其自然', chance: 0.65,
        s: { fx: [stat(STRESS, -6), stat(MORALE, 4)], msg: ['你接受状态有高低。', '低谷时不硬撑，状态自然回来了。'], next: 'rookie-exhaustion' },
        f: { fx: [stat(MORALE, -6)], msg: ['你太随缘了，关键比赛的发挥变得不可控。', '教练开始对你皱眉。'], next: 'rookie-exhaustion' } },
    ],
  },
  {
    id: 'rookie-exhaustion', title: '疲惫累积', period: 'NORMAL', conds: [done('rookie-form-waves')],
    desc: '连着三个月的比赛和直播让你身体报警：白天嗜睡，晚上睡不着，训练质量直线下降。',
    options: [
      { id: 'cut-streams', label: '砍掉直播', chance: 0.65,
        s: { fx: [stat(ENERGY, 12), stat(STRESS, -8), stat(MORALE, 4)], msg: ['你把直播全停了，专注训练。', '两周后状态明显回升。'], next: 'rookie-holiday-decision' },
        f: { fx: [cstat('CAREER_EARNINGS', -400), stat(ENERGY, 6)], msg: ['直播合同让你没法全停。', '你只减了一半，杯水车薪。'], next: 'rookie-holiday-decision' } },
      { id: 'push-harder', label: '硬扛过去', chance: 0.4,
        s: { fx: [stat(MORALE, 8), stat(ENERGY, -10)], msg: ['你告诉自己职业选手都这样。', '扛过一个月，你确实没垮，但眼神空了。'], next: 'rookie-holiday-decision' },
        f: { fx: [stat(STRESS, 15), stat(ENERGY, -15), flag('BURNOUT_RISK', '倦怠风险', 'MENTAL')], msg: ['硬扛的结果是某天训练你直接在椅子上睡着了。', '队医建议你强制休息。'], next: 'rookie-holiday-decision' } },
    ],
  },
  {
    id: 'rookie-holiday-decision', title: '休赛取舍', period: 'OFFSEASON', conds: [done('rookie-exhaustion')],
    desc: '休赛期到了。有人约你去打高强度训练营，有人喊你去海边度假。你的身体告诉你答案。',
    options: [
      { id: 'real-rest', label: '真休息两周', chance: 0.7,
        s: { fx: [stat(ENERGY, 18), stat(STRESS, -12), stat(MORALE, 8)], msg: ['你关掉游戏，睡了两周好觉。', '归队时你觉得自己换了个脑子。'], next: 'rookie-major-qualifier' },
        f: { fx: [stat(STRESS, 6)], msg: ['你休息了，但群里每天都在聊转会，你忍不住刷。', '休息打了折扣。'], next: 'rookie-major-qualifier' } },
      { id: 'training-camp', label: '去高强度训练营', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.008 }],
        s: { fx: [attr(AIM, 3), attr(GAME_SENSE, 2), stat(ENERGY, -6)], msg: ['训练营十天后，你的枪法精进了。', '但腰酸背痛也回来了。'], next: 'rookie-major-qualifier' },
        f: { fx: [stat(ENERGY, -15), stat(STRESS, 8)], msg: ['训练营的强度超出你的恢复能力。', '新赛季第一周你就状态全无。'], next: 'rookie-major-qualifier' } },
    ],
  },
  {
    id: 'rookie-major-qualifier', title: '大赛预选', period: 'NORMAL', conds: [done('rookie-holiday-decision')],
    desc: 'Major 预选赛最后一轮，BO3 生死战。赢了进正赛，输了回家。',
    options: [
      { id: 'calm-execute', label: '按战术执行', chance: 0.6, mods: [{ attribute: GAME_SENSE, perPoint: 0.008 }],
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 12), flag('MAJOR_QUALIFIED', '晋级大赛', 'ACHIEVEMENT')], msg: ['你们 2:1 拿下生死战。', '晋级那一刻，你被队友抱得喘不过气。'], next: 'rookie-major-debut' },
        f: { fx: [stat(STRESS, 12)], msg: ['你们被拖入第三图，最后惜败。', '就差两个回合，你记了一整年。'], next: 'rookie-major-debut' } },
      { id: 'hero-mode', label: '靠个人能力carry', chance: 0.45, mods: [{ attribute: CLUTCH, perPoint: 0.008 }],
        s: { fx: [attr(CLUTCH, 3), cstat('TOTAL_KILLS', 55), stat(MORALE, 12)], msg: ['你一个人打出了统治级数据。', '赛后解说喊你的 ID 喊到破音。'], next: 'rookie-major-debut' },
        f: { fx: [stat(STRESS, 15), stat(MORALE, -8)], msg: ['个人英雄主义害了你。', '你最后一张图的数据惨不忍睹。'], next: 'rookie-major-debut' } },
    ],
  },
  {
    id: 'rookie-major-debut', title: '大赛首秀', period: 'NORMAL', conds: [done('rookie-major-qualifier')],
    desc: 'Major 正赛第一场，对手是世界排名前三的队伍。观众席上有人举着你的应援牌。',
    options: [
      { id: 'keep-humble', label: '低调务实', chance: 0.55, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), stat(MORALE, 10)], msg: ['你按部就班地打，数据虽然不华丽但很稳。', '教练赛后罕见地夸了你。'], next: 'rookie-big-stage-choke' },
        f: { fx: [stat(STRESS, 14)], msg: ['舞台太大，你的手又开始抖了。', '你打出了生涯最差的线下数据。'], next: 'rookie-redemption' } },
      { id: 'shoot-for-stars', label: '挑战顶级选手', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), stat(MORALE, 12), flag('TOP10_SCALP', '击败世界前十', 'ACHIEVEMENT')], msg: ['你在顶级选手面前打出了几个精彩对位。', '赛后对方主动和你碰了碰拳。'], next: 'rookie-redemption' },
        f: { fx: [stat(STRESS, 16), stat(MORALE, -10)], msg: ['你想单杀对方明星选手，结果被反杀三次。', '弹幕全是嘲讽。'], next: 'rookie-redemption' } },
    ],
  },
  {
    id: 'rookie-big-stage-choke', title: '大赛手软', period: 'NORMAL', conds: [done('rookie-major-debut')],
    desc: '关键局 15:14，你们守 A 点。你架枪的位置空了，对方静步摸过来完成了拆除。',
    options: [
      { id: 'own-the-mistake', label: '承认失误', chance: 0.6,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 6)], msg: ['你在赛后采访里认了那个失误。', '出人意料，评论区反而开始鼓励你。'], next: 'rookie-redemption' },
        f: { fx: [stat(STRESS, 10), stat(MORALE, -6)], msg: ['你认了错，但那个空位反复出现在梦里。', '你开始怀疑自己的架枪习惯。'], next: 'rookie-redemption' } },
      { id: 'blame-luck', label: '归咎于运气', chance: 0.45,
        s: { fx: [stat(MORALE, 4)], msg: ['你说那局是运气问题。', '但教练的复盘笔记里写着：不是运气。'], next: 'rookie-redemption' },
        f: { fx: [stat(TEAM_CONFLICT, 3), stat(STRESS, 8)], msg: ['甩锅给运气让队友不太舒服。', '更衣室里没人接话。'], next: 'rookie-redemption' } },
    ],
  },
  {
    id: 'rookie-redemption', title: '救赎表现', period: 'NORMAL', conds: [done('rookie-major-debut')],
    desc: '下一场对阵淘汰边缘的队伍。所有人都盯着你：上一场的失误，这一场怎么还。',
    options: [
      { id: 'steady-rebound', label: '稳稳打回来', chance: 0.6, mods: [{ attribute: CONSISTENCY, perPoint: 0.009 }],
        s: { fx: [attr(CONSISTENCY, 3), cstat('TOTAL_KILLS', 48), stat(MORALE, 12)], msg: ['你没有刻意证明什么，只是打得很扎实。', '这场之后，质疑声小了一半。'], next: 'rookie-title-run' },
        f: { fx: [stat(STRESS, 12)], msg: ['想太多导致又一场平淡的发挥。', '评论区开始叫你「大赛软脚虾」。'], next: 'rookie-title-run' } },
      { id: 'explosive-rebound', label: '打出爆发数据', chance: 0.45, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), cstat('TOTAL_KILLS', 62), stat(MORALE, 14)], msg: ['你打出了 62 击杀，对面被打得叫暂停。', '这场成为你职业生涯的转折点。'], next: 'rookie-title-run' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['越想爆发越急，你再次发挥失常。', '教练把你换下了场。'], next: 'rookie-title-run' } },
    ],
  },
  {
    id: 'rookie-title-run', title: '冠军之路', period: 'NORMAL', conds: [done('rookie-redemption')],
    desc: '你们一路杀进淘汰赛。半决赛对手是你们的「克星」，交手记录全败。',
    options: [
      { id: 'study-weakness', label: '研究克星弱点', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 8)], msg: ['你发现对方指挥固定习惯：残局总喜欢绕后。', '这个发现成了你们翻盘的关键。'], next: 'rookie-championship-point' },
        f: { fx: [stat(ENERGY, -8)], msg: ['研究到一半被自己的焦虑打断。', '你什么结论都没得出来。'], next: 'rookie-championship-point' } },
      { id: 'psych-war', label: '心理战', chance: 0.5,
        s: { fx: [attr(LEADERSHIP, 2), stat(MORALE, 8)], msg: ['你在采访里放话要「终结连败」。', '对面果然有点被激怒，节奏乱了。'], next: 'rookie-championship-point' },
        f: { fx: [stat(TEAM_CONFLICT, 2), stat(STRESS, 8)], msg: ['放话之后你反而压力更大。', '对面教练似乎早就等着你这么说。'], next: 'rookie-championship-point' } },
    ],
  },
  {
    id: 'rookie-championship-point', title: '冠军点', period: 'FINAL_DECISIVE_MOMENT', conds: [done('rookie-title-run')],
    desc: '决赛 15:14，你们手握赛点。整座场馆的灯都亮着，你能听见自己的心跳。',
    options: [
      { id: 'ice-veins', label: '心如止水打最后一局', chance: 0.55, mods: [{ attribute: CLUTCH, perPoint: 0.01 }],
        s: { fx: [attr(CLUTCH, 3), trophy('S_TIER', 1), stat(MORALE, 15), flag('FIRST_TITLE', '首个冠军', 'ACHIEVEMENT')], msg: ['你在最后十秒完成了决定性击杀。', '夺冠的那一刻，你听见全场在喊你的 ID。'], next: 'rookie-team-disband' },
        f: { fx: [stat(STRESS, 16), stat(MORALE, -6)], msg: ['赛点局你空枪了。', '加时赛你们没能顶住，冠军擦肩而过。'], next: 'rookie-team-disband' } },
      { id: 'go-all-in', label: '最后一波全压', chance: 0.4, mods: [{ attribute: AIM, perPoint: 0.009 }],
        s: { fx: [attr(AIM, 3), trophy('S_TIER', 1), cstat('TOTAL_KILLS', 30), flag('FIRST_TITLE', '首个冠军', 'ACHIEVEMENT')], msg: ['你带头冲锋，一波流带走比赛。', '冠军奖杯比想象中沉。'], next: 'rookie-team-disband' },
        f: { fx: [stat(STRESS, 15), stat(MORALE, -10)], msg: ['全压变成全送。', '冠军奖杯在对面手里，你站在原地看完全场。'], next: 'rookie-team-disband' } },
    ],
  },
  // ============ 极端事件 ============
  {
    id: 'rookie-team-disband', title: '队伍解散', period: 'NORMAL', conds: [done('rookie-championship-point')],
    desc: '俱乐部宣布重组：两名主力被卖，教练离职，你的位置突然悬空。',
    options: [
      { id: 'wait-out', label: '留下来等新阵容', chance: 0.55,
        s: { fx: [stat(MORALE, 6), stat(STRESS, -4)], msg: ['你选择赌俱乐部的重建计划。', '新教练到任第一天，点名让你进首发。'], next: 'rookie-online-harassment' },
        f: { fx: [stat(STRESS, 12)], msg: ['等待的日子很难熬，训练都变得形式化。', '你开始想别的出路。'], next: 'rookie-online-harassment' } },
      { id: 'jump-ship', label: '主动找下家', chance: 0.5,
        s: { fx: [transfer('mouz'), stat(MORALE, 10)], msg: ['你在转会窗关闭前谈好了新队。', '新环境让你重新燃起了斗志。'], next: 'rookie-online-harassment' },
        f: { fx: [stat(STRESS, 14)], msg: ['谈了两家都黄了。', '你只能留在原地，处境尴尬。'], next: 'rookie-online-harassment' } },
    ],
  },
  {
    id: 'rookie-online-harassment', title: '网络暴力', period: 'NORMAL', conds: [done('rookie-team-disband')],
    desc: '一场失利后，你的私人社交账号被挖了出来。几千条私信涌进来，没有一条是善意的。',
    options: [
      { id: 'lawyer-up', label: '保留证据维权', chance: 0.6,
        s: { fx: [stat(MORALE, 8), flag('LEGAL_ACTION', '依法维权', 'CAREER')], msg: ['你截图了所有私信，联系了律师。', '发出声明后，最恶毒的那批人删了号。'], next: 'rookie-fight-incident' },
        f: { fx: [stat(STRESS, 10)], msg: ['律师费让你有点犹豫。', '你删了所有社交软件，眼不见为净。'], next: 'rookie-fight-incident' } },
      { id: 'keep-playing', label: '不回应，继续打', chance: 0.55,
        s: { fx: [attr(CONSISTENCY, 2), stat(STRESS, -4)], msg: ['你把注意力锁在训练上。', '两周后舆论自己散了。'], next: 'rookie-fight-incident' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -8)], msg: ['你假装不在乎，但每条私信都看完了。', '你的睡眠开始出问题。'], next: 'rookie-fight-incident' } },
    ],
  },
  {
    id: 'rookie-fight-incident', title: '队内斗殴', period: 'NORMAL', conds: [done('rookie-online-harassment')],
    desc: '训练赛里有个队友骂了你母亲。你们在训练室动了手，椅子翻了一地。',
    options: [
      { id: 'report-first', label: '先上报俱乐部', chance: 0.55,
        s: { fx: [stat(TEAM_CONFLICT, -6), stat(MORALE, 8), flag('DISCIPLINED', '纪律优先', 'CAREER')], msg: ['俱乐部罚了他，也给了你警告。', '事情闹到台面，反而没人再敢阴阳怪气。'], next: 'rookie-blackmail-hook' },
        f: { fx: [stat(TEAM_CONFLICT, 4), stat(STRESS, 10)], msg: ['上报后处理结果模棱两可。', '你在更衣室里变得更加孤立。'], next: 'rookie-blackmail-hook' } },
      { id: 'settle-hands', label: '私了，靠拳头', chance: 0.45,
        s: { fx: [stat(TEAM_CONFLICT, -8), stat(MORALE, 10)], msg: ['你把他按在墙上的那一下，全队都看见了。', '从那以后没人敢惹你，但隔阂也留下了。'], next: 'rookie-blackmail-hook' },
        f: { fx: [stat(TEAM_CONFLICT, 8), stat(STRESS, 14), stat(MORALE, -6)], msg: ['你被俱乐部记了大过。', '他没事，你却背上了处分。'], next: 'rookie-blackmail-hook' } },
    ],
  },
  {
    id: 'rookie-blackmail-hook', title: '敲诈阴影', period: 'NORMAL', conds: [done('rookie-fight-incident')],
    desc: '有人拿着你斗殴那晚的监控截图来找你：给钱，或者让截图「不小心」发出去。',
    options: [
      { id: 'go-clean', label: '直接报警', chance: 0.6,
        s: { fx: [stat(MORALE, 10), flag('CLEAN_ACCOUNT', '履历干净', 'CAREER')], msg: ['你把截图和聊天记录全部交给了警方。', '对方被带走的那天，你睡了个好觉。'], next: 'rookie-prodigy-discovery' },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['报警后对方跑了，截图仍在暗处。', '这件事像根刺，偶尔会扎你一下。'], next: 'rookie-prodigy-discovery' } },
      { id: 'pay-up', label: '花钱消灾', chance: 0.5,
        s: { fx: [cstat('CAREER_EARNINGS', -3000), stat(STRESS, -6)], msg: ['你转了一笔钱，截图没有流出去。', '但你知道对方留着底片。'], next: 'rookie-prodigy-discovery' },
        f: { fx: [cstat('CAREER_EARNINGS', -5000), stat(STRESS, 14)], msg: ['对方得寸进尺，要了一次又一次。', '你意识到这是无底洞。'], next: 'rookie-prodigy-discovery' } },
    ],
  },
  // ============ 世界线转换 ============
  {
    id: 'rookie-prodigy-discovery', title: '天赋觉醒', period: 'NORMAL', conds: [done('rookie-blackmail-hook')],
    desc: '一支豪门战队的分析师看了你的比赛录像，给了你一个大胆的评价：「你是被埋没的天才。」',
    options: [
      { id: 'embrace-talent', label: '接受天才定位', chance: 0.65,
        s: { fx: [wl('prodigy'), stat(MORALE, 15), flag('CROSSED_TO_PRODIGY', '转入天才线', 'CUSTOM')], msg: ['你决定相信那份评价。', '你的职业生涯翻开了新的一页。'], next: null },
        f: { fx: [stat(STRESS, 10)], msg: ['你犹豫了，天才的帽子太重。', '你还是留在了原来的轨迹上。'], next: 'rookie-grinder-reality' } },
      { id: 'stay-course', label: '保持现状', chance: 0.7,
        s: { fx: [stat(MORALE, 6)], msg: ['你选择一步一个脚印。', '分析师的那份评价被你锁进了抽屉。'], next: 'rookie-grinder-reality' },
        f: { fx: [stat(STRESS, 8)], msg: ['你嘴上说保持现状，心里却开始期待更多。', '这种感觉让你坐立不安。'], next: 'rookie-grinder-reality' } },
    ],
  },
  {
    id: 'rookie-grinder-reality', title: '现实打磨', period: 'NORMAL', conds: [done('rookie-blackmail-hook')],
    desc: '经纪人帮你算了笔账：留在中游队伍打三年，不如去低级别联赛当绝对核心，稳扎稳打出成绩。',
    options: [
      { id: 'step-down', label: '去低级别当核心', chance: 0.6,
        s: { fx: [wl('grinder'), stat(MORALE, 12), flag('CROSSED_TO_GRINDER', '转入磨砺线', 'CUSTOM')], msg: ['你去了低级别联赛，成了绝对核心。', '这里的节奏更慢，但每场比赛都在打磨你。'], next: null },
        f: { fx: [stat(STRESS, 8)], msg: ['你担心降级是职业倒退。', '最终你没有迈出那一步。'], next: 'rookie-matchfixing-tempt' } },
      { id: 'stay-put', label: '留在中游队伍', chance: 0.7,
        s: { fx: [stat(MORALE, 8)], msg: ['你选择留下，继续和熟悉的队友磨合。', '慢一点，但至少安全。'], next: 'rookie-matchfixing-tempt' },
        f: { fx: [stat(MORALE, -4), stat(STRESS, 6)], msg: ['留下后你开始怀疑这个决定。', '「如果当初去了低级别……」'], next: 'rookie-matchfixing-tempt' } },
    ],
  },
  {
    id: 'rookie-matchfixing-tempt', title: '诱惑初现', period: 'NORMAL', conds: [done('rookie-blackmail-hook')],
    desc: '有人在你常去的网吧门口堵住你：「一场比赛的失误，够你半年工资。」他递来一张纸条。',
    options: [
      { id: 'walk-away', label: '转身离开', chance: 0.75,
        s: { fx: [stat(MORALE, 10), flag('REFUSED_FIX', '拒绝假赛', 'ACHIEVEMENT')], msg: ['你把纸条揉成一团扔进了垃圾桶。', '那个人的眼神你不愿意再想起。'], next: 'rookie-veteran-handoff' },
        f: { fx: [stat(STRESS, 10)], msg: ['你离开时腿有点发软。', '那张纸条的内容你其实扫了一眼，记性很好。'], next: 'rookie-veteran-handoff' } },
      { id: 'hear-him-out', label: '听完再说', chance: 0.4,
        s: { fx: [wl('matchfixing'), stat(MORALE, 4), stat(STRESS, 12)], msg: ['你坐下来听了十分钟。', '走出网吧时，你的心跳快得可怕。'], next: null },
        f: { fx: [stat(STRESS, 14), stat(MORALE, -6)], msg: ['你听了，也动摇了，最后还是拒绝了。', '但那笔数字跟着你回了家。'], next: 'rookie-veteran-handoff' } },
    ],
  },
  // ============ 尾声 ============
  {
    id: 'rookie-veteran-handoff', title: '传承经验', period: 'NORMAL', conds: [done('rookie-matchfixing-tempt')],
    desc: '俱乐部安排你带两个青训新人。你想起自己刚入队时的笨拙。',
    options: [
      { id: 'teach-well', label: '认真带新人', chance: 0.7,
        s: { fx: [attr(LEADERSHIP, 3), stat(MORALE, 8)], msg: ['你把踩过的坑都讲给他们听。', '其中一个新人后来成了你的得力队友。'], next: 'rookie-farewell' },
        f: { fx: [stat(ENERGY, -6)], msg: ['你带得马马虎虎，新人跟不上。', '教练委婉地提醒了你。'], next: 'rookie-farewell' } },
      { id: 'set-example', label: '用行动示范', chance: 0.6,
        s: { fx: [attr(CONSISTENCY, 2), stat(MORALE, 6)], msg: ['你让新人看你怎么训练。', '言传不如身教。'], next: 'rookie-farewell' },
        f: { fx: [stat(STRESS, 6)], msg: ['示范时你发挥失常，场面有点尴尬。', '但新人还是学到了你的态度。'], next: 'rookie-farewell' } },
    ],
  },
  {
    id: 'rookie-farewell', title: '青训告别', period: 'NORMAL', conds: [done('rookie-veteran-handoff')],
    desc: '你正式离开青训体系，成为完全的职业选手。离开那天，训练室的门在你身后关上。',
    options: [
      { id: 'graduate', label: '带着收获离开', chance: 0.7,
        s: { fx: [trophy('MVP', 1), stat(MORALE, 12), flag('ROOKIE_GRADUATE', '青训毕业', 'ACHIEVEMENT')], msg: ['你回头看了一眼训练室。', '下一站，职业赛场。'], next: 'rookie-gear-choice' },
        f: { fx: [stat(MORALE, -4)], msg: ['离开时你有点怅然。', '但你的脚步没有停。'], next: 'rookie-gear-choice' } },
      { id: 'thank-team', label: '请全队吃顿饭', chance: 0.65,
        s: { fx: [stat(TEAM_CONFLICT, -4), stat(MORALE, 8)], msg: ['散伙饭上，老将破天荒敬了你一杯。', '这一顿饭花掉你不少钱，但你觉得很值。'], next: 'rookie-gear-choice' },
        f: { fx: [stat(STRESS, 4)], msg: ['饭局上有人提起了那场斗殴。', '气氛微妙地安静了几秒。'], next: 'rookie-gear-choice' } },
    ],
  },
  // ============ 风味日常（可重复） ============
  {
    id: 'rookie-gear-choice', title: '外设抉择', period: 'NORMAL', conds: [done('rookie-farewell')],
    desc: '新赛季赞助商换了，你不得不用新键盘。旧键盘的每个键位你都记得。',
    options: [
      { id: 'adapt-fast', label: '快速适应新外设', chance: 0.6, mods: [{ attribute: AIM, perPoint: 0.006 }],
        s: { fx: [attr(AIM, 2), stat(MORALE, 6)], msg: ['你花了一周适应新键盘的键程。', '手感回来了，钱也省了。'], next: 'rookie-gym-routine' },
        f: { fx: [stat(STRESS, 8)], msg: ['新键盘怎么都不顺手。', '你在直播间吐槽了两句，被赞助商看到。'], next: 'rookie-gym-routine' } },
      { id: 'buy-old', label: '自费买同款旧键盘', chance: 0.55,
        s: { fx: [cstat('CAREER_EARNINGS', -200), stat(MORALE, 8)], msg: ['你自费买了一把同款。', '训练状态立刻回来了。'], next: 'rookie-gym-routine' },
        f: { fx: [stat(STRESS, 6)], msg: ['同款停产了，你只能买二手。', '二手键盘的按键偶尔失灵。'], next: 'rookie-gym-routine' } },
    ],
  },
  {
    id: 'rookie-gym-routine', title: '体能训练', period: 'NORMAL', conds: [done('rookie-farewell')],
    desc: '新教练引入体能课。你第一次知道打职业还要跑步。',
    options: [
      { id: 'commit-fitness', label: '坚持体能训练', chance: 0.6,
        s: { fx: [stat(ENERGY, 10), stat(STRESS, -4)], msg: ['一个月后你的专注时长明显变长。', '教练说：手稳是练出来的。'], next: 'rookie-film-study' },
        f: { fx: [stat(ENERGY, -6)], msg: ['你跑了三天就找理由请假。', '训练室里的椅子越来越难坐。'], next: 'rookie-film-study' } },
      { id: 'skip-fitness', label: '只练游戏', chance: 0.65,
        s: { fx: [attr(AIM, 2), stat(ENERGY, -4)], msg: ['你把这时间拿去练枪。', '枪法涨了，腰开始疼了。'], next: 'rookie-film-study' },
        f: { fx: [stat(ENERGY, -8)], msg: ['没锻炼的身体开始抗议。', '长时间训练后你的肩膀发酸。'], next: 'rookie-film-study' } },
    ],
  },
  {
    id: 'rookie-film-study', title: '录像分析', period: 'NORMAL', conds: [done('rookie-farewell')],
    desc: '复盘课上新教练要求每个人讲自己的一场失误。你翻出了三年前的黑历史。',
    options: [
      { id: 'share-cringe', label: '公开讲黑历史', chance: 0.65,
        s: { fx: [attr(GAME_SENSE, 3), stat(MORALE, 6)], msg: ['你把自己最蠢的失误投到了大屏幕上。', '大家笑完之后，讨论得很认真。'], next: 'rookie-z-training-day' },
        f: { fx: [stat(STRESS, 8)], msg: ['讲黑历史讲到一半你卡壳了。', '尴尬归尴尬，但教训是记住了。'], next: 'rookie-z-training-day' } },
      { id: 'pick-easy', label: '挑个简单的讲', chance: 0.7,
        s: { fx: [stat(MORALE, 4)], msg: ['你讲了个无关痛痒的失误。', '新教练看了你一眼，没说什么。'], next: 'rookie-z-training-day' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['有人嘀咕了一句「不敢讲真问题」。', '你假装没听见。'], next: 'rookie-z-training-day' } },
    ],
  },
  {
    id: 'rookie-z-training-day', title: '训练日常', period: 'NORMAL', conds: [], repeatable: true,
    desc: '普通的一天：热手、训练赛、复盘、加练。职业选手的日常就是这么枯燥。',
    options: [
      { id: 'steady-grind', label: '按计划完成训练', chance: 0.7,
        s: { fx: [attr(CONSISTENCY, 1), stat(MORALE, 4)], msg: ['今天的训练完成度很高。', '你按部就班地变强。'], next: 'rookie-z-scrim-day' },
        f: { fx: [stat(ENERGY, -4)], msg: ['训练到一半你走神了。', '你决定明天补上。'], next: 'rookie-z-scrim-day' } },
      { id: 'extra-drills', label: '给自己加练', chance: 0.55, mods: [{ attribute: AIM, perPoint: 0.005 }],
        s: { fx: [attr(AIM, 1), stat(ENERGY, -6)], msg: ['加练的专项让你的枪感更好。', '但明天可能会困。'], next: 'rookie-z-scrim-day' },
        f: { fx: [stat(ENERGY, -10), stat(STRESS, 4)], msg: ['加练过头，反而影响了状态。', '你学会了什么叫适度。'], next: 'rookie-z-scrim-day' } },
    ],
  },
  {
    id: 'rookie-z-scrim-day', title: '训练赛日常', period: 'NORMAL', conds: [], repeatable: true,
    desc: '今天的训练赛对手是风格迥异的一支队伍。你的任务是适应他们的节奏。',
    options: [
      { id: 'adapt-midgame', label: '赛中调整', chance: 0.6,
        s: { fx: [attr(GAME_SENSE, 1), stat(MORALE, 4)], msg: ['你半场就摸清了他们的习惯。', '教练在赛后就这一点表扬了你。'], next: 'rookie-z-team-chat' },
        f: { fx: [stat(STRESS, 6)], msg: ['你适应得太慢，被对面牵着走。', '复盘时你记下了教训。'], next: 'rookie-z-team-chat' } },
      { id: 'practice-calls', label: '练自己的战术', chance: 0.65,
        s: { fx: [attr(LEADERSHIP, 1), stat(MORALE, 4)], msg: ['你试着在训练赛里喊新战术。', '队友配合了一次，效果不错。'], next: 'rookie-z-team-chat' },
        f: { fx: [stat(TEAM_CONFLICT, 1)], msg: ['新战术喊了两遍都没人接。', '你明白默契需要时间。'], next: 'rookie-z-team-chat' } },
    ],
  },
  {
    id: 'rookie-z-team-chat', title: '队内闲聊', period: 'NORMAL', conds: [], repeatable: true,
    desc: '训练结束后，大家在休息室聊起了圈内的八卦：谁要转会，谁又涨薪了。',
    options: [
      { id: 'join-in', label: '加入闲聊', chance: 0.7,
        s: { fx: [stat(TEAM_CONFLICT, -2), stat(MORALE, 5)], msg: ['你听了一肚子圈内八卦。', '和队友的关系更近了一点。'], next: 'rookie-z-training-day' },
        f: { fx: [stat(STRESS, 3)], msg: ['你接了个话题，结果说错了一件事。', '大家笑你消息不灵通。'], next: 'rookie-z-training-day' } },
      { id: 'head-home', label: '早点回去休息', chance: 0.65,
        s: { fx: [stat(ENERGY, 6), stat(STRESS, -3)], msg: ['你选择早点睡。', '第二天训练状态很好。'], next: 'rookie-z-training-day' },
        f: { fx: [stat(ENERGY, 2)], msg: ['你回去了，但躺在床上刷手机到半夜。', '和早睡的效果差不多打了个平手。'], next: 'rookie-z-training-day' } },
    ],
  },
];
